### ISSUE TITLE
Parse error when placing implicit arguments in parenthesis

### ISSUE THREAD

**Issue by A-Manning** [FStarLang/FStar#765] opened 2016-11-17 20:42 UTC
The function 
`val foo: (#n:nat) -> Type -> Tot Type` 
gives a parse error, but removing the parenthesis on the implicit, as below, verifies fine. 

`val foo: #n:nat -> Type -> Tot Type`

Why is this?

**Comment by kyoDralliam** [comment] 2016-11-17 23:56
The origin of the bug is that the parser is parsing an optional qualifier ("#") followed by an arbitrary term which can happen to be ascribed ("n:nat") and parenthesized ("(n:nat)"). I fixed it by adding a special case handling this issue in the branch kyod_parser which will hopefully be merged soon. 

I wil try to see if I can do something cleaner by rearranging the syntactical categories of terms...

**Comment by catalin-hritcu** [comment] 2016-11-18 00:08
Should probably also double-check with @nikswamy  that allowing 
```
val foo'': (n:nat) -> Type -> Tot Type
```
is a feature, not a bug in the first place. I remember this issue came up in some past discussions.

**Comment by kyoDralliam** [comment] 2016-11-18 00:22
Already checked, and we agreed that it was something we wanted to be valid F* code.

**Comment by catalin-hritcu** [comment] 2016-11-29 02:26
Fixed by Kenji's new parser

**Closed by catalin-hritcu** 2016-11-29 02:26 UTC
Labels: bug, syntax
