### ISSUE TITLE
Invalid_argument("List.fold_right2: list lengths differ")

### ISSUE THREAD

**Issue by msprotz** [FStarLang/FStar#1861] opened 2019-09-26 13:57 UTC
On HACL* branch `protz_meta_interfaces`, processing the following snippet in interactive mode crashes F*:

```

let f1: #w35434: Hacl.Impl.Chacha20.Core32xN.lanes
  -> Prims.Tot
    (
          arg_Hacl_Impl_Chacha20_Core32xN_double_round35435:
            (fun (#w35438: Hacl.Impl.Chacha20.Core32xN.lanes) ->
                st35439: Hacl.Impl.Chacha20.Core32xN.state w35438
                  -> FStar.HyperStack.ST.Stack Prims.unit _ _) #w35434
        -> Prims.Tot
          ((fun (#w35436: Hacl.Impl.Chacha20.Core32xN.lanes) ->
                st35437: Hacl.Impl.Chacha20.Core32xN.state w35436
                  -> FStar.HyperStack.ST.Stack Prims.unit _ _) #w35434))

=
  fun
  (#w35397: Hacl.Impl.Chacha20.Core32xN.lanes)
  (arg_Hacl_Impl_Chacha20_Core32xN_double_round35398:
    (fun (#w35400: Hacl.Impl.Chacha20.Core32xN.lanes) ->
        st35401: Hacl.Impl.Chacha20.Core32xN.state w35400 -> FStar.HyperStack.ST.Stack Prims.unit) #w35397
    )
  (st35399: Hacl.Impl.Chacha20.Core32xN.state w35397)
  ->
  let _uu___35402 = arg_Hacl_Impl_Chacha20_Core32xN_double_round35398 st35399 in
  let _uu___35403 = arg_Hacl_Impl_Chacha20_Core32xN_double_round35398 st35399 in
  let _uu___35404 = arg_Hacl_Impl_Chacha20_Core32xN_double_round35398 st35399 in
  let _uu___35405 = arg_Hacl_Impl_Chacha20_Core32xN_double_round35398 st35399 in
  let _uu___35406 = arg_Hacl_Impl_Chacha20_Core32xN_double_round35398 st35399 in
  let _uu___35407 = arg_Hacl_Impl_Chacha20_Core32xN_double_round35398 st35399 in
  let _uu___35408 = arg_Hacl_Impl_Chacha20_Core32xN_double_round35398 st35399 in
  let _uu___35409 = arg_Hacl_Impl_Chacha20_Core32xN_double_round35398 st35399 in
  let _uu___35410 = arg_Hacl_Impl_Chacha20_Core32xN_double_round35398 st35399 in
  arg_Hacl_Impl_Chacha20_Core32xN_double_round35398 st35399
```

Thanks,

Jonathan

**Comment by mtzguido** [comment] 2019-10-01 15:31
This is due to a bad computation type (the `Stack unit` without pre/post arguments) reaching the unifier. I have, for now, fixed the unifier to at least not crash, but I'm not sure why this is not failing before reaching it, as the computation type is ill-typed itself.

Smaller repro:
```fstar
let test : (f : unit -> Exn unit _ _) -> unit =
    fun (f : unit -> Exn unit) -> ()
```

**Comment by aseemr** [comment] 2020-04-13 07:06
I actually get a proper error about effect constructor not being fully applied (on Guido's small example):

```
Test.fst(4,25-4,29): (Error 35) Effect constructor is not fully applied; expected 3 args, got 1 args, i.e., FStar.Pervasives.Exn Prims.unit
Test.fst(4,25-4,29): (Error 12) Expected type "Effect"; but "FStar.Pervasives.Exn Prims.unit" has type "pre: FStar.Pervasives.ex_pre -> post: FStar.Pervasives.ex_post' Prims.unit pre -> Prims.Tot Effect"
2 errors were reported (see above)
```

(Note that this is not the error coming from `Rel` that Guido added.)

**Comment by mtzguido** [comment] 2020-04-16 06:29
The problem is that at some point we *log* the error 12 (see `subtype_fail`) but carry on, so we reach the unifier with a bogus computation type. My patch makes it not crash, and then we get the errors reported. Without my patch we actually get the crash plus the error 12.

Ill-typed terms should never reach the unifier, right?

Another solution is to `raise_error` in `subtype_fail`. But we probably need to investigate a bit deeper.

**Comment by aseemr** [comment] 2020-04-16 06:58
I reverted your patch and I still get the errors, and no crash, the error `35` in `Env.fs` is a `raise_erro`. Sorry if I am totally missing something.

**Comment by aseemr** [comment] 2020-04-16 10:31
Whoops, you are right, can repro :/.

**Comment by aseemr** [comment] 2020-04-16 11:43
Another thing we could do is, make ill-typed effect constructor applications fail hard, something like this:

https://github.com/FStarLang/FStar/commit/aeae9934975565094318552d65bf7964fc1591cc

**Comment by mtzguido** [comment] 2020-04-16 18:20
Ah yes, indeed. Though can we ever really just carry on with a typing error? It seems hard to guarantee they won't affect the rest of the typechecking procedure. In some languages one can recover at the point of an ascription, but since we're higher order and can call the normalizer, I don't think anything like that could work?

Verification errors could indeed just be logged.

(FWIW, in tactics we make sure to abort before running if any error was logged. Otherwise tactics with an assertion failure could run and get stuck.)

**Comment by aseemr** [comment] 2020-11-18 09:36
@nikswamy reported it when using layered effects. I have fixed it so that computation types are checked with `failhard=true`. But should we failhard on all subtyping errors?

**Comment by aseemr** [comment] 2022-03-15 16:33
Closing this issue since the root cause of this one was fixed, the question about failing hard on all subtyping errors is orthogonal.

**Closed by aseemr** 2022-03-15 16:33 UTC
Labels: kind/bug, component/unifier, milestone/everest-v1
