### ISSUE TITLE
What's up with Data_app?

### ISSUE THREAD

**Issue by cpitclaudel** [FStarLang/FStar#1303] opened 2017-10-11 15:46 UTC
I'm confused about Data_app:

* We have a mk_data function that introduces `Data_app` annotations, but it's dead code.  Should it be used?

```
let mk_data l args =
  match args with
    | [] ->
      mk (Tm_meta(fvar l Delta_constant (Some Data_ctor), Meta_desugared Data_app)) None (range_of_lid l)
    | _ ->
      let e = mk_app (fvar l Delta_constant (Some Data_ctor)) args in
      mk (Tm_meta(e, Meta_desugared Data_app)) None e.pos
```

* We don't seem to use Data_app anywhere except for resugaring, but there it'd be enough to just check for a capitalized name, right?

Can we just get rid of that annotation entirely? And is it bad that mk_data isn't used anywhere?

**Comment by mtzguido** [comment] 2017-10-19 13:28
What's preventing the merge of your fix to this? I sometimes run into this and it's always annoying, so it'd be great to merge it.

**Comment by cpitclaudel** [comment] 2017-10-19 14:22
Life is :) I was hoping to merge this last Friday, but with the CI down I couldn't. Now I'm back at work, so things are slower.

**Comment by mtzguido** [comment] 2017-10-19 14:26
Cool, no rush! I was just wondering if anything was missing.

**Comment by cpitclaudel** [comment] 2017-10-19 19:09
Ah, there is one thing preventing the merge. A circular dependency in F#.
tosyntax.vsproj depends on syntax,vsproj, and I need a dependency in the other direction.

**Comment by cpitclaudel** [comment] 2017-10-19 19:14
Should I just move ToSyntax.Env into Syntax? Or move Syntax.Print to ToSyntax?

**Comment by mtzguido** [comment] 2017-10-19 19:27
Can you say more about that circularity? I just merged 8edeba6 and it seems to have compiled OK (but I see a lot of `Binder uu___ is not used`).

**Comment by cpitclaudel** [comment] 2017-10-19 19:35
I'm working on cpitclaudel_1293; I think you only merged part of that branch.

**Comment by mtzguido** [comment] 2017-10-19 19:38
Indeed. Taking a look now ..

**Comment by mtzguido** [comment] 2017-10-19 19:54
Moving ToSyntax.Env into syntax/ looks like the sanest solution.

**Comment by mtzguido** [comment] 2018-01-22 16:18
I'll try to make this happen soon.

**Comment by mtzguido** [comment] 2018-03-04 00:33
I merged your `cpitclaudel_1293` branch into a current F* and moved the desugaring environment into `syntax/` to avoid the circular dep. The result is in `guido_1303`, and CI just gave a green for it.

If you have a couple of minutes could you check that it works as intended? The merge was non-trivial and I could have messed up. I do see prettier output but I haven't tried all of the bullets in #1293.

I stacked this over some tactics stuff which will get to master in a few days. I'll probably merge this with it unless you find I made some mistake or some bug appears.

Thanks a lot for working on this, the better resugaring and robustness is great.

**Closed** 2018-03-04 17:44 UTC
Labels: component/desugaring, kind/question

**Comment by cpitclaudel** [comment] 2018-03-04 21:41
Just had a quick look; it looks pretty good! I'll admit I didn't read the whole thing though :)
I left one quick question in https://github.com/FStarLang/FStar/commit/29b070c4fcec6165486f12fa1c79229899246823
