### ISSUE TITLE
Surprising subtyping error

### ISSUE THREAD

**Issue by s-zanella** [FStarLang/FStar#543] opened 2016-06-03 19:00 UTC
This is easy to work around, but quite common and very annoying:

``` F#
module M

type range = r:(int * int) { fst r <= snd r }
type wider (r1:range) (r2:range) = fst r1 <= fst r2 /\ snd r2 <= snd r1
type within (n:int) (r:range) = fst r <= n /\ n <= snd r
type rint (r:range) = n:int {fst r <= n /\ n <= snd r}

let u:range = (0,1)
assume val r : (r:range{wider r u})

val f: n:int {within n u} -> m:int {within m r}
let f n = n

val g: rint u -> rint r
let g n = n

//This works
//let g n = let m:int = n in m
```

```
$ fstar.exe --universes M.fst
M.fst(15,10-15,11) : Error
Expected expression of type "(M.rint M.r)";
got expression "n" of type "(M.rint M.u)"
```

**Comment by vkanne-msft** [comment] 2016-06-16 20:27
We are agreeing that this is a common situation and the behavior is sub-optimal. The fix is not straightforward. We will look to fixing it in the future.

**Comment by s-zanella** [comment] 2018-08-20 08:48
This is still reproducible.

**Comment by aseemr** [comment] 2018-08-20 09:10
Seems to be a duplicate of #606 (marking so that both can be tracked together).

**Closed** 2018-08-22 07:16 UTC
Labels: area/usability, kind/bug
