### ISSUE TITLE
Wrong SMT encoding for partially applied inductive types containing subtypes 

### ISSUE THREAD

**Issue by kyoDralliam** [FStarLang/FStar#692] opened 2016-09-24 13:41 UTC
I am having a (little) problem with the following code

````
type bidule0 (x:int) : int -> Type =
| Chose0 : y:int{y = 5} -> bidule0 x y


let truc0 () : Tot unit =
  let x = Mkdtuple2 #int #(bidule0 3) 5 (Chose0 5) in
  ()
````

which results in

````
unknown(0,0-0,0) (Warning): Unexpected output from Z3: (error "line 43704 column 27: Wrong number of arguments (1) passed to function (declare-fun BugTest.bidule0 (Term Term) Term)")

unknown(0,0-0,0) (Warning): Unexpected output from Z3: (error "line 43763 column 27: Wrong number of arguments (1) passed to function (declare-fun BugTest.bidule0 (Term Term) Term)")

unknown(0,0-0,0) (Warning): Unexpected output from Z3: (error "line 43822 column 27: Wrong number of arguments (1) passed to function (declare-fun BugTest.bidule0 (Term Term) Term)")

unknown(0,0-0,0) (Warning): Unexpected output from Z3: (error "line 43881 column 27: Wrong number of arguments (1) passed to function (declare-fun BugTest.bidule0 (Term Term) Term)")

unknown(0,0-0,0) (Warning): Unexpected output from Z3: (error "line 43940 column 27: Wrong number of arguments (1) passed to function (declare-fun BugTest.bidule0 (Term Term) Term)")

./bugTest.fst(6,38-11,4): Unknown assertion failed
Error: 1 errors were reported (see above)
````

A simple fix is to explicitly pass the second parameter of bidule0 (i.e. replacing #(bidule0 3) by #(fun y -> bidule0 3). The error disappear if I remove the {y = 5} in the definition of bidule or if the "let x =" is at the toplevel.

**Comment by nikswamy** [comment] 2016-09-25 08:48
Duplicate of #686. Closing.

It is unrelated to the use of the refinement subtype.

**Closed by nikswamy** 2016-09-25 08:48 UTC
Labels: bug, error-message
