### ISSUE TITLE
Some examples in the tutorial are not working

### ISSUE THREAD

**Issue by Eltges** [FStarLang/FStar#303] opened 2015-08-07 10:48 UTC
I stumbled accross some "answers" in the tutorial that crash or do not typecheck.
E.g. the answer to Exercise 11a which shows:
```
Unexpected error; please file a bug report, ideally with a minimized version of the source program that triggered the error.
ApplicationName='z3', CommandLine='-smt2 -in -t:20000 AUTO_CONFIG=false MODEL=true SMT.RELEVANCY=2', CurrentDirectory='', Native error= Cannot find the specified file
```

**Comment by nikswamy** [comment] 2015-08-10 18:13
@ad-l @markulf  ... any idea what's going on here?

**Comment by nikswamy** [comment] 2015-08-14 14:31
Could really use help from @ad-l on this. I don't have access to the server to reproduce this issue.

**Comment by catalin-hritcu** [comment] 2015-08-14 15:29
The server calls `fstar.exe` with additional parameters like `--fstar_home` and `--smt` (see `<fstar-priv>/website/run.php`), which is sometimes incompatible with using a `build-config` (issue #246). My guess is that this causes problems similar to what Markulf was reporting here: https://github.com/FStarLang/FStar/issues/246#issuecomment-119923546

**Comment by catalin-hritcu** [comment] 2015-08-14 15:34
Adding `--smt /var/fstar/bin/z3` to the options in the build-config in robots2 makes this work, but seems like a temporary workaround not a real fix. A real fix would be to sort out the mess in #246.

**Comment by markulf** [comment] 2015-08-16 13:00
We should include the tutorial in the regression.

**Comment by catalin-hritcu** [comment] 2015-08-16 18:09
The tutorial (including `robot2.fst`) is already part of the regression (`make test`). The problem is that on the server build-config does not interact well with the additional command line arguments the server needs ... and this is just an instance of #246.

**Comment by nikswamy** [comment] 2015-08-29 03:42
Where can I find the exact command line arguments being provided to F\* on the web server?

**Comment by catalin-hritcu** [comment] 2015-08-29 03:43
`<fstar-priv>/website/run.php` as already mentioned above (https://github.com/FStarLang/FStar/issues/303#issuecomment-131149675)

**Comment by nikswamy** [comment] 2015-08-29 04:42
Well, this issue of command line args + build config is fixed in master. 

It seems like the website is not pulling and deploying the latest files. At least it hasn't pulled my changes for the last couple of hours yet. 

How can we force the website to update to the HEAD revision on master?

**Comment by catalin-hritcu** [comment] 2015-08-29 04:50
> How can we force the website to update to the HEAD revision on master?

Only @ad-l can do that, I think

**Comment by catalin-hritcu** [comment] 2015-08-29 04:57
>> How can we force the website to update to the HEAD revision on master?

> Only @ad-l can do that, I think

Actually no, we can actually edit this at `<fstar-priv>/website/update_fstar.php`
But first we would need to understand what it does :)

**Comment by catalin-hritcu** [comment] 2015-08-29 05:06
For now I discovered that https://www.fstar-lang.org/UPDATE points to the latest update and currently it's this:
```
Last update: 28 Aug 2015 19:08
From git+ssh://scm.gforge.inria.fr//gitroot/fstar-priv/fstar-priv
 * branch            HEAD       -> FETCH_HEAD
Updating cf72215..50a7252
Fast-forward
 papers/dm4free/vmap_example.pdf | Bin 0 -> 67273 bytes
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 papers/dm4free/vmap_example.pdf
```
Not the newest, but not very old either. In particular it should have your fix for #246.

**Comment by catalin-hritcu** [comment] 2015-08-29 05:09
ah nevermind, this is about fstar-priv, so the source of the website itself ... I'm no longer sure if there ever was a smilar file for the github repo ... if somebody can code PHP we could add one :)

**Comment by nikswamy** [comment] 2015-08-29 05:13
I guess the web server is a Linux box. Can you confirm on Linux that running 'fstar --smt some/path/z3 robot2.fst' in exercises actually works? It does on windows.

Sent from my Windows Phone
________________________________

**Comment by nikswamy** [comment] 2015-08-29 05:15
Antoine, we could really use your help with this. Thanks! -Nik

Sent from my Windows Phone
________________________________

**Comment by catalin-hritcu** [comment] 2015-08-29 05:28
> I guess the web server is a Linux box. Can you confirm on Linux that running 'fstar --smt some/path/z3 robot2.fst' in exercises actually works? It does on windows.

It does indeed work now on Linux.

```
[hritcu@detained exercises]$ fstar.exe --smt ~/Apps/z3-4.4.0-x64-ubuntu-14.04/bin/z3 robot2.fst
Verifying module: FStar.FunctionalExtensionality
Verifying module: FStar.Heap
Verifying module: FStar.List.Tot
Verifying module: FStar.ST
Verifying module: FStar.All
Verifying module: FStar.Util
Verifying module: FStar.List
Verifying module: Robot
All verification conditions discharged successfully
[hritcu@detained exercises]$ fstar.exe --smt ~/Apps/z3-4.4.0-x64-ubuntu-14.04/bin/z3 --fstar_home ../../../.. robot2.fst
Verifying module: FStar.FunctionalExtensionality
Verifying module: FStar.Heap
Verifying module: FStar.List.Tot
Verifying module: FStar.ST
Verifying module: FStar.All
Verifying module: FStar.Util
Verifying module: FStar.List
Verifying module: Robot
All verification conditions discharged successfully

```

**Comment by catalin-hritcu** [comment] 2015-08-29 05:43
The webhook on github that notifies https://www.fstar-lang.org/update_fstar.php seems to work well and is triggered on each commit. But that's all I can say at this point, my change to the website to instrument when a github update happens was not yet itself yet taken into account.

**Comment by markulf** [comment] 2015-08-29 08:25
I did some PHP hacking on top of Antoine's code a while back, but I guess it caused its own set of problems and was overwritten by other peoples edits. Probably you Catalin? Sorry for the mess. 

But from that experience, did you try running  

```fstar.exe --smt ~/Apps/z3-4.4.0-x64-ubuntu-14.04/bin/z3 heap.fst set.fst set2.fst robot2.fst```

or whatever the top of `run.php` produces? But this code is deactivated when there is a build-config, so likely this is not the problem.

**Comment by markulf** [comment] 2015-08-29 08:55
I reinstalled the tutorials on a local virtual machine and get a number of errors, that seem unrelated to the issues here, though who knows. Will report them anyway. 

```Access to the path "/home/markulf/Source/fstar-priv/website/queries-bg-0.smt2" is denied```

`fstar` needs to be able to write into the local directory. After I fix that I get. 

```heap.fst(14,37-14,40) : Error Identifier not found: [set] (Possible clash with related name at set.fsi(20,0-23,3)) ```

Checking now that I have the latest consistent version of everything.

**Comment by markulf** [comment] 2015-08-29 09:10
Could it be that the pattern matching code at the top of `run.php` is the problem?

**Comment by markulf** [comment] 2015-08-29 10:28
Wrong track. The files actually differ in the build-config. For some reason the tutorial loads files in which the `--admit-fsi` do not yet have the `FStar` namespace.

**Comment by catalin-hritcu** [comment] 2015-08-29 14:49
> was overwritten by other peoples edits. Probably you Catalin?

No, not really. Run `git blame` if you want to see who edited what.

> did you try running
> fstar.exe --smt ~/Apps/z3-4.4.0-x64-ubuntu-14.04/bin/z3 heap.fst set.fst set2.fst robot2.fst
> or whatever the top of run.php produces

Tried two commands, but none of them gave me what Nik is seing:
```
[hritcu@detained exercises]$ fstar.exe --smt ~/Apps/z3-4.4.0-x64-ubuntu-14.04/bin/z3 ext.fst set.fsi heap.fst map.fsi listTot.fst hyperHeap.fsi stHyperHeap.fst allHyperHeap.fst util.fst list.fst --admit_fsi FStar.Set --admit_fsi FStar.Map --admit_fsi FStar.HyperHeap
Verifying module: FStar.FunctionalExtensionality
Verifying module: FStar.Heap
Verifying module: FStar.List.Tot
Verifying module: FStar.ST
Verifying module: FStar.All
Verifying module: FStar.Util
Verifying module: FStar.List
All verification conditions discharged successfully
[hritcu@detained exercises]$ fstar.exe --smt ~/Apps/z3-4.4.0-x64-ubuntu-14.04/bin/z3 ext.fst set.fsi heap.fst map.fsi listTot.fst hyperHeap.fsi stHyperHeap.fst allHyperHeap.fst util.fst list.fst                                                                    
heap.fst(14,37-14,40) : Error
Identifier not found: [set] (Possible clash with related name at set.fsi(18,76-20,23))
```

On the other hand, it seems the server still didn't take up my changes I made on `fstar-priv` last night.

**Comment by markulf** [comment] 2015-08-30 19:15
I still get a robot2 file in the tutorial without the `FStar` namespace in the `--admit-fsi`, resulting in your error above about `[set]` not found. 

This is independent from your problems of updating the server, and my `xhr.open` patch should fix it. How do you refresh your browser? How to do it in Edge? Guess restarting is an option.

**Comment by catalin-hritcu** [comment] 2015-09-04 06:58
This is fixed now.

**Closed by catalin-hritcu** 2015-09-04 06:58 UTC
Labels: bug, documentation, example
