### ISSUE TITLE
Compiling third party support

### ISSUE THREAD

**Issue by VincentCheval** [FStarLang/FStar#104] opened 2015-01-13 10:53 UTC
Hello,

I was trying to install the 3rd party tool that you have in src/support/ocaml/3rdparty. Following the file INSTALL, I've obtained the following error:

``````
E: Failure("Command ''/usr/local/bin/ocamlbuild' src_gen/nocrypto_bindgen.byte src/libnocrypto_stubs.a src/dllnocrypto_stubs.so src/nocrypto.cma src/nocrypto.cmxa src/nocrypto.a src/nocrypto.cmxs -tag debug' terminated with error code 10")
``````

I have the impression that these files are outdated due to lot of warning in the compilation.

Here is the full output from `make`:

``````
Removed /Users/vc218/.opam/system/lib/asn1-combinators
make -C ocaml-asn1-combinators
ocaml setup.ml -build 
File "setup.ml", line 247, characters 8-26:
Warning 3: deprecated: String.set
Use Bytes.set instead.
File "setup.ml", line 2502, characters 6-24:
Warning 3: deprecated: Lazy.lazy_from_fun
Use Lazy.from_fun instead.
Finished, 0 targets (0 cached) in 00:00:00.
Finished, 41 targets (40 cached) in 00:00:00.
make -C ocaml-asn1-combinators install
ocaml setup.ml -install 
File "setup.ml", line 247, characters 8-26:
Warning 3: deprecated: String.set
Use Bytes.set instead.
File "setup.ml", line 2502, characters 6-24:
Warning 3: deprecated: Lazy.lazy_from_fun
Use Lazy.from_fun instead.
W: Nothing to install for findlib library 'testlib'
Installed /Users/vc218/.opam/system/lib/asn1-combinators/asn.mli
Installed /Users/vc218/.opam/system/lib/asn1-combinators/asn1-combinators.cma
Installed /Users/vc218/.opam/system/lib/asn1-combinators/asn1-combinators.cmxa
Installed /Users/vc218/.opam/system/lib/asn1-combinators/asn1-combinators.a
Installed /Users/vc218/.opam/system/lib/asn1-combinators/asn1-combinators.cmxs
Installed /Users/vc218/.opam/system/lib/asn1-combinators/asn.cmi
Installed /Users/vc218/.opam/system/lib/asn1-combinators/asn_ber_der.cmx
Installed /Users/vc218/.opam/system/lib/asn1-combinators/asn_combinators.cmx
Installed /Users/vc218/.opam/system/lib/asn1-combinators/asn_random.cmx
Installed /Users/vc218/.opam/system/lib/asn1-combinators/asn_core.cmx
Installed /Users/vc218/.opam/system/lib/asn1-combinators/asn_prim.cmx
Installed /Users/vc218/.opam/system/lib/asn1-combinators/asn_writer.cmx
Installed /Users/vc218/.opam/system/lib/asn1-combinators/asn_cache.cmx
Installed /Users/vc218/.opam/system/lib/asn1-combinators/asn_time.cmx
Installed /Users/vc218/.opam/system/lib/asn1-combinators/asn_oid.cmx
Installed /Users/vc218/.opam/system/lib/asn1-combinators/asn.cmx
Installed /Users/vc218/.opam/system/lib/asn1-combinators/META
cd ocaml-nocrypto && ( ocamlfind remove nocrypto || true )
ocamlfind: [WARNING] No such directory: /Users/vc218/.opam/system/lib/nocrypto
make -C ocaml-nocrypto
ocaml setup.ml -build 
File "setup.ml", line 247, characters 8-26:
Warning 3: deprecated: String.set
Use Bytes.set instead.
File "setup.ml", line 2502, characters 6-24:
Warning 3: deprecated: Lazy.lazy_from_fun
Use Lazy.from_fun instead.
Finished, 0 targets (0 cached) in 00:00:00.
File "_tags", line 104, characters 25-32:
Warning: the tag "pkg_lwt" is not used in any flag declaration, so it will have no effect; it may be a typo. Otherwise use `mark_tag_used` in your myocamlbuild.ml to disable this warning.
File "_tags", line 105, characters 25-39:
Warning: the tag "pkg_lwt.syntax" is not used in any flag declaration, so it will have no effect; it may be a typo. Otherwise use `mark_tag_used` in your myocamlbuild.ml to disable this warning.
File "_tags", line 106, characters 25-37:
Warning: the tag "pkg_lwt.unix" is not used in any flag declaration, so it will have no effect; it may be a typo. Otherwise use `mark_tag_used` in your myocamlbuild.ml to disable this warning.
File "_tags", line 110, characters 18-25:
Warning: the tag "pkg_lwt" is not used in any flag declaration, so it will have no effect; it may be a typo. Otherwise use `mark_tag_used` in your myocamlbuild.ml to disable this warning.
File "_tags", line 111, characters 18-32:
Warning: the tag "pkg_lwt.syntax" is not used in any flag declaration, so it will have no effect; it may be a typo. Otherwise use `mark_tag_used` in your myocamlbuild.ml to disable this warning.
File "_tags", line 112, characters 18-30:
Warning: the tag "pkg_lwt.unix" is not used in any flag declaration, so it will have no effect; it may be a typo. Otherwise use `mark_tag_used` in your myocamlbuild.ml to disable this warning.
+ /Users/vc218/.opam/system/bin/ocamlfind ocamlc -g -linkpkg -package ctypes.stubs src_gen/bindings.cmo src_gen/nocrypto_bindgen.cmo -o src_gen/nocrypto_bindgen.byte
File "_none_", line 1:
Error: Error on dynamically loaded library: dllctypes_stubs.so: dlopen(dllctypes_stubs.so, 138): image not found
Command exited with code 2.
Compilation unsuccessful after building 5 targets (4 cached) in 00:00:00.
E: Failure("Command ''/usr/local/bin/ocamlbuild' src_gen/nocrypto_bindgen.byte src/libnocrypto_stubs.a src/dllnocrypto_stubs.so src/nocrypto.cma src/nocrypto.cmxa src/nocrypto.a src/nocrypto.cmxs -tag debug' terminated with error code 10")
make[1]: *** [build] Error 1
make: *** [ocaml-nocrypto] Error 2
``````

Many thanks

Vincent

**Comment by catalin-hritcu** [comment] 2015-01-27 14:47
This works for me, attached output:
```
[hritcu@detained 3rdparty]$ make
cd ocaml-asn1-combinators && ( ocamlfind remove asn1-combinators || true )
Removed /home/hritcu/.opam/4.02.1/lib/asn1-combinators
make -C ocaml-asn1-combinators
make[1]: Entering directory '/home/hritcu/Projects/fstar/pub/src/support/ocaml/3rdparty/ocaml-asn1-combinators'
ocaml setup.ml -build 
File "setup.ml", line 247, characters 8-26:
Warning 3: deprecated: String.set
Use Bytes.set instead.
File "setup.ml", line 2502, characters 6-24:
Warning 3: deprecated: Lazy.lazy_from_fun
Use Lazy.from_fun instead.
Finished, 0 targets (0 cached) in 00:00:00.
Finished, 41 targets (40 cached) in 00:00:00.
make[1]: Leaving directory '/home/hritcu/Projects/fstar/pub/src/support/ocaml/3rdparty/ocaml-asn1-combinators'
make -C ocaml-asn1-combinators install
make[1]: Entering directory '/home/hritcu/Projects/fstar/pub/src/support/ocaml/3rdparty/ocaml-asn1-combinators'
ocaml setup.ml -install 
File "setup.ml", line 247, characters 8-26:
Warning 3: deprecated: String.set
Use Bytes.set instead.
File "setup.ml", line 2502, characters 6-24:
Warning 3: deprecated: Lazy.lazy_from_fun
Use Lazy.from_fun instead.
W: Nothing to install for findlib library 'testlib'
Installed /home/hritcu/.opam/4.02.1/lib/asn1-combinators/asn.mli
Installed /home/hritcu/.opam/4.02.1/lib/asn1-combinators/asn1-combinators.cma
Installed /home/hritcu/.opam/4.02.1/lib/asn1-combinators/asn1-combinators.cmxa
Installed /home/hritcu/.opam/4.02.1/lib/asn1-combinators/asn1-combinators.a
Installed /home/hritcu/.opam/4.02.1/lib/asn1-combinators/asn1-combinators.cmxs
Installed /home/hritcu/.opam/4.02.1/lib/asn1-combinators/asn.cmi
Installed /home/hritcu/.opam/4.02.1/lib/asn1-combinators/asn_ber_der.cmx
Installed /home/hritcu/.opam/4.02.1/lib/asn1-combinators/asn_combinators.cmx
Installed /home/hritcu/.opam/4.02.1/lib/asn1-combinators/asn_random.cmx
Installed /home/hritcu/.opam/4.02.1/lib/asn1-combinators/asn_core.cmx
Installed /home/hritcu/.opam/4.02.1/lib/asn1-combinators/asn_prim.cmx
Installed /home/hritcu/.opam/4.02.1/lib/asn1-combinators/asn_writer.cmx
Installed /home/hritcu/.opam/4.02.1/lib/asn1-combinators/asn_cache.cmx
Installed /home/hritcu/.opam/4.02.1/lib/asn1-combinators/asn_time.cmx
Installed /home/hritcu/.opam/4.02.1/lib/asn1-combinators/asn_oid.cmx
Installed /home/hritcu/.opam/4.02.1/lib/asn1-combinators/asn.cmx
Installed /home/hritcu/.opam/4.02.1/lib/asn1-combinators/META
make[1]: Leaving directory '/home/hritcu/Projects/fstar/pub/src/support/ocaml/3rdparty/ocaml-asn1-combinators'
cd ocaml-nocrypto && ( ocamlfind remove nocrypto || true )
Removed /home/hritcu/.opam/4.02.1/lib/stublibs/dllnocrypto_stubs.so
Removed /home/hritcu/.opam/4.02.1/lib/stublibs/dllnocrypto_stubs.so.owner
Removed /home/hritcu/.opam/4.02.1/lib/nocrypto
make -C ocaml-nocrypto
make[1]: Entering directory '/home/hritcu/Projects/fstar/pub/src/support/ocaml/3rdparty/ocaml-nocrypto'
ocaml setup.ml -build 
File "setup.ml", line 247, characters 8-26:
Warning 3: deprecated: String.set
Use Bytes.set instead.
File "setup.ml", line 2502, characters 6-24:
Warning 3: deprecated: Lazy.lazy_from_fun
Use Lazy.from_fun instead.
Finished, 0 targets (0 cached) in 00:00:00.
Finished, 93 targets (92 cached) in 00:00:00.
make[1]: Leaving directory '/home/hritcu/Projects/fstar/pub/src/support/ocaml/3rdparty/ocaml-nocrypto'
make -C ocaml-nocrypto install
make[1]: Entering directory '/home/hritcu/Projects/fstar/pub/src/support/ocaml/3rdparty/ocaml-nocrypto'
ocaml setup.ml -install 
File "setup.ml", line 247, characters 8-26:
Warning 3: deprecated: String.set
Use Bytes.set instead.
File "setup.ml", line 2502, characters 6-24:
Warning 3: deprecated: Lazy.lazy_from_fun
Use Lazy.from_fun instead.
W: Nothing to install for findlib library 'testlib'
Installed /home/hritcu/.opam/4.02.1/lib/nocrypto/uncommon.ml
Installed /home/hritcu/.opam/4.02.1/lib/nocrypto/base64.mli
Installed /home/hritcu/.opam/4.02.1/lib/nocrypto/hash.mli
Installed /home/hritcu/.opam/4.02.1/lib/nocrypto/cipher_stream.mli
Installed /home/hritcu/.opam/4.02.1/lib/nocrypto/cipher_block.mli
Installed /home/hritcu/.opam/4.02.1/lib/nocrypto/numeric.mli
Installed /home/hritcu/.opam/4.02.1/lib/nocrypto/fortuna.mli
Installed /home/hritcu/.opam/4.02.1/lib/nocrypto/rng.mli
Installed /home/hritcu/.opam/4.02.1/lib/nocrypto/rsa.mli
Installed /home/hritcu/.opam/4.02.1/lib/nocrypto/dh.mli
Installed /home/hritcu/.opam/4.02.1/lib/nocrypto/libnocrypto_stubs.a
Installed /home/hritcu/.opam/4.02.1/lib/nocrypto/nocrypto.cmi
Installed /home/hritcu/.opam/4.02.1/lib/nocrypto/nocrypto.cma
Installed /home/hritcu/.opam/4.02.1/lib/nocrypto/nocrypto.cmxa
Installed /home/hritcu/.opam/4.02.1/lib/nocrypto/nocrypto.a
Installed /home/hritcu/.opam/4.02.1/lib/nocrypto/nocrypto.cmxs
Installed /home/hritcu/.opam/4.02.1/lib/nocrypto/META
Installed /home/hritcu/.opam/4.02.1/lib/stublibs/dllnocrypto_stubs.so
Installed /home/hritcu/.opam/4.02.1/lib/stublibs/dllnocrypto_stubs.so.owner
ocamlfind: [WARNING] You have installed DLLs but the directory /home/hritcu/.opam/4.02.1/lib/stublibs is not mentioned in ld.conf
make[1]: Leaving directory '/home/hritcu/Projects/fstar/pub/src/support/ocaml/3rdparty/ocaml-nocrypto'
cd ocaml-x509 && ( ocamlfind remove x509 || true )
Removed /home/hritcu/.opam/4.02.1/lib/x509
make -C ocaml-x509
make[1]: Entering directory '/home/hritcu/Projects/fstar/pub/src/support/ocaml/3rdparty/ocaml-x509'
ocaml setup.ml -build 
File "setup.ml", line 247, characters 8-26:
Warning 3: deprecated: String.set
Use Bytes.set instead.
File "setup.ml", line 2502, characters 6-24:
Warning 3: deprecated: Lazy.lazy_from_fun
Use Lazy.from_fun instead.
Finished, 0 targets (0 cached) in 00:00:00.
Finished, 22 targets (21 cached) in 00:00:00.
make[1]: Leaving directory '/home/hritcu/Projects/fstar/pub/src/support/ocaml/3rdparty/ocaml-x509'
make -C ocaml-x509 install
make[1]: Entering directory '/home/hritcu/Projects/fstar/pub/src/support/ocaml/3rdparty/ocaml-x509'
ocaml setup.ml -install 
File "setup.ml", line 247, characters 8-26:
Warning 3: deprecated: String.set
Use Bytes.set instead.
File "setup.ml", line 2502, characters 6-24:
Warning 3: deprecated: Lazy.lazy_from_fun
Use Lazy.from_fun instead.
Installed /home/hritcu/.opam/4.02.1/lib/x509/asn_grammars.ml
Installed /home/hritcu/.opam/4.02.1/lib/x509/certificate.mli
Installed /home/hritcu/.opam/4.02.1/lib/x509/x509.mli
Installed /home/hritcu/.opam/4.02.1/lib/x509/x509.cma
Installed /home/hritcu/.opam/4.02.1/lib/x509/x509.cmxa
Installed /home/hritcu/.opam/4.02.1/lib/x509/x509.a
Installed /home/hritcu/.opam/4.02.1/lib/x509/x509.cmxs
Installed /home/hritcu/.opam/4.02.1/lib/x509/x509.cmi
Installed /home/hritcu/.opam/4.02.1/lib/x509/certificate.cmi
Installed /home/hritcu/.opam/4.02.1/lib/x509/asn_grammars.cmi
Installed /home/hritcu/.opam/4.02.1/lib/x509/registry.cmx
Installed /home/hritcu/.opam/4.02.1/lib/x509/x509_common.cmx
Installed /home/hritcu/.opam/4.02.1/lib/x509/x509.cmx
Installed /home/hritcu/.opam/4.02.1/lib/x509/certificate.cmx
Installed /home/hritcu/.opam/4.02.1/lib/x509/asn_grammars.cmx
Installed /home/hritcu/.opam/4.02.1/lib/x509/META
W: Nothing to install for findlib library 'tests'
make[1]: Leaving directory '/home/hritcu/Projects/fstar/pub/src/support/ocaml/3rdparty/ocaml-x509'
```

**Comment by catalin-hritcu** [comment] 2015-02-17 13:22
Any news on this? Can anyone reproduce Vincent's problem? Vincent, you still have the problem, right?

**Comment by catalin-hritcu** [comment] 2015-03-27 21:07
This looks like obsolete stuff. Closing.

**Closed by catalin-hritcu** 2015-03-27 21:07 UTC
Labels: needinput
