### ISSUE TITLE
SMTPat generates unexpected output from Z3.

### ISSUE THREAD

**Issue by VincentCheval** [FStarLang/FStar#2140] opened 2020-09-15 08:20 UTC
Hello,

I obtain the following error from Z3 when I use a SMTPat in one of my functions. I found another issue #1796 still open where they obtain the same error message but I don't know if the situation is exactly the same.

```
Sem.Term2.fst(37,0-38,120): (Error 276) Unexpected output from Z3: (error "line 148910 column 50: Wrong number of arguments (1) passed to function (declare-fun Sem.Term2.occurs.fuel_instrumented (Fuel Term Term) Term)")
```

I tried to make the example as minimal as possible:

```
module Sem.Term2

(****** Interface *******)

type funsymbol = int

type variable =
  {
    v_name: string
  }

type name = int

type term =
  | Var : v:variable -> term
  | Name : n:name -> term
  | Func : s:funsymbol -> l:list term -> term

(** Occurrence function **)

val occurs: variable -> term -> bool
val occurs_list: variable -> list term -> bool
let rec occurs x t= match t with
  | Var v -> v = x
  | Name _ -> false
  | Func _ args -> occurs_list x args
and occurs_list x l = match l with
  | [] -> false
  | t::q -> occurs x t || occurs_list x q

assume val spec_occurs_list_exists: x:variable -> l:list term -> Lemma
  (ensures (occurs_list x l <==> FStar.List.Tot.existsb (occurs x) l))
  [SMTPat (occurs_list x l)]

assume val get_vars_list: l:list term -> list variable -> list variable

val spec_get_vars_list: l:list term -> acc:list variable -> Lemma
  (forall (x:variable). (FStar.List.Tot.mem x (get_vars_list l acc) <==> (FStar.List.Tot.mem x acc \/ occurs_list x l)))
```

Note that if you change the type `variable` to `type variable = int` then it works. Don"t know if that can help you debug.

Best,
Vincent

**Comment by aseemr** [comment] 2020-09-15 11:16
Thanks @VincentCheval for the report!

The issue is same as #1575 which is still a problem. I have added the example there, with some explanation for the behavior. Closing this one.

**Closed by aseemr** 2020-09-15 11:16 UTC
