### ISSUE TITLE
Bug or NYI?

### ISSUE THREAD

**Issue by wintersteiger** [FStarLang/FStar#1101] opened 2017-06-28 20:30 UTC
This is what I get using the latest master of F* on one of the hacl-star files ([Hacl.Spec.Bignum.Fsquare.fst.txt](https://github.com/FStarLang/FStar/files/1110128/Hacl.Spec.Bignum.Fsquare.fst.txt))

```
> /mnt/f/dev/sec/FStar/bin/fstar.ocaml  Hacl.Spec.Bignum.Fsquare.fst  --trace_error

Warning: in Hacl.Spec.Bignum.Fsquare.fst: no modules in namespace Hacl.Bignum.Limb and no file with that name either
Warning: no modules in namespace Hacl.Bignum.Limb and no file with that name either
Warning: in Hacl.Spec.Bignum.Fsquare.fst: no modules in namespace Hacl.Spec.Bignum.Bigint and no file with that name either
Warning: no modules in namespace Hacl.Spec.Bignum.Bigint and no file with that name either
Warning: in Hacl.Spec.Bignum.Fsquare.fst: no modules in namespace Hacl.Spec.Bignum.Fproduct and no file with that name either
Warning: no modules in namespace Hacl.Spec.Bignum.Fproduct and no file with that name either
Unexpected error
Failure("Not yet implemented:raise")
Raised at file "pervasives.ml", line 32, characters 17-33
Called from file "src/ocaml-output/FStar_Pervasives.ml" (inlined), line 162, characters 30-68
Called from file "src/ocaml-output/FStar_Parser_Dep.ml", line 467, characters 10-119
Called from file "src/ocaml-output/FStar_Parser_Dep.ml", line 511, characters 16-49
Called from file "src/ocaml-output/FStar_Parser_Dep.ml", line 1006, characters 1-23
Called from file "list.ml", line 77, characters 12-15
Called from file "src/ocaml-output/FStar_Parser_Dep.ml", line 745, characters 62-97
Called from file "list.ml", line 77, characters 12-15
Called from file "src/ocaml-output/FStar_Parser_Dep.ml", line 1165, characters 1-19
Called from file "src/ocaml-output/FStar_Parser_Dep.ml" (inlined), line 1259, characters 19-57
Called from file "src/ocaml-output/FStar_Parser_Dep.ml", line 1293, characters 56-114
Called from file "list.ml", line 77, characters 12-15
Called from file "src/ocaml-output/FStar_Parser_Dep.ml", line 1325, characters 4-62
Called from file "src/ocaml-output/FStar_Dependencies.ml", line 15, characters 15-59
Called from file "src/ocaml-output/FStar_Main.ml", line 339, characters 17-79
Called from file "src/ocaml-output/FStar_Main.ml", line 377, characters 1-8
```

Am I exercising something that's indeed not implemented? I stripped a bunch of related stuff to get a small repro, but I get the same error on the full file with includes etc.

**Comment by msprotz** [comment] 2017-06-28 20:35
From `FStar.Pervasives.fst`: 

```
144 assume val raise: exn -> Ex 'a       (* TODO: refine with the Exn monad *)
```

but I thought we had changed the extraction mechanism to replace calls to raise with the actual raise keyword from OCaml? Or perhaps to just not extract it?

instead, in src/ocaml-output/FStar_Pervasives.ml, we have:
```
  43 let raise uu____661 = failwith "Not yet implemented:raise"
```
which shouldn't be there... @aseemr I seem to remember you worked on that recently?

**Comment by msprotz** [comment] 2017-06-28 20:36
But in any case, the root cause of your error is that you probably don't have enough directories on your `--include` path... probably in the same bucket as #718

**Comment by wintersteiger** [comment] 2017-06-28 22:14
More than likely! I removed them to get a simpler example, so it may well be a different error than the one I get with all the includes added (but it was an NYI too).

**Comment by wintersteiger** [comment] 2017-06-28 22:17
Oh wait. It's possible that I extracted a new set of ml files using an old ml version without bootstrapping from F#, that would explain why it doesn't use the raise keyword if that change was made recently.

**Comment by aseemr** [comment] 2017-06-29 05:25
@protz, during extraction, the uses of `FStar.Pervasives.raise` are extracted as primitive OCaml `raise`. haven't looked into this issue in detail yet.

**Comment by msprotz** [comment] 2017-06-29 06:29
Ok. It's just, I think, that `raise` is resolving into `Pervasives.raise` because of scoping, so it doesn't change much to replace `FStar.Pervasives.raise` with `raise`, since `FStar.Pervasives` is always open, right?

**Comment by nikswamy** [comment] 2017-10-14 18:21
Is this still open? Seem to remember this was a transient problem that was fixed at some point. 

@victor-dumitrescu : this is close to your territory ... can you investigate please? Thanks!

**Comment by aseemr** [comment] 2018-08-08 08:27
@victor-dumitrescu, could you please see if this is already fixed? Thanks!

**Closed** 2019-10-21 16:36 UTC
Labels: component/extraction, kind/crash, status/needs-confirmation
