### ISSUE TITLE
Ticked variables preventing unification

### ISSUE THREAD

**Issue by gabriel-fallen** [FStarLang/FStar#1292] opened 2017-10-10 13:31 UTC
In an example like this:
```
module Example

val o : ('a -> Tot int) -> ('a -> Tot int) -> 'a -> Tot int
let o f g = fun x -> f x + g x

val foldr : ('a -> 'b -> Tot 'b) -> 'b -> list 'a -> Tot 'b
let rec foldr f x l = match l with
  | [] -> x
  | h::t -> f h (foldr f x t)

val foo : list ('a -> Tot int) -> 'a -> Tot int
let foo = foldr (fun f g -> f `o` g) (fun x -> 0)
```
I get an error
```
Example(12,10-12,49): (Error) Failed to resolve implicit argument of type 'Type' introduced in (*?u9*) _ (see also Example(12,28-12,35))
Example(12,10-12,49): (Error) Expected type "uu___159033:Prims.list (uu___159035:'a -> Prims.Tot Prims.int) -> uu___159034:'a -> Prims.Tot Prims.int"; but "Example.foldr (fun f g -> Example.o f g) (fun x -> 0)" has type "l:Prims.list (uu___159041:(*?u9*) _ -> Prims.Tot Prims.int) -> Prims.Tot (uu___159040:(*?u9*) _ -> Prims.Tot Prims.int)"
2 errors were reported (see above)
```
I didn't figured out the first error yet, but the second is clearly mismatch between `'a -> Tot int` and `Tot ('a -> Tot int)`.

Is it inherent difference between curried and "constructed" functions due to effect system or there's some workaround? Coming from Haskell it's a bit strange considering all the functions involved are pure (and even total).

PS. Custom `foldr` is there instead of `fold_right` due to different positions of initial argument and list argument.

**Comment by mtzguido** [comment] 2017-10-10 16:20
There shouldn't be a difference between those two, but I think that's not the error you're seeing. It seems to have something to do with "tick" variables, since the two types you see are:
`uu___159033:Prims.list (uu___159035:'a -> Prims.Tot Prims.int) -> uu___159034:'a -> Prims.Tot Prims.int`
and
`l:Prims.list (uu___159041:(*?u9*) _ -> Prims.Tot Prims.int) -> Prims.Tot (uu___159040:(*?u9*) _ -> Prims.Tot Prims.int)`

Note that the type of the list elements are `'a -> Tot int` and `?u9 _ -> Tot int`, but `?u9 _` cannot depend on `a` since uvars are closed, and this cannot unify. (Unsure what's up with that `_` there too).

As workarounds, you can either use regular implicit variables
```
val foo : (#a:Type) -> list (a -> Tot int) -> a -> Tot int
let foo #a = foldr (fun f g -> f `o` g) (fun x -> 0)
```
Or just drop the `val`.
```
let foo' = foldr (fun f g -> f `o` g) (fun x -> 0)
```

**Comment by gabriel-fallen** [comment] 2017-10-10 16:32
Indeed! Both options are fixing the problem even in more advanced (original) case.
@mtzguido thanks a lot!

Should I close this issue or you are going to investigate why "tick" variables do not unify?

**Comment by mtzguido** [comment] 2017-10-10 16:33
Don't close it! This is indeed a bug. Although I'm not going to try to squash it anytime soon :)

**Comment by gabriel-fallen** [comment] 2017-10-10 17:13
OK. No problem. :)

And thanks again!

**Comment by cpitclaudel** [comment] 2017-10-10 17:18
>  (Unsure what's up with that _ there too).
We don't have surface syntax for unification variable, so they are printed as `_`; the (* ?u9 *) part is a comment that makes it possible to see when multiple of the `_` came from the same unification variable.

**Comment by mtzguido** [comment] 2017-10-10 17:20
Ah, I see, thanks. Then this uvar was created on an empty environment, since it's not applied to anything.

**Comment by gabriel-fallen** [comment] 2017-10-10 17:46
Probably here is not the right place to ask, I'm sorry for that.
Now I have this code
```
module Example

open FStar.List.Tot

type tree 'a =
  | Leaf: 'a -> tree 'a
  | Node : list (tree 'a) -> tree 'a

val foldt : #a:Type -> #b:Type -> (a -> b) -> (list b -> b) -> tree a -> b
let rec foldt #a #b f g tr = match tr with
  | Leaf x  -> f x
  | Node ts -> g (map (foldt #a #b f g) ts)
```
and it fails with
```
Example(12,22-12,39): (Error) Subtyping check failed; expected type uu___343621:Example.tree a -> Prims.Tot b; got type uu___343618:(uu___343619:Example.tree a{ uu___343619 << tr }) -> Prims.Tot b (see also Example(10,0-12,43))
Verified module: Example (844 milliseconds)
1 error was reported (see above)
```

That's due to termination argument and covariance I guess?

**Comment by mtzguido** [comment] 2017-10-10 17:57
Yes, terminiation is non-trivial in that case.

This should provide some info: https://lists.gforge.inria.fr/pipermail/fstar-club/2017/000078.html

**Comment by mtzguido** [comment] 2018-08-21 17:25
The original problem seems gone, but we now get
```
Example.fst(12,10-12,49): (Error 120) Expected a term with 1 implicit arguments, but Example.foldr (fun f g -> Example.o f g) (fun _ -> 0) has only 0
```
which can be fixed by eta-expanding `foo` or by adding a `#_` argument to it.

**Comment by mtzguido** [comment] 2020-04-16 04:03
On a second look, this new error is correct expected behaviour. Closing.

**Closed by mtzguido** 2020-04-16 04:03 UTC
Labels: component/inference, component/typechecker, component/unifier, kind/enhancement
