### ISSUE TITLE
F* can't re type-check the WPs it produces itself: Interface violates its abstraction + Too many arguments to function

### ISSUE THREAD

**Issue by catalin-hritcu** [FStarLang/FStar#1123] opened 2017-07-12 12:13 UTC
Please note that the following module has no abstract functions:
```
module Blah

open Preorder
open Heapx
open STx
open MRefx

val evolve : x:int -> Tot (preorder int)
let evolve x = trivial_preorder int

(* fails *)
let write (r:mref int (evolve 1)) = r := 42

(* fails *)
let write2 (r:mref int (evolve 2)) = STx.op_Colon_Equals r 42

(* fails *)
let write3 (r:mref int (evolve 3)) = STx.write r 42
```
Yet all the three variants of `write` typecheck at first but then fail with an `Interface of Blah violates its abstraction (add a 'private' qualifier to 'write'?): Too many arguments to function` error:
```
$ fstar.exe Blah.fst       (git)-[master]
./Blah.fst(12,38-12,40): (Error) Interface of Blah violates its abstraction (add a 'private' qualifier to 'write'?): Too many arguments to function of type x:Prims.int -> Prims.Tot (Preorder.preorder Prims.int); got 3 arguments (see also ./STx.fst(95,25-95,34))
1 error was reported (see above)
```

**Comment by kyoDralliam** [comment] 2017-07-12 12:15
@nikswamy would it be possible that the inferred wp leaks the definition of `STx.write` which is supposed to be abstract (in its own module) ?

**Comment by catalin-hritcu** [comment] 2017-07-12 14:49
The spec inferred by F* (as printed by `--log_types --print_effect_args`):
```
val write : r:(STx.mref Prims.int (evolve 1)) -> STx.ST Prims.unit
  (fun h -> evolve 1 (Heapx.sel h r) 42)
  (fun h0 x h1 ->
      evolve 1 (Heapx.sel h0 r) 42 /\ Heapx.contains h0 r /\ h1 == Heapx.upd h0 r 42)
```
Is not accepted by F* as well-typed (following error pointing at `evolve 1 (Heapx.sel h r) 42`):
```
Too many arguments to function of type x:Prims.int -> Prims.Tot (Preorder.preorder Prims.int)
```
although it is actually well typed. Seems similar to previous issues with refined function types: #1060 but also some others before it (which I can no longer find).

Also, very unclear what this has to do with abstraction.

**Comment by catalin-hritcu** [comment] 2017-07-12 14:51
The following also fails:
```
val evolve : x:int -> Tot (preorder int)
let evolve x = trivial_preorder int

let y = evolve 1 2 3
```
with the same error message:
```
Too many arguments to function of type x:Prims.int -> Prims.Tot (Preorder.preorder Prims.int); got 3 arguments
```

**Comment by nikswamy** [comment] 2017-07-12 14:56
Thanks for the detective work. 

The error message about abstraction violation is indeed misleading. What's happening is that we re-typecheck the interface of a module M to make sure that its external-facing terms remain well-typed from the perspective of another module that can't view M's abstractions. 

If this re-typechecking fails, we report that "abstraction violation" message.

In this case, some other bug (as your last comment shows) causes re-typechecking to fail.

Maybe, in this case, the error message should be a bit more operational: something like "failed to type-check the symbols exported by this module. It may be that the module exports a symbol whose well-typedness relies on an abstraction enforced by the module".

**Comment by aseemr** [comment] 2017-07-28 14:09
I ran into this issue too, the workaround was to add a spec to the `write` functions in the above examples.

**Comment by catalin-hritcu** [comment] 2017-10-08 10:56
This bug is still present and still affects one of our school's examples of WP inference. Also the `Interface of ... violates its abstraction` part of the error message is still misleading.

**Comment by nikswamy** [comment] 2017-10-14 17:52
This is also related to #1307

**Comment by aseemr** [comment] 2017-12-01 14:35
A small repro:

```
module Test

assume val bar (x:int) :Dv unit

let foo (x:int) = bar x; Some #unit ()
```
The issue is that, in the `wp` of `foo`, `Some` is applied to two arguments, `unit` and `()`, except that the information that `unit` is instantiation of an implicit argument is lost. In other words, the argument qualifier on `unit` is `None`.

A couple of things more:

1. The problem seems related to lifts. In the minimal example above, `Some ()` is lifted to `Dv`. In other examples also, I have seen some lift happening.

2. Removing the `#unit` argument makes the example go through.

**Comment by aseemr** [comment] 2017-12-01 16:43
The issue about abstraction error is fixed in my commit above. One of Catalin's example is a different issue, see #1352.

**Closed by aseemr** 2017-12-01 16:43 UTC
Labels: area/error-messages, component/two-phase-tc, component/typechecker, kind/bug
