### ISSUE TITLE
If-then-else in decreases clauses blows up: Expect match nodes to be annotated already

### ISSUE THREAD

**Issue by catalin-hritcu** [FStarLang/FStar#128] opened 2015-02-17 17:18 UTC
[This part is already fixed, please look at the end for the remaining problem here]
Commenting this out in `stlc_strong_db_parsubst.fst`
```
val subst_eabs : s:sub -> Tot sub (*decreases (is_renaming s)*)
```
causes F* to blow up:
```
../../bin/fstar.exe --fstar_home ../.. stlc_strong_db_parsubst.fst 
Error stlc_strong_db_parsubst.fst(59,0-62,3): The following problems were found:
	Patterns are incomplete (stlc_strong_db_parsubst.fst(59,20-59,67))
Error stlc_strong_db_parsubst.fst(70,0-82,3): The following problems were found:
	Subtyping check failed; expected type _13771:sub{(%[(is_renaming _13771)] << %[(is_renaming s); e])}; got type sub (stlc_strong_db_parsubst.fst(73,46-73,47))

Unexpected error; please file a bug report, ideally with a minimized version of the source program that triggered the error.
The lists had different lengths.
Parameter name: xs2
```

**Comment by catalin-hritcu** [comment] 2015-02-17 18:16
There are a couple more blow-ups in there 
``` 
   (decreases (if is_EVar e then LexTop else %[is_renaming s; e]))
```
and
```
val subst_eabs : s:sub -> Tot (sub(*{renaming s ==> renaming s'}*))
```

**Comment by nikswamy** [comment] 2015-04-28 17:16
Could this be a duplicate with #123 
I can't reproduce it based on the instructions above ... stlc_strong_db_parsubst.fst has changed substantially

**Comment by catalin-hritcu** [comment] 2015-04-29 06:59
The other ones seem fixed, but I can still reproduce one of these. Changing line 71 in `stlc_strong_db_parsubst.fst` as follows:
```
val subst : s:sub -> e:exp -> Pure exp (requires True)
     (ensures (fun e' -> (renaming s /\ is_EVar e) ==> is_EVar e'))
(*     (decreases %[is_var e; is_renaming s; e])*)
     (decreases (if is_EVar e then LexTop else %[is_renaming s; e]))
```
causes
```
Unexpected error; please file a bug report, ideally with a minimized version of the source program that triggered the error.
Expect match nodes to be annotated already
```
I could minimize this to just:
```
val subst : x:int -> Tot unit (decreases (if x = 42 then LexTop else LexTop))
let rec subst x = ()
```

**Comment by s-zanella** [comment] 2016-06-30 16:45
This verifies with `--universes`.
```
val subst : x:int -> Tot unit (decreases (if x = 42 then LexTop else LexTop))
let rec subst x = ()
```
Closing the issue.

**Closed by s-zanella** 2016-06-30 16:45 UTC
Labels: bug
