### ISSUE TITLE
Subtyping check fails due to projectee

### ISSUE THREAD

**Issue by jaylorch** [FStarLang/FStar#2460] opened 2022-02-16 20:29 UTC
The following code gives a subtyping check failure:

```
module Test9

open FStar.List.Tot

#push-options "--print_implicits --print_effect_args"

let rec for_all_range (n: nat) (f: (i: nat{i < n}) -> bool) =
  if n = 0 then
    true
  else (
    f (n - 1) && for_all_range (n - 1) f
  )

noeq type test_t = {
  s: list nat;
  lem: squash (for_all_range (length s) (fun (i: nat{i < length s}) -> true));
}
```

The reported error is:
```
test9.fst(16,2-16,5): (Error 19) Subtyping check failed; expected type Prims.squash (Prims.b2t (Test9.for_all_range (FStar.List.Tot.Base.length #Prims.nat
              (Mktest_t?.s projectee))
          (fun _ -> true))); got type Prims.squash (Prims.b2t (Test9.for_all_range (FStar.List.Tot.Base.length #Prims.nat s)
          (fun _ -> true))); The SMT solver could not prove the query, try to spell your proof in more detail or increase fuel/ifuel (see also test9.fst(16,14-16,77))
Verified module: Test9
1 error was reported (see above)
```

**Comment by nikswamy** [comment] 2022-02-16 21:52
Duplicate of #1355 

Short version, you can work around it with 

```
#push-options "--__temp_no_proj Test9" //use YourModuleName instead of Test9 
noeq type test_t = {
  s: list nat;
  lem: squash (for_all_range (length s) (fun (i: nat{i < length s}) -> true));
}
#pop-options
```

We have been dragging our feet on fixing this using a tactic, discussed more in #1355

**Closed by nikswamy** 2022-02-16 21:52 UTC
