### ISSUE TITLE
Unification failures / crashes in tactics

### ISSUE THREAD

**Issue by nikswamy** [FStarLang/FStar#1256] opened 2017-09-21 17:18 UTC
Here are two simple programs that fail. 

1.  This one fails at the last line with a

`Failed to resolve implicit argument of type '(WP.aug p#1710867)' introduced in (?2512 p#1710867)`

```
let my_cut (t:tactic term) : tactic unit =
    qq <-- quote_lid ["FStar";"Tactics";"Derived";"__cut"];
    t <-- t ;
    let tt = pack (Tv_App qq (t, Q_Explicit)) in
    apply (return tt)

assume val aug : (unit -> Type0) -> Type0
let test (p:(unit -> Type0)) (q:(unit -> Type0))
   = assert_by_tactic
            (p == q ==>
             aug p ==>
             aug q)
             ( eq <-- implies_intro ;
               h <-- implies_intro ;
               dump "A" ;;
               my_cut (return (type_of_binder h)) ;;
               dump "B" ;;
               rewrite eq;;
               norm [] ;;
               dump "C" ;;
               hh <-- intro ;
               apply (quote return_squash) ;;
               dump "D" ;;               
               exact (return (pack (Tv_Var h))))
```

2. This variant is worse. It crashes at the last intro with 

```
[F* warning] Normalization failed with error Failure("Incompatible version for unification variable: current version is 1977.2634; got version 1977.2635")
[F* error] Unexpected error; please file a bug report, ideally with a minimized version of the source program that triggered the error.
[F* error] Failure("Incompatible version for unification variable: current version is 1977.2634; got version 1977.2635")
```

```
assume val aug : (unit -> Type0) -> Type0
let test (post:(unit -> Type0))
   = assert_by_tactic
            ((post ==  (fun x -> post ())) ==>
             aug post ==>
             aug (fun x -> post ()))
             ( eq <-- implies_intro ;
               h <-- implies_intro ;
               dump "A" ;;
               my_cut (return (type_of_binder h)) ;;
               dump "B" ;;
               rewrite eq;;
               norm [] ;;
               dump "C" ;;
               hh <-- intro ;
               fail "HERE")
```

Will try to work on these myself, but @mtzguido  you may be curious too. Especially the first one seems possibly related to the rough edges you were reporting with your `retype_binder` experiment.

**Comment by mtzguido** [comment] 2017-09-21 20:52
(For some reason, doing `apply (quote return_squash)` is blowing up for me, so I replaced it with `squash_intro` for now)

In the first one, two things are wrong. First, the tactic itself is succeeding, but the check that all implicits were instantiated is failing afterwards. This is because of a bug in `apply`, in that it's not asking for a hypothesis where it should really be doing it. Note that your goal just before `apply` is `squash (aug q)`, but apply is discharging the goal instead of asking you to prove `aug q`! This was a silly mistake in forgetting to normalize before checking if uvars were instantiated, and is fixed in my branch.

After we fix that, we fail differently on the last `exact`.
```
./T.fst(13,5-13,21): (Error) user tactic failed: uu___#697500 does not solve (?2296 q#668470) : (T.aug q#668470) (see also /home/guido/r/fstar/ulib/FStar.Tactics.Effect.fst(88,32-88,42))
```
This is a correct failure, since `?2296` is going to be resolved to a closed term and then, on the whole, the witness (the RHS) can only have `q#668470` as a free variable, and not `uu___#697500`. But how did we get this witness? It seems that unifying uvars when variables are repeated doesn't behave as I expected. By that I mean the general shape
```
?u1 a a c d = E
```
which happens in our case since we wrote `p` to `q`, so `q` is repeated. In your example, when doing intros, the terms get excessively restricted, as some added debug output shows:
```
Unifying ((?4181 q#668474 q#668474 uu___#753251 uu___#753396)) and ((fun uu___#754922:(T.aug q#668474) -> (?4270 p#668473 q#668474 uu___#753396 uu___#753251 uu___@0:Tm_app)))
Got ((fun uu___#755096:(T.aug q#668474) -> (?4296 q#668474))) and ((fun uu___#755097:(T.aug q#668474) -> (?4296 q#668474)))
```
Note that a whole bunch of free variables were dropped. Is this a bug, or a limitation of the unifier?

A way around this is to not `rewrite` on uvar applications, but that has the cost of not being able to use `subst` and means that we need to keep the rewritten variable in scope.

Also, as a very lucky workaround, doing `squash_intro` instead of `x <-- intro; squash_intro;; exact (return (pack (Tv_Var x)))` works fine and discharges the goal, since it unifies with `a -> squash a` directly.

As for the second error, I don't have a clue for now..

**Comment by mtzguido** [comment] 2017-11-18 21:17
Part 2 now doesn't have the uvar version error, after ee6e50727bc68232599074f0b6d03df268a979b6,(c.f. #1319 for discussion). It fails when doing intros:
```
(./T.fst(33,0-47,27)) Failed to solve the sub-problem

125801:	(*?u378*) _ (Tm_uvar)	?378 : Type 
		=
	Prims.squash (T.aug (fun x -> post ())) (Tm_app)	--
Which arose because:
	flex-flex kinding
	>lambda co-domain
	>Top-level:
fun uu___5337 -> (*?u348*) _ post uu___3621 uu___3833 uu___5337
	=
(*?u264*) _ (fun x -> post ()) uu___3621 uu___3833
Failed because:flex-rigid case failed all backtracking attempts
proof-state: State dump @ depth 2 (at the time of failure):
Position: ./T.fst(47,15-47,26)
ACTIVE goals (2):
(post:(uu___5547:Prims.unit -> Prims.Tot Type0)), (uu___3621:post == (fun x -> post ())), (r:T.aug (fun x -> post ())) |- fun uu___5559 -> (*?u383*) _ : uu___5563:T.aug (fun x -> post ()) -> Prims.Tot (Prims.squash (T.aug (fun x -> post ())))
(post:(uu___5566:Prims.unit -> Prims.Tot Type0)), (uu___3621:post == (fun x -> post ())), (r:T.aug post) |- (*?u299*) _ post uu___3621 r : T.aug post
SMT goals (0):

/home/guido/r/fstar/ulib/FStar.Tactics.Effect.fst(107,45-107,55): (Error) user tactic failed: intro: unification failed
1 error was reported (see above)
```

**Comment by mtzguido** [comment] 2018-06-15 23:44
This all seems fixed now, with the second one failing with
```
FStar.Tactics.Logic.fst(61,41-61,54): (Error 217) Tactic left uninstantiated unification variable ?236 of type (*?u236*) _ (reason = "apply arg") (see also examples/tactics/Bug1256.fst(36,13-36,21))
```
when we check the implicits at the end. This is a bit unfortunate, since one might want to *admit* a proof obligation that has some implicits and continue proving the rest of the program, but this would cause an error. I see this final implicit check as somewhat paranoid, so maybe we could just blow it away. Or perhaps skip it when the tactic used some unsafe feature such as `admit`?

**Comment by mtzguido** [comment] 2018-08-23 19:18
Looking at it again, everything is working fine here. Adding the examples (fixed to work in-full) to regressions and closing.

**Closed by mtzguido** 2018-08-23 19:18 UTC
Labels: component/tactics, kind/bug
