### ISSUE TITLE
Discrepancy in parsing between F# and OCaml versions of F*

### ISSUE THREAD

**Issue by nikswamy** [FStarLang/FStar#441] opened 2015-12-03 18:40 UTC
This code fails to parse in the F# version although it succeeds in OCaml. Rather surprising, since the parsers are identical. However, the lexers do differ ...maybe that contributes to this somehow. Not sure yet.

```
module T
type t : int -> Type
type f  = o:option (x:int & t x){is_Some o}
```

**Comment by dsyme** [comment] 2015-12-03 20:07
You might want to update to FsLexYacc from github.com/fsprojects. If there's a bug in the parser generator then please report it

**Comment by s-zanella** [comment] 2015-12-04 14:36
This is the same as #404.  Here's a minimal example:
```
module M
type t = (x:unit & unit)
```
We updated FsLexYacc in October. We're using the latest version (v6.1.0) from NuGet.
It looks more like a bug in our F# code for parser utilities rather than a FsLexYacc bug.

**Comment by s-zanella** [comment] 2015-12-04 14:38
Closing this as a duplicate of #404.

**Closed by s-zanella** 2015-12-04 14:38 UTC
Labels: bug, duplicate
