### ISSUE TITLE
Several Warning 271s  and 241 when using fresh opam installation

### ISSUE THREAD

**Issue by A-Manning** [FStarLang/FStar#1677] opened 2019-03-06 15:13 UTC
tested with a fresh opam installation of F* (master).

When verifying a file, I get the following output
`fstar.exe Foo.fst`
```
.opam/4.06.1/lib/fstar/prims.fst(0,0-0,0): (Warning 241) Unable to compute digest of .opam/4.06.1/lib/fstar/prims.fst.checked since file .opam/4.06.1/lib/fstar/prims.fst.checked does not exists; will recheck .opam/4.06.1/lib/fstar/prims.fst and all subsequent files
.opam/4.06.1/lib/fstar/FStar.List.Tot.Properties.fst(1010,2-1010,136): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  Prims.eq2 Prims.eq2
.opam/4.06.1/lib/fstar/FStar.Seq.Properties.fst(939,2-939,49): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  Prims.op_Addition 1
.opam/4.06.1/lib/fstar/FStar.Seq.Properties.fst(958,2-958,33): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  0
.opam/4.06.1/lib/fstar/FStar.UInt.fst(625,8-625,66): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  Prims.eq2 Prims.op_Modulus 0
.opam/4.06.1/lib/fstar/FStar.UInt.fst(626,8-626,23): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  Prims.eq2 Prims.op_Modulus 0 (see also .opam/4.06.1/lib/fstar/FStar.UInt.fst(625,8-625,66))
.opam/4.06.1/lib/fstar/FStar.UInt.fst(644,8-644,61): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  Prims.op_LessThan
.opam/4.06.1/lib/fstar/FStar.UInt.fst(645,8-645,22): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  Prims.op_LessThan (see also .opam/4.06.1/lib/fstar/FStar.UInt.fst(644,8-644,61))
.opam/4.06.1/lib/fstar/FStar.UInt.fst(664,8-664,51): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  Prims.op_Subtraction 1
.opam/4.06.1/lib/fstar/FStar.UInt.fst(665,8-665,25): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  Prims.op_Subtraction 1 (see also .opam/4.06.1/lib/fstar/FStar.UInt.fst(664,8-664,51))
Verified module: Foo (94 milliseconds)
All verification conditions discharged successfully
```

**Comment by aseemr** [comment] 2019-03-06 15:28
Hi Asher, we recently added a check to warn the users about using Z3 theory symbols in the smt patterns which could result in unexpected behaviors. We are working on removing these warnings from the `ulib` files as part of #1666. You could use `--warn_error` option to silence these for the time being. Closing this issue since it is the expected behavior but please re-open if you have more questions/suggestions.

**Closed by aseemr** 2019-03-06 15:28 UTC
