### ISSUE TITLE
Dependent pair deconstruction / construction issue

### ISSUE THREAD

**Issue by theolaurent** [FStarLang/FStar#1491] opened 2018-07-06 08:44 UTC
I cannot manage to write generic functions taking advantage of dependent pairs. Here is a snippet:
```
val id : (x:Type & x) -> (y:Type & y)
let id p = match p with
  | (|a, b|) -> (|a, b|)
```
It raises `(Error 12) Expected type "y: Type & y"; but "(| a, b |)" has type "_: Type & a"`
How to make it work? Is it a bug?

**Comment by aseemr** [comment] 2018-07-06 09:31
This is a sort of known issue.

This works:

```
let id (p:(x:Type & x)) :(y:Type & y) =
  match p with
  | (|a, b|) -> (| a, b |)
```

And this too:

```
val id : (x:Type u#a & x) -> (y:Type u#a & y)  //note the explicit universe annotations
let id p =
  match p with
  | (|a, b|) -> (| a, b |)
```

The problem is in the universe  generalization code. When F* type checks the `val` declaration in your example, it figures that id is polymorphic in two universes, which then makes the implementation of `id` type incorrect. So, F* "over-generalizes" the universes in the `val` declaration.

On the other hand providing explicit universe annotations on `val` or rather just write the `let` works since then F* can figure out that there is only a single universe to generalize.

**Comment by aseemr** [comment] 2018-07-06 09:41
#604.

**Comment by catalin-hritcu** [comment] 2018-07-06 22:28
Closing as duplicate

**Closed by catalin-hritcu** 2018-07-06 22:28 UTC
Labels: status/duplicate
