### ISSUE TITLE
Order sensitivity for typeclass resolution?

### ISSUE THREAD

**Issue by TWal** [FStarLang/FStar#3130] opened 2023-12-02 17:32 UTC
See the following snippet:

```fstar
class typeclass1 (a:Type0) = {
  x: unit;
}

class typeclass2 (bytes:Type0) {|typeclass1 bytes|} (a:Type) = {
  y:unit;
}

assume val bytes: Type0
assume val bytes_typeclass1: typeclass1 bytes
instance bytes_typeclass1_ = bytes_typeclass1
assume val t: Type0 -> Type0
assume val t_inst: t bytes

assume val truc:
  #bytes:Type0 -> {|typeclass1 bytes|} ->
  #a:Type -> {|typeclass2 bytes a|} ->
  t bytes -> a ->
  Type0

noeq
type machin (a:Type) {|typeclass2 bytes a|} = {
  lemma:
    content:a ->
    Lemma
    (ensures truc t_inst content) // error here on `truc`
  ;
}
```

This snippet works on the commit 3ad64126966f25423c7fb897412faebc540b864a.
However, with the commit a780656d449a2ae6df84516f4404cfbb3d33fcd7, there is the following error:

```
(Error 228) - Tactic failed
  - "Typeclass resolution failed: could not solve constraint: typeclass2 bytes a"
```

Maybe it was introduced by #3117? (didn't test yet)

**Comment by mtzguido** [comment] 2023-12-02 18:38
Thanks Théophile, I think I have a fix for this (I'll merge it if it passes everest regressions).

The main reason is that there are two constraints to solve in the type `machin`: the one in its typeclass parameter `d : typeclass2 bytes #(*instance*) a` and the one for `truc`. The typechecker is trying to solve the one for `truc` first, and refusing to use the dictionary `d` since it still has an unresolved uvar in it, and it would get instantiated (which leads to all sorts of weirdness, see #3115 or https://github.com/FStarLang/FStar/commit/00fa94f3218d7ea52c5bfa8f326059641f9f9f47).

Doing a round of solving implicits in type constructor (hence parameters) before the data constructors fixes this one. And I didn't find a way to trigger this without such a type.

But, I'm not 100% convinced about it. It seems weird that we're order sensitive wrt typeclasses, so maybe the right thing to do if solving a constraint fails is to keep trying with other ones and then come back to the failing one. So I'm keeping this open and relabeling.

Please report if you find any other problem! And if you want to add any tests to `tests/typeclasses` that's very welcome.

Thanks!
Guido

**Comment by TWal** [comment] 2023-12-02 21:12
Ah, interesting!
A related issue is #2591 (that arised in the same project, hence a similar example), but the snippet worked with none of the two commits I mentioned in the first message.

**Comment by mtzguido** [comment] 2023-12-02 21:57
Thanks for reminder, posting there.

**Comment by TWal** [comment] 2023-12-03 13:25
Here is another that regressed (adapted from the first example):

```fstar
class typeclass1 (a:Type0) = {
  x: unit;
}

class typeclass2 (bytes:Type0) {|typeclass1 bytes|} (a:Type) = {
  y:unit;
}

assume val bytes: Type0
assume val bytes_typeclass1: typeclass1 bytes
instance bytes_typeclass1_ = bytes_typeclass1
assume val t: Type0 -> Type0
assume val t_inst: t bytes

assume val truc:
  #bytes:Type0 -> {|typeclass1 bytes|} ->
  #a:Type -> {|typeclass2 bytes a|} ->
  t bytes -> a ->
  Type0

noeq
type machin (a:Type) {|typeclass2 bytes a|} = {
  pred: a -> prop;
  lemma:
    content:a ->
    Lemma
    (ensures truc t_inst content)
  ;
}


val bidule:
  #a:Type -> {|typeclass2 bytes a|} ->
  m:machin a -> x:a ->
  Lemma
  (requires m.pred x)
  (ensures True)
let bidule #a #tc2 m x = ()
```

**Comment by mtzguido** [comment] 2023-12-03 20:04
Great example, thanks! Could you try this branch? https://github.com/mtzguido/FStar/tree/3130. It introduces some deferring of meta-args until their type and environment are fully defined (no uvars). But it still finally tries to run them in partially-unresolved contexts if no progress is made, which we apparently rely on heavily in Steel. If you find that it works better I can try to get it polished and to master.

**Comment by mtzguido** [comment] 2023-12-05 20:27
I think #3134 pretty much takes care of it.

**Closed by mtzguido** 2023-12-05 20:27 UTC
Labels: component/typeclasses
