### ISSUE TITLE
Strange propagation of VC when using quantifiers

### ISSUE THREAD

**Issue by kyoDralliam** [FStarLang/FStar#1089] opened 2017-06-20 10:22 UTC
stumbled on that surprising example with @jakesilverman

```F#
module Test

open FStar.Seq

let _in (s:seq 'a) = k:nat{k < length s}
let works (s:seq 'a) =
  match length s with
  | 0 -> ()
  | _ -> let s' = tail s in assert (forall (i:_in s'). True) ; ()

let fails (s:seq 'a) =
  match length s with
  | 0 -> ()
  | _ -> assert (forall (i:_in (tail s)). True) ; ()
```

The second fails with `Failed to verify implicit argument: Subtyping check failed; expected type (s:FStar.Seq.Base.seq 'a{ Prims.b2t (FStar.Seq.Base.length s > 0) }); got type FStar.Seq.Base.seq 'a` at the level of the argument of the function (where it does not hold) instead of keeping it in the branch of the match

**Comment by nikswamy** [comment] 2017-10-14 18:48
This doesn't have much to do with quantifiers.

I see it as a duplicate of #580 , since what's happening is that the implicit argument of `forall` is not being type-checked in a context that includes the control-flow assumption of `length s <> 0`.

The plan to fix this is @aseemr-msr 's two-phase type-checker. .Which is close to completion. Also see #1307

**Closed by nikswamy** 2017-10-14 18:48 UTC
