### ISSUE TITLE
Refiniment types in lists

### ISSUE THREAD

**Issue by GKerfImf** [FStarLang/FStar#593] opened 2016-07-25 17:11 UTC
Hello, 

Let's сonsider the following predicates and function 
```fs
assume val p1: n:nat -> Tot bool
assume val p2: n:nat -> Tot bool
assume val f: n: nat {p1 n} -> Tot bool
```
Now I have 2 lists. One with elements that satisfy p1 and other with elements that satisfy p1 /\ p2
I can write them the following way:
```fs
//first way:
list (n: nat {p1 n}) 
list (n: nat {p1 n /\ p2 n})

//second way:
l: list nat {forall n. List.Tot.mem n l ==> p1 n}
l: list nat {forall n. List.Tot.mem n l ==> (p1 n /\ p2 n)}
```

We have a function for which only p1 is essentially .
We can also write this in two ways.
```fs
assume val fl1: list (n: nat {p1 n}) -> Tot bool
assume val fl2: l:list nat {forall n. List.Tot.mem n l ==> p1 n} -> Tot bool
```

The first way to define the list has a significant drawback:
```fs
val test1:
    ln1: list (n: nat {p1 n})
    -> ln2: list (n: nat {p1 n /\ p2 n})
    -> Tot bool
let test1 ln1 ln2 = fl1 ln1 || fl1 ln2    // Fail 
```

While the second method is still good
```fs
val test2:
    ln1: list nat {forall n. List.Tot.mem n ln1 ==> p1 n}
    -> ln2: list nat {forall n. List.Tot.mem n ln2 ==> (p1 n /\ p2 n)}
    -> Tot bool
let test2 ln1 ln2 = fl2 ln1 || fl2 ln2    // Ok
```
It seems that the second method of specifying the list is preferable.

But now I need to use the List.map. And I see the opposite side. The first way works, the second - doesn't work.
```fs
val test3:
    ln1: list (n: nat {p1 n})
    -> ln2: list (n: nat {p1 n /\ p2 n})
    -> Tot (list bool)
let test3 ln1 ln2 = 
    List.Tot.map f ln1 @ List.Tot.map f ln2    // Ok
```
```fs
val test4:
    ln1: list nat {forall n. List.Tot.mem n ln1 ==> p1 n}
    -> ln2: list nat {forall n. List.Tot.mem n ln2 ==> p1 n /\ p2 n}
    -> Tot (list bool)
let test4 ln1 ln2 = 
    List.Tot.map f ln1 @ List.Tot.map f ln2    // Fail 
```

For the first method, it's boring, for each type to keep his own coercion (like in [#65](65)). On the other hand, for the second method it is not clear how to use the map and etc. Could you tell me the best way to solve problems of this kind?

**Comment by nikswamy** [comment] 2016-07-25 18:00
These are indeed tricky tradeoffs. I don't really have a good answer. I can only say that this is yet another great example to motivate the addition of polarities to the system (as discussed in #65 and elsewhere).

**Comment by catalin-hritcu** [comment] 2016-08-09 19:31
Closing this as duplicate of #65. Let's continue the discussion there if needed.

**Closed by catalin-hritcu** 2016-08-09 19:31 UTC
Labels: duplicate
