### ISSUE TITLE
Unexpected name clashes when using .fsi file.

### ISSUE THREAD

**Issue by fmrl** [FStarLang/FStar#407] opened 2015-10-02 02:35 UTC
Given a file named `ex1.fsi`:
```
(*--build-config
--*)

module Example1

   // this example fails to verify if the type is defined here.
   type YY 'aa = 'aa -> Tot 'aa
```

And the following file named `ex1.fst`:
```
(*--build-config
   other-files:ex1.fsi
--*)

module Example1

   // this example verifies if the type is defined here.
   //type YY 'aa = 'aa -> Tot 'aa

   type ZZ 'aa =
      | MkZZ: yy:YY 'aa -> ZZ 'aa
```

I get the following error message:
```
<input>(11,17-11,19): Identifier not found: [YY] (Possible clash with related name at ex1.fsi(4,15-6,31))
```

Is this a mistake on my part or a bug in F*?

Thanks in advance.
~mlr

**Comment by aseemr** [comment] 2015-10-02 05:12
As far as I understand, this is the expected behavior. I think of a.fsi and a.fst as "a.fst provides the interface a.fsi". All the type definitions that are there in .fsi should be present in .fst also (see other .fsi and .fst in lib/ for example).

**Comment by markulf** [comment] 2015-10-02 09:24
The error message is confusing in this case. `(Possible clash with related name at ex1.fsi(4,15-6))` isn't really a clash, its more a hint that this is what should be implemented.

I guess this is tough usability engineering, as one error messages may have to fit multiple situations depending on the context.

**Comment by catalin-hritcu** [comment] 2015-10-02 11:58
To be honest, I've never seen any context in which the `Possible clash` part made sense to me as an user.

**Comment by markulf** [comment] 2015-10-11 20:57
Just wasted some more time on this. These bad error messages are especially bad when a beginner, or when tired after a long day. In the end I had to add an `--admit-fsi`. I guess there are different ways to resolve this, either by adding an implementation in the `.fst` or the `--admit-fsi`. 

Tried to produce a representative minimal 'bug report' reproducing the error message but failed so far.

**Comment by mlr-msft** [comment] 2015-10-12 20:25
Given the following type defintions:

from `abc.fsi`:
```
module ABC
type A: Type 
type B = nat 
type C = nat
```

from `abc.fst`:
```
module ABC
type A = nat
// type B defintion in abc.fsi used.
type C = nat // expected to match definition of type C in abc.fsi.
```
You're telling me that currently only *A* and *C* are the only forms language supports, right?

I find *A* and *B* intuitive but I find *C* to be unintuitive in the absence of support for *B*.

**Comment by nikswamy** [comment] 2015-10-20 17:39
Actually, it shouldn't allow you to use `type B` in `abc.fst`. If it does, it's a bug that should be fixed.

**Comment by mlr-msft** [comment] 2015-10-21 21:14
I see. I'll look for divergence from that behavior then.

Just to verify that I understand: Is it accurate to say that only `val` and `type x: ...` statements are accessible (i.e. nothing after an `=` is accessible) from outside of a `.fsi` file?

**Comment by fmrl** [comment] 2015-11-10 03:44
a related error message:

`ex.fsi`:
```
module Ex
type Y 'a = 'a -> Tot 'a
type X 'a = | Make: cx:Y 'a -> X 'a
val make_x: Y 'a -> Tot (X 'a)
```

`ex.fst`:
```
(*--build-config
   options:--admit_fsi FStar.Seq;
   other-files:seq.fsi ex.fsi
--*)
module Ex
let make x =
   Make x 
```

terminal output:
```
computer :: ~/Desktop » fstar.exe ex.fst

Unexpected error; please file a bug report, ideally with a minimized version of the source program that triggered the error.
Type name not found: X
```

also, is the following true (question posed earlier)?

> Just to verify that I understand: Is it accurate to say that only val and type x: ... statements are accessible (i.e. nothing after an = is accessible) from outside of a .fsi file?

**Comment by nikswamy** [comment] 2015-11-10 03:57
This is a bug. But X, Y and Make are all unbound in the implementation module. It should report an error more gracefully.


Sent from a mobile device



From: michael lowell roberts

Sent: Monday, November 9, 7:44 PM

Subject: Re: [FStar] Unexpected name clashes when using .fsi file. (#407)

To: FStarLang/FStar

Cc: nikswamy



a related error message:


ex.fsi:


module Ex type Y 'a = 'a -> Tot 'a type X 'a = | Make: cx:Y 'a -> X 'a val make_x: Y 'a -> Tot (X 'a) 


ex.fst:


(*--build-config options:--admit_fsi FStar.Seq; other-files:seq.fsi ex.fsi --*) module Ex let make x = Make x 


terminal output:


computer :: ~/Desktop » fstar.exe ex.fst Unexpected error; please file a bug report, ideally with a minimized version of the source program that triggered the error. Type name not found: X 


also, is the following true (question posed earlier)?



Just to verify that I understand: Is it accurate to say that only val and type x: ... statements are accessible (i.e. nothing after an = is accessible) from outside of a .fsi file?

**Comment by VincentCheval** [comment] 2016-01-29 16:48
I tried the code of `furl` above and I obtain the same error message as him. However, I do not have an error in the following:

`Test.fsi`:

```
module Test

val test : int -> int -> Tot bool
val lemma : x:int -> Lemma (requires True) (ensures test x x)

type ahahaha
val test2 : int -> ahahaha -> Tot bool
``` 

`Test.fst`

```
(*--build-config
   other-files:Test.fsi
--*)

module Test

let test x y = x = y
``

terminal output:

```
vincheval:Fstar Version vincentcheval$ fstar Test.fst
Verifying i'face: Test
Verifying module: Test
All verification conditions discharged successfully
``

**Comment by nikswamy** [comment] 2016-01-29 17:34
.fsi files are on their way out. Supporting them accurately is too painful and we have other means of enforcing abstractions. This bug will not be fixed; rather .fsi will just become illegal.

**Comment by VincentCheval** [comment] 2016-01-29 22:25
When you say .fsi will become illegal, is it the same for .fsti ? because I have the same issue when I rename my .fsi into a .fsti

**Comment by nikswamy** [comment] 2016-01-29 23:25
Yes, both .fsi and .fsti interfaces will soon become illegal.

**Comment by VincentCheval** [comment] 2016-01-29 23:27
Thanks for the information. I wonder what the new system is gonna be 😊

**Comment by nikswamy** [comment] 2016-06-17 14:37
After much back and forth, we now actually have a system for supporting interfaces (available only with --universes)

https://github.com/FStarLang/FStar/wiki/F%E2%98%85-interfaces-(split-file,-more-complicated-version)

With .fsti+.fst files, the original example from @mlr-msft works (suitably adapted to the revised naming conventions)

Issue407.fsti
```
module Issue407
type yy 'aa = 'aa -> Tot 'aa
```

Issue407.fst:
```
module Issue407
type zz 'aa =
      | MkZZ: yy 'aa -> zz 'aa
```

Additionally, the example from @VincentCheval is rejected, as it should be.

**Closed by nikswamy** 2016-06-17 14:37 UTC
Labels: bug, error-message, needs-confirmation, usability
