### ISSUE TITLE
Suggested type for ex.8a in tutorial fails verification of the exercise

### ISSUE THREAD

**Issue by hoheinzollern** [FStarLang/FStar#205] opened 2015-04-21 10:11 UTC
I'm having a problem to finding the right type for exercise 8a of the tutorial. If I use the suggested type and try to verify the code I get the following message:

```
bash-3.2$ make dynacls2.ver
../dist_web/bin/fstar --debug_level Low --prims ../dist_web/lib/prims.fst --fstar_home ../dist_web ../dist_web/lib/set.fst ../dist_web/lib/heap.fst ../dist_web/lib/st.fst ../dist_web/lib/list.fst ../dist_web/lib/option.fst  --verify dynacls2.fst
dynacls2.fst(35,0-38,18) : Error
Computed type "unit" and effect "ALL" is not compatible with the annotated type "unit" effect "STATE"
```

the problem lies in the type for revoke:
```
val revoke: e:entry -> ST unit (requires (fun h -> True))
                               (ensures (fun h x h' -> not(List.mem e (sel h' acls))))
                               (modifies (a_ref acls))
let revoke e = 
  let a = ST.read acls in
  let db = List.filter (fun e' -> e<>e') a in
  ST.write acls db
```
If I don't specity the type verification succeeds, otherwise I get said error message. Does anyone know why?

**Comment by ngrimm** [comment] 2015-04-21 11:11
The problem is that you are trying to give the effect ST to the function revoke, while FStar can only give the effect ALL to it.
This is because the function revoke uses the function List.filter which has effect ALL. 
You can make your code work by replacing the function List.filter with the function List.filterT, which does exactly the same but is total. (It also requires that the function in the first argument is total, but that is given in your case.)

**Comment by hoheinzollern** [comment] 2015-04-21 11:26
Thanks for the reply. Then I propose to change the tutorial by using `filterT`, and also there is a typo in the description of the exercise the functions `canRead` and `canWrite` should really be `grant` and `revoke`.

**Comment by catalin-hritcu** [comment] 2015-08-24 05:06
@hoheinzollern Can you please merge change 2a6a9f4 into our repo? Or if you prefer make it a pull request and I can merge it.

**Comment by msprotz** [comment] 2016-06-16 20:55
@catalin-hritcu can you close this if it's done?

**Comment by msprotz** [comment] 2016-06-16 20:56
looks like the commit exists in the f* tree; closing

**Closed by msprotz** 2016-06-16 20:56 UTC
Labels: documentation
