### ISSUE TITLE
Inconsistency by matching on `UInt8.t`

### ISSUE THREAD

**Issue by catalin-hritcu** [FStarLang/FStar#1572] opened 2018-10-24 07:38 UTC
The complete coverage check when pattern matching on `UInt8.t` is completely bogus and allows one to prove false:
```Fstar
let f (i:FStar.UInt8.t) = if i = 0x00uy then 0x00uy else 0x01uy

let bad_lemma (i:FStar.UInt8.t) : Lemma (f i = 0x00uy) =
  match i with
  | 0x00uy -> assert_norm (f 0x00uy = 0x00uy)

let contra() : Lemma False =
  assert_norm (f 0x01uy = 0x01uy);
  bad_lemma 0x01uy
```

**Comment by mtzguido** [comment] 2018-10-24 07:44
I think this is quite likely the same issue as the first part of #1535. `UInt8.t` has a single constructor, so that optimization might kick in but of course it's bogus since there is a subpattern. I can look in the afternoon.

**Comment by catalin-hritcu** [comment] 2018-10-24 07:53
For what it's worth, the following fails as expected:
```
type box (a:Type) = | C : a -> box a

let f (b:box int) : int = if b = (C 0) then 0 else 1

let bad_lemma (b:box int) : Lemma (f b = 0) =
  match b with
  | C 0 -> assert_norm (f (C 0) = 0)
```
```
Patterns are incomplete
```

**Comment by catalin-hritcu** [comment] 2018-10-24 07:54
The other thing that worries me is that `Uint8.t` is `abstract type`, so matching on its representation is shady anyway.

**Comment by mtzguido** [comment] 2018-10-24 07:58
Indeed, the problem is a bit different. The culprit is this `if`:

https://github.com/FStarLang/FStar/blob/338a9fb5b8f64fc9f1edd90038d9e86ad383112c/src/typechecker/FStar.TypeChecker.TcTerm.fs#L2176-L2180

The pattern in this case, given the special desugaring for `UInt8.t`, is `__uint_to_t 0`. Which is not a data constructor. This should be rejected instead of succeeding happily without a guard. Trying a regression build with that.

**Comment by aseemr** [comment] 2018-10-24 09:56
For example as is done in the `Tm_constant` case above (after checking that `args` are all constants).

**Comment by aseemr** [comment] 2018-10-24 10:09
Or better, treat __uint_to_t n as a constant, it's special in the compiler anyway.

**Comment by fournet** [comment] 2018-10-24 12:00
Please add plenty of negative tests to regression...

**Comment by mtzguido** [comment] 2018-10-24 13:36
I don't know what's best, honestly. Should we even match on these integers? FWIW I removed the `if not (Env.is_datacon ..` and kept only the `else` branch in each case, and CI passes (branch `guido_1572`). This example fails then with `(Error) Name "FStar.UInt8.__uint_to_t" not found`

**Comment by aseemr** [comment] 2018-10-24 14:22
My thinking is: these are integer constants, so, from a user perspective it is fine to match on them ... just like it is fine to match on `int` or `nat`.

The compiler is treating these constants specially by desugaring them as `__uint_to_t n`. So, in this piece of code, we could treat them just like other constants.

On the other hand, any time we are returning `[ ]` from this code, it seems dangerous for the pattern exhaustiveness check. So may be @nikswamy can add some comments in this code so that we can convince ourselves that the remaining cases are ok. I don't know the original idea behind those.

**Comment by aseemr** [comment] 2018-10-24 14:43
I think I understand the code a little bit now. The top-level pattern is not supposed to be a `Tm_app` unless it is application of a data constructor (e.g. it would not even parse). It is this desugaring of machine integers that breaks the invariant.

**Comment by mtzguido** [comment] 2018-10-24 14:47
Thta's right, and what really bothers me is that the parser seems to be a part of the TCB by enforcing this. I would expect that this should fail (by default) and hten *maybe* we have some special handling to `uint_to_t` above that.

**Comment by aseemr** [comment] 2018-10-24 14:52
I think it is *ok* to allow these terms for a dot pattern. So, may be this function needs to track that all these `Tm_app` nodes etc. (essentially all the cases when we are returning `[]`) are when we are (recursively) inside a dot pattern.

**Comment by aseemr** [comment] 2018-10-24 14:53
Which would fail this example -- and then we should add special handling for `__uint_to_t` by treating it similar to `Tm_const`.

**Comment by nikswamy** [comment] 2018-10-24 20:15
My understanding is that the code is incorrectly assuming that all non data-constructor applications in the expression corresponding to the pattern (`pat_exp`) are implicit arguments filled in by unification (I.e., "dot patterns"). This assumption is broken by the `__uint_to_t` introduced when desugaring machine-integer constants that appear in patterns.

The status of machine integers is a bit odd. On the one hand, they are defined in the libraries as abstract types modeled using mathematical integers. But, they have primitive syntax and primitive desugaring. We even elide trivial bounds checks on machine integer constants (e.g., `v (0 uy) < 256` etc.) since these are enforced in ToSyntax.

One possible way to see it is that the machine integer types and their constants are built in to the language, but they have no operations aside from those provided by the FStar.[U]Int[N] libraries. But the line is pretty blurry.

In any case, I'm with @aseemr in that I think we should retain pattern matching on machine integer constants since these constants are already primitive in the language. This stle is pretty common already in many programs so it would be hard to remove.

Treating the occurrence of `___uint_to_t` in `pat_exp` in the same way as `Tm_constant` sounds reasonable.

We could also be more defensive and check that when we encounter on non-data or variable sub-term in `pat_exp` then this really corresponds to an inaccessible sub-term (i.e., a dot pattern) in the orignial patttern. I think this is also one of Aseem's suggestions.

Finally, I'm surprised @mtzguido  that just removing the Env.is_datacon check worked. I guess it's just adding more guards, some of them possibly redundant, e.g., things like `proj_0 (Mktuple3 #int #_ _ _ ) = int` etc.

**Comment by nikswamy** [comment] 2018-10-25 04:14
FYI, my status: I have a patch in nik_1572 that seems to mostly work. I have a failure in StreamAE.fst-ver (in TLSConstants.fst) which I need to investigate further.

**Comment by nikswamy** [comment] 2018-10-25 14:50
The proof in TLSConstants seems to be failing because of an unrelated context pollution issue in miTLS. Trying to resolve that separately now.

**Comment by nikswamy** [comment] 2018-10-25 19:30
Fixed and merged in master.

**Comment by nikswamy** [comment] 2018-10-25 19:30
That said, if @aseemr and/or @mtzguido want to have a look at my diff in nik_1572 and comment on it, that would be most welcome.

**Closed by nikswamy** 2018-10-25 19:30 UTC
Labels: kind/unsoundness, priority/high
