### ISSUE TITLE
Memory and performance regressions after the merge of the core typechecker branch

### ISSUE THREAD

**Issue by msprotz** [FStarLang/FStar#2757] opened 2022-11-14 18:28 UTC
Sucessful build from last Friday (11/11), in the morning: https://everest-ci.paris.inria.fr/build/4139

```
[VERIFY] Test.Vectors.Chacha20Poly1305.fst, 1:44.01
```

Successful build from last Friday (11/11), later in the day: https://everest-ci.paris.inria.fr/build/4181

```
[VERIFY] Test.Vectors.Chacha20Poly1305.fst, 44:32.08
```

We are also starting to notice out-of-memory errors on the HACL build that weren't there before. A recent build OOM'd on that file above, and on my machine I see 4.8GB used for Test.Vectors.Chacha20Poly1305. As a point of comparison, when @mtzguido ran his most recent memory usage analysis, in https://github.com/FStarLang/FStar/pull/2734#issuecomment-1285586701, that file wasn't even one of the "top" 25 files for memory usage, meaning that its memory usage was below 1.6GB. So it looks like memory usage tripled for that file, and verification time exploded too.

CCing @karthikbhargavan, @R1kM and @polubelova as the HACL maintainers.

**Comment by nikswamy** [comment] 2022-11-14 20:18
Thanks for reporting ... taking a look. It doesn't seem like that files uses tactics at all, so it's a bit surprising.

**Comment by nikswamy** [comment] 2022-11-14 21:00
The perf regression turns out to not be related to the core checker at all. 

There was a change to the way the normalizer was memoizing the reduction of the scrutinee in pattern matches that impacts performance severely in this example. Reverting that one change to the normalizer makes this example go through again in a minute or so.

Working on a patch ...

**Comment by msprotz** [comment] 2022-11-14 21:27
Thanks. Should Everest regressions include time and memory measurements? Guido had a nice proposal for measuring that (and post-processing the result) in #2734, which leads me to think at least the top 10 files for memory / time could be reported as part of a build.

**Comment by nikswamy** [comment] 2022-11-15 17:54
hi @msprotz, that PR #2759 fixed the perf regression on this file. Closing this issue for now. Do re-open if you find any other perf regressions. 

I agree that it would be useful to report time & memory measurements as part of CI. Maybe you can open an issue requesting that on project-everest/everest?

**Closed by nikswamy** 2022-11-15 17:54 UTC
