### ISSUE TITLE
Replacing type by provably propositionally equal type breaks typechecking

### ISSUE THREAD

**Issue by s-zanella** [FStarLang/FStar#606] opened 2016-08-10 13:45 UTC
The example below shows a case where type checking fails after replacing a type defined transparently in another module by a type that is provably propositionally equal. Moreover, when redefining the problematic type locally, the code typechecks.

``` F#
module M

open FStar.UInt
(*
In FStar.UInt: 
type uint_t (n:pos) = x:int{size x n}

In FStar.UInt64:
val v        : t -> Tot (uint_t n)
val uint_to_t: uint_t n -> Pure t
*)

let n:pos = 32

val uint64_to_uint32: m:UInt64.t{fits (UInt64.v m) n} -> Tot FStar.UInt32.t
let uint64_to_uint32 m =
  let m': x:int{size x n} = UInt64.v m in
  UInt32.uint_to_t m'

//With this uncommented, uint64_to_uint32' below typechecks 
//type uint_t (n:pos) = x:int{size x n}

val uint64_to_uint32': m:UInt64.t{fits (UInt64.v m) n} -> Tot FStar.UInt32.t
let uint64_to_uint32' m =
  cut (uint_t n == x:int{size x n});
  cut (forall (p:uint_t n). p:(x:int{size x n}));
  let m':uint_t n = UInt64.v m in // This fails, even if the above is provable
  UInt32.uint_to_t m'
```

Labelling this as a bug, but remove the label if you believe this is expected (and please explain why!).

**Comment by nikswamy** [comment] 2016-08-11 17:53
Sorry Santiago ... this looks painful. It is a bug, but it's a bit delicate to fix ... but I really should fix it. I think it's a duplicate of another you had to suffer through, but I'm having trouble finding that issue now.

Here's what's happening:

1. This file fails even --lax checking. The error is raised by the type inference algorithm and is unrelated to the verification conditions.

2. The problem is that in the 2nd last line, we have a type inference problem of the form `t n <: t m`, i.e., a rigid-rigid subtyping. In this case, it seems we try directly to unify `n=m`, which fails in this case. The unification algorithm has support for backtracking, but, it in this case, it doesn't seem to be backtracking as expected.

3. When you add the intervening type abbreviation, the inference problem becomes of the form `s n <: t m`, which triggers some unfolding first and then ends up generating a verification condition relating the sizes of the integers, which Z3 can prove.

**Comment by catalin-hritcu** [comment] 2016-10-13 22:02
Same problem appeared in printf implementation, but Nik found a quick workaround (4ff8a23).

**Comment by mtzguido** [comment] 2018-06-14 00:07
@R1kM ran into this today, which seems to have been made more frequent after my changes to the unfolding logic for refinements in the unifier. I added a file `examples/micro-benchmarks/UnifyRefs.fst` with various instances of this so we keep it tracked. Failing tests have a `@fail` attached, so we'll know if they happen to be fortuitously fixed.

I can try to improve the unifier next week. For reference, this is the current test file and status. The first 8 tests fail.
```f#
[@fail]
let nat32_to_nat64'0 (n:nat32) : nat64 = n

[@fail]
let nat32_to_nat64'1 (n:natN pow2_32) : nat64 = n

[@fail]
let nat32_to_nat64'2 (n:nat32) : natN pow2_64 = n

[@fail]
let nat32_to_nat64'3 (n:natN pow2_32) : natN pow2_64 = n

[@fail]
let nat64_to_nat32'0 (n:nat64 {n < pow2_32}) : nat32 = n

[@fail]
let nat64_to_nat32'1 (n:nat64 {n < pow2_32}) : natN pow2_32 = n

[@fail]
let nat64_to_nat32'2 (n:natN pow2_64 {n < pow2_32}) : nat32 = n

[@fail]
let nat64_to_nat32'3 (n:natN pow2_64 {n < pow2_32}) : natN pow2_32 = n

(* Unfolding manually causes the unifier to do more work, and succeed *)

let nat32_to_nat64'4 (n:nat{n < pow2_32}) : natN pow2_64 = n

let nat32_to_nat64'5 (n:nat32) : (x:nat{x < pow2_64}) = n

let nat64_to_nat32'4 (n:(x:nat{x < pow2_64}) {n < pow2_32}) : nat32 = n

let nat64_to_nat32'5 (n:nat64 {n < pow2_32}) : (n:nat{n < pow2_32}) = n
```

**Comment by nikswamy** [comment] 2018-08-20 21:53
Some progress in `nik_606` ... trying to land this in master

**Closed** 2018-08-22 07:16 UTC
Labels: area/usability, component/unifier, kind/bug, to-be-squashed
