### ISSUE TITLE
Wrong error message related to MkTuple2

### ISSUE THREAD

**Issue by msprotz** [FStarLang/FStar#482] opened 2016-02-08 21:45 UTC
If I use the wrong syntax for product types, I get:

```
Identifier not found: [Prims.MkTuple2] (Possible clash with related name at D:\cygwin\home\protz\Code\FStar\lib\prims.fst(423,44-428,26))
```

by doing:

```
val gen: r0:rid -> i:id -> (state i * state i)
```

This could be improved.

**Comment by izgzhen** [comment] 2016-12-26 15:30
Hi, I guess this is already fixed?

**Comment by catalin-hritcu** [comment] 2016-12-26 16:59
Not sure how I'm supposed to reproduce this problem. The following simply succeeds:
```
val gen: int -> int -> (int * int)
```

**Comment by s-zanella** [comment] 2017-02-02 17:14
Whatever the problem was, it was fixed in the meantime. 
1 year ago we didn't even had universes in `master`.

**Closed by s-zanella** 2017-02-02 17:14 UTC
Labels: easy fix, error-message
