### ISSUE TITLE
Support for reification of indexed effects (WAS: Bug with Reify for Indexed Effects)

### ISSUE THREAD

**Issue by andricicezar** [FStarLang/FStar#2641] opened 2022-07-07 14:56 UTC
Recently I managed to prove `False` by accident while using `reify` for an indexed effect. I tried to minimize it in a PoC (with some help from @TheoWinterhalter), but it is 100 lines of code and uses Index Effects and Type Classes. I don't yet understand why I can prove False, and I don't know how to simplify and debug this further. The PoC is not using tactics (except Type Classes).

```fstar
module BugReify 


open FStar.List.Tot
open FStar.Tactics.Typeclasses

(** Working on F* release: 2022.05.06 **)

noeq
type free (a:Type u#a) : Type u#(max a 1) =
| Return : a -> free a
| PartialCall : (pre:pure_pre) -> cont:((squash pre) -> free u#a a) -> free a

let rec free_bind (#a:Type u#a) (#b:Type u#b) (l:free a) (k: a -> free b) : free b =
  match l with
  | Return x -> k x
  | PartialCall pre fnc ->
    PartialCall pre (fun _ -> free_bind (fnc ()) k)

(** *** Spec **)
(** monotonicity seems relevant **)
let hist a = wp:(pure_wp' a){pure_wp_monotonic0 a wp}

val hist_ord (#a : Type) : hist a -> hist a -> Type0
let hist_ord wp1 wp2 = forall p. wp1 p ==> wp2 p

let hist_return (x:'a) : hist 'a =
  fun p -> p x

let hist_bind (#a #b:Type) (w : hist a) (kw : a -> hist b) : hist b =
  fun p -> w (fun r -> kw r p)

let wp_lift_pure_hist (w : pure_wp 'a) : hist 'a =
  FStar.Monotonic.Pure.elim_pure_wp_monotonicity_forall ();
  w

let partial_call_wp (pre:pure_pre) : hist (squash pre) = 
  let wp' : pure_wp' (squash pre) = fun p -> pre /\ p () in
  wp'


(** *** Dijkstra Monad **)
val theta : #a:Type -> free a -> hist a
let rec theta m =
  match m with
  | Return x -> hist_return x
  | PartialCall pre k -> 
    hist_bind (partial_call_wp pre) (fun r -> theta (k r))

let dm_free (a:Type) (wp:hist a) =
  tree:(free a){wp `hist_ord` theta tree} 

val dm_free_return : (a:Type) -> (x:a) -> dm_free a (hist_return x)
let dm_free_return a x = Return x

val lemma_monad_morphism  : 
  a: Type ->
  b: Type ->
  v: free a ->
  f: (x: a -> free b) ->
  Lemma (hist_bind (theta v) (fun x -> theta (f x)) `hist_ord` theta (free_bind v f))
let rec lemma_monad_morphism a b v f =
  match v with
  | Return _ -> ()
  | PartialCall pre k -> 
    calc (hist_ord) {
      hist_bind (theta (PartialCall pre k)) (fun x -> theta (f x));
      == { _ by (FStar.Tactics.compute ()) }
      hist_bind (hist_bind (partial_call_wp pre) (fun r -> theta (k r))) (fun x -> theta (f x));
      == { _ by (FStar.Tactics.compute ()) }
      hist_bind (partial_call_wp pre) (fun r -> hist_bind (theta (k r)) (fun x -> theta (f x)));
      `hist_ord` {         
        let rhs1 : squash pre -> hist b = fun r -> hist_bind (theta (k r)) (fun x -> theta (f x)) in
        let rhs2 : squash pre -> hist b = fun r -> theta (free_bind (k r) f) in
        introduce forall (r:squash pre). (rhs1 r) `hist_ord` (rhs2 r) with begin
          lemma_monad_morphism _ _ (k r) f
        end
      }
      theta (PartialCall pre (fun r -> free_bind (k r) f));
      `hist_ord` { _ by (FStar.Tactics.compute ()) }
      theta (free_bind (PartialCall pre k) f);
    }
  
val dm_free_bind  : 
  a: Type ->
  b: Type ->
  wp_v: hist a ->
  wp_f: (_: a -> Tot (hist b)) ->
  v: dm_free a wp_v ->
  f: (x: a -> Tot (dm_free b (wp_f x))) ->
  Tot (dm_free b (hist_bind wp_v wp_f))
let dm_free_bind a b wp_v wp_f v f =
  lemma_monad_morphism a b v f;
  free_bind v f

val dm_free_subcomp : 
  a: Type ->
  wp1: hist a ->
  wp2: hist a ->
  f: dm_free a wp1 ->
  Pure (dm_free a wp2) (hist_ord wp2 wp1) (fun _ -> True)
let dm_free_subcomp a wp1 wp2 f = f

val lift_pure_dm_free :
  a: Type ->
  w: pure_wp a ->
  f: (_: eqtype_as_type unit -> PURE a w) ->
  Tot (dm_free a (wp_lift_pure_hist w))
let lift_pure_dm_free a w f =
  FStar.Monotonic.Pure.elim_pure_wp_monotonicity_forall ();
  PartialCall (as_requires w) (fun proof -> Return (f proof))

total
reifiable
reflectable
effect {
  FREEwp (a:Type) (wp : hist a) 
  with {
       repr       = dm_free
     ; return     = dm_free_return
     ; bind       = dm_free_bind 
     ; subcomp    = dm_free_subcomp
     }
}

sub_effect PURE ~> FREEwp = lift_pure_dm_free

class compilable (t:Type) = {
  comp_type : Type;
  compile: t -> comp_type
}

instance compile_option (t:Type) {| d1:compilable t |} : compilable (option t) = {
  comp_type = option (d1.comp_type);
  compile = (fun x ->
    match x with
    | Some r -> Some (compile r)
    | None -> None)
}

let test_assert_false
  (t1:Type)
  (t2:Type)
  {| d2:compilable t2 |} 
  (f:(t1 -> FREEwp (option t2) (fun p -> (forall r. p r)))) 
  (x:t1) : 
  Lemma False =
  let _ : dm_free (option d2.comp_type) (hist_bind (fun p -> forall r . p r)
                                                   (fun (r:option t2) -> hist_return (compile #(option t2) #(compile_option t2 #d2) r))) =
       reify (compile #(option t2) #(compile_option t2 #d2) (f x)) in
  assert (False)
```

I tried to do the same test without reify, but my take on it fails during verification as expected with an assertion failure on `assert False`.
```fstar
let test_without_reify
  (t1:Type)
  (t2:Type)
  {| d2:compilable t2 |} 
  (f:(t1 -> FREEwp (option t2) (fun p -> (forall r. p r)))) : 
  Lemma False =
  let _ : t1 -> FREEwp (option d2.comp_type) (hist_bind (fun p -> forall r. p r)
                                                   (fun (r:option t2) -> hist_return (compile #(option t2) #(compile_option t2 #d2) r))) =
       fun x -> (compile #(option t2) #(compile_option t2 #d2) (f x)) in
  assert (False)

```

**Comment by catalin-hritcu** [comment] 2022-07-07 17:26
On a second look, this could also fail because there's not definitions for things like `dm_free_return`, `lift_pure_dm_free`, etc. In general, it's not an inconsistency if you still have assumptions lying around :)

**Comment by andricicezar** [comment] 2022-07-08 13:04
I updated the main post and added all definitions, thus there are no more assumptions in the PoC.

Your previous test failed because previously I did not define the `subcomp` operator. I added one now.

**Comment by aseemr** [comment] 2022-07-11 11:57
Here is a minimal repro without any typeclasses etc.:

```
let compile_option : (option int -> option int) =
  fun x -> match x with
        | None -> None
        | Some r -> Some r

let test_assert_false
  (f:(unit -> FREEwp (option int) (fun p -> (forall r. p r)))) : 
  Lemma False =
  let _ : dm_free (option int) (hist_bind (fun p -> forall r . p r)
                                        (fun (r:option int) -> hist_return ((compile_option r)))) =
       reify (let eff_val = f () in
              compile_option eff_val) in
  assert False
```

We are inlining the `reify e` term in the VC, and that results in a suspicious looking smt query (note that `e` is effectful here). With a quick patch that prohibits inlining of `reify`, the proof fails as expected.

**Comment by aseemr** [comment] 2022-07-18 08:14
Please see #2654.

**Comment by aseemr** [comment] 2022-07-18 08:30
Restricting reify means that it is no longer an unsoundness, but keeping the issue open, we can use it to track support for indexed effects reification.

**Comment by SECtim** [comment] 2023-02-15 10:55
Is there some way to extract code when working with indexed effects w/o `reify`?
I want to actually execute my F* code and used something along the lines of `(reify (some_fun_with_indexed_effect some_param) initial_state)` (my effect carries a state, but does some other things as well).

**Comment by nikswamy** [comment] 2023-02-15 17:08
The issue is that in the current implementation we do not retain the index instantiations, so if the computational behavior of your effect depends on the indices, then we do not support reification, even for extraction.

If the indices of your effect are non-informative, e.g., they are type indices or are erased values, then we should be able to support reification at least for extraction. But @aseemr would know best.

**Comment by SECtim** [comment] 2023-02-17 11:10
Thanks for the clarification! My indices should be non-informative, will check that.

**Comment by qaphla** [comment] 2023-02-21 10:55
I'm working on the same project as @SECtim , and can confirm that our indices are non-informative.

When you say that it should be possible to support reification at least for extraction in this context, what would it involve to get that working, and would that require any changes to our implementation (i.e. if we want to depend on this, is it feasible to just work as if it will work at some point in the relatively near future, or would we need to make more substantial changes to get it to work once this is supported?)

Additionally, is this something that's likely to see work soon? I'd be happy to look into it as well, but don't really have the necessary expertise to know the best way to change this safely.

**Comment by aseemr** [comment] 2023-02-21 11:50
Hi @qaphla , @SECtim , we will need some typechecker changes to support this, and it should be doable without requiring any changes in your code. I will take a look early next week and let you know the feasibility. Thanks!

**Comment by SECtim** [comment] 2023-03-13 10:20
Hi @aseemr, thanks for your reply! Are there any updates on this?

**Comment by aseemr** [comment] 2023-03-14 17:25
Hi @SECtim, see this: https://github.com/FStarLang/FStar/pull/2851. You can try this branch. Please feel free to ping me on slack if you see any issues.

**Comment by SECtim** [comment] 2023-03-14 17:28
Thanks a lot!

**Comment by aseemr** [comment] 2023-03-17 15:38
PR #2851 adds limited support for extraction of indexed effects. Reification of indexed effects in their full generality is a bigger chunk of work, and we don't plan to address in the next few months.

Closing this PR, please reopen / file a new issue if you see any issues with the supported fragment of indexed effects.

Thanks!

**Closed by aseemr** 2023-03-17 15:38 UTC
Labels: component/typechecker, component/effect-system
