### ISSUE TITLE
Extraction bug in points-free style type abbreviations

### ISSUE THREAD

**Issue by nikswamy** [FStarLang/FStar#490] opened 2016-02-19 23:07 UTC
Extracting this with --codegen OCaml fails with 

```
Error: Unexpected error; please file a bug report, ideally with a minimized version of the source program that triggered the error.
Substitution must be fully applied: instantiation of %A failed; got %A
```

```
module Test
type t (i:nat) = unit
type s = t 
let f (x: s 0) = ()
```

**Comment by msprotz** [comment] 2016-08-25 17:53
For reference, the workaround is to η-expand the type.

**Comment by nikswamy** [comment] 2016-10-25 14:32
This comes up very regularly ... we should fix it quickly

**Comment by tahina-pro** [comment] 2017-04-07 16:14
This failure also happens in a possibly unrelated case:

```
module Essai
noeq type class' : (carrier: Type0) -> Type u#1 =
| Class:
  (carrier: Type0) ->
  (b: bool) ->
  (ancestor_carrier: (squash (b == true) -> Tot Type0)) ->
  (ancestor_class: (squash (b == true) -> Tot (class' (ancestor_carrier ())))) ->
  class' carrier
```

With `fstar.exe --lax --codegen OCaml Essai.fst`, extraction fails with the following error message:

Unexpected error; please file a bug report, ideally with a minimized version of the source program that triggered the error.
Failure("Substitution must be fully applied (see GitHub issue #490)")

However, extraction succeeds if I replace `Type0` with `nat`.

**Comment by tahina-pro** [comment] 2017-04-07 18:29
Another case where extraction fails with the same message: I am trying to define a typeclass-like structure packaging some operators and predicates, and an invariant packaging lemmas about these operators and predicates, as follows:

```
module Es2
noeq type class: Type u#1 = | Class: (preserved: (nat -> GTot Type0)) -> class
noeq type class_invariant (c: class) : Type0 = {
  preserved_always: (
    (i: nat) ->
    Lemma
    (requires True)
    (ensures (Class?.preserved c i))
  );
}
let lemma_preserved_always (c: class { class_invariant c} ) (i: nat) : Lemma
  (requires True)
  (ensures (Class?.preserved c i))
= Squash.bind_squash #(class_invariant c) #(Class?.preserved c i) ()
    (fun (j: class_invariant c) -> j.preserved_always i)
```

This example fails to extract (when trying to extract lemma_preserved_always), with the same error message.

Replacing the type of `preserved_always` with `forall` instead of a function does not help, extraction still fails with the same error message.

**Comment by fournet** [comment] 2017-04-13 13:39
How to localize the problematic type? Could the failure message include a source location?

**Comment by s-zanella** [comment] 2017-04-13 16:08
The source of the error can be hard to locate. Without any debug flags, the last output lines look something like:
```
Extracted module M
Unexpected error; please file a bug report, ideally with a minimized version of the source program that triggered the error.
Failure("Substitution must be fully applied (see GitHub issue #490)")
```
This could be misleading as the problem is certainly not in module `M` but the module extracted just after it. Say it's module `N`; the flags `--debug_level Extraction --debug N` will produce much more detailed information that can help locate the problematic code.

**Comment by fournet** [comment] 2017-04-21 14:27
We are still struggling to debug instances of this bug in mitls-fstar extraction. A patch that tells us where to look at would be very helpful.

**Comment by nikswamy** [comment] 2017-04-21 21:27
The two examples reported by @tahina-pro are unrelated to the points-free style.

Renaming this issue to reflect what remains to be solved.

**Comment by nikswamy** [comment] 2017-07-25 14:25
I fixed this during last week's bug squash day. It should work now, including Tahina's examples. 

Would be great if folks reporting issues from mitls etc. can confirm that this is indeed no longer an issue in their code so we can close this.

**Comment by mtzguido** [comment] 2018-08-31 06:55
AFAICT, this hasn't popped up, closing.

**Closed by mtzguido** 2018-08-31 06:55 UTC
Labels: component/extraction, kind/bug, priority/high
