### ISSUE TITLE
Crypto.AEAD.Encoding works on my OSX machine but not on CI

### ISSUE THREAD

**Issue by msprotz** [FStarLang/FStar#893] opened 2017-03-13 15:18 UTC
```
jonathan@chartreuse:~/Code/fstar/examples/low-level/crypto (master) $ make Crypto.AEAD.Encoding.fst-ver OTHERFLAGS=--record_hints\ --z3rlimit\ 1024
../../../bin/fstar.exe --fstar_home ../../.. --max_fuel 4 --initial_fuel 0 --max_ifuel 2 --initial_ifuel 0 --z3rlimit 20  --use_hints --record_hints --z3rlimit 1024 \
    --include ../../../ulib/hyperstack --include hacl \
    --__temp_no_proj Crypto.Symmetric.MAC \
    --verify_module Crypto.AEAD.Encoding \
    Crypto.AEAD.Encoding.fst
Verified module: Crypto.AEAD.Encoding (361952 milliseconds)
All verification conditions discharged successfully
```

but:

```
./Crypto.AEAD.Encoding.fst(405,0-460,5): (Error) Unknown assertion failed
```

(on a7204466)

this is WITH hints regenerated.

Multiplying the z3rlimit by 10 gives:

```
All verification conditions discharged successfully
.\Crypto.AEAD.Encoding.fst(454,6-454,12): (Error) assertion failed (see .\Crypto.AEAD.Encoding.fst(454,12-454,46))
Verified module: Crypto.AEAD.Encoding (388249 milliseconds)
```

(on  d9089ac0)

Setting it to `--lax` to the moment but any help would be appreciated.

Thanks,

Jonathan

CC @nikswamy @s-zanella @wintersteiger

**Comment by jkzinzindohoue** [comment] 2017-03-13 15:23
It usually works if you raise the rlimit even more if that helps. If I remember correctly I regenerate hints with more than 2000 for hacl-star. Removing the hints might help as well.
On the other hand I would be happy to understand those failures.

**Comment by msprotz** [comment] 2017-03-13 15:58
The current rlimit is 2048... do you think I should try more than that?

**Comment by s-zanella** [comment] 2017-03-13 16:13
I had problems replaying hints in `examples/low-level`. E.g. a module verifying without hints but not with recorded hints. This could be another instance of it. I ran `make all-ver` on my OS X machine and it worked fine.

**Comment by wintersteiger** [comment] 2017-03-13 17:27
I tried and it verifies with old and new hints. @msprotz could you extract the query files on the CI server, so that we can see whether there's a difference on that level or whether it's a Z3-internal problem?

**Comment by s-zanella** [comment] 2017-03-19 16:13
This is not a problem anymore since the same file in hacl-star verifies fine in CI and hacl-star supersedes `examples/low-level/crypto`.

Reopen if you think that digging into this problem to find the cause is worthwhile.

**Comment by s-zanella** [comment] 2017-03-22 10:59
Reopening because the same problem showed up again in `hacl-star` and finding the root cause can help us improve hint replayability.

I reduced the problem to this piece of code:
```F#
#reset-options "--initial_fuel 0 --max_fuel 0 --initial_ifuel 0 --max_ifuel 0 --z3rlimit 400"
val accumulate: #i:MAC.id -> st:CMA.state i ->
  aadlen:aadlen_32 -> aad:lbuffer (v aadlen) ->
  txtlen:txtlen_32 -> cipher:lbuffer (v txtlen) ->
  StackInline (CMA.accBuffer i)
  (requires (fun h0 ->
    CMA.(MAC.norm_r h0 st.r) /\
    Buffer.live h0 aad /\
    Buffer.live h0 cipher /\
    Buffer.disjoint_2 CMA.(MAC.as_buffer st.r) aad cipher))
  (ensures (fun _ _ _ -> True))

let accumulate #i st aadlen aad txtlen cipher =
  let acc = CMA.start st in
  add_bytes st acc aadlen aad;
  add_bytes st acc txtlen cipher;
  //let final_word = Buffer.create 0uy 16ul in
  acc
```
With `let final_word = Buffer.create 0uy 16ul in` commented out it verifies and the hint replays.
Uncommenting it makes the code still verifies but the recorded hint no longer replays.

**Comment by s-zanella** [comment] 2017-03-22 12:49
More debugging.
Here's a self-contained example:
```F#
module M

module MAC = Crypto.Symmetric.MAC

#set-options "--lax"
val f: unit -> StackInline unit (requires (fun _ -> True)) (ensures  (fun _ _ _ -> True))

#reset-options "--initial_fuel 0 --max_fuel 0 --initial_ifuel 0 --max_ifuel 0 --z3rlimit 20"
let f _ =
  let b = Buffer.create 0uy 16ul in
  ()
```
```
~/hacl-star/secure_api $ ~/fstar/bin/fstar.exe M.fst --include ../../FStar/ulib/hyperstack --include ../code/bignum --include ../code/experimental/aesgcm --include ../code/lib/kremlin --include ../code/poly1305 --include ../secure_api/uf1cma --include ../secure_api/utils --include ../specs --include ../../kremlin/kremlib --record_hints --hint_info
(./M.fst(26,0-28,4))
	Query (M.f, 1)	succeeded in 2565 milliseconds with fuel 0 and ifuel 0
Verified module: M (3003 milliseconds)
All verification conditions discharged successfully
```
```
~/hacl-star/secure_api $ ~/fstar/bin/fstar.exe M.fst --include ../../FStar/ulib/hyperstack --include ../code/bignum --include ../code/experimental/aesgcm --include ../code/lib/kremlin --include ../code/poly1305 --include ../secure_api/uf1cma --include ../secure_api/utils --include ../specs --include ../../kremlin/kremlib --use_hints --hint_info
(/Users/anonymous/hacl-star/secure_api/M.fst) digest is valid; using hints db.
(./M.fst(26,0-28,4))
	Query (M.f, 1)	failed (with hint) in 124 milliseconds with fuel 0 and ifuel 0
(./M.fst(26,0-28,4))
	Query (M.f, 1)	succeeded in 2777 milliseconds with fuel 0 and ifuel 0
Hint-info (./M.fst(26,0-28,4)): Replay failed in 124 milliseconds
Verified module: M (3414 milliseconds)
All verification conditions discharged successfully
```
The dependencies of `Crypto.Symmetric.MAC` are crucial to get this behaviour.

The hint recorded with these dependencies fails to replay:
```
    [
      "M.f",
      1,
      0,
      0,
      [
        "@query",
        "b2t_def",
        "equation_Crypto.Symmetric.GF128.len",
        "equation_FStar.HyperStack.is_stack_region",
        "equation_FStar.UInt.fits",
        "equation_FStar.UInt.max_int",
        "equation_FStar.UInt.min_int",
        "equation_FStar.UInt.size",
        "equation_FStar.UInt.uint_t",
        "equation_FStar.UInt32.n",
        "equation_FStar.UInt32.uint_to_t",
        "equation_FStar.UInt32.v",
        "equation_FStar.UInt8.n",
        "equation_Prims.nat",
        "equation_Prims.pos",
        "fuel_correspondence_Prims.pow2.fuel_instrumented",
        "function_token_typing_Crypto.Symmetric.GF128.len",
        "function_token_typing_FStar.UInt8.n",
        "primitive_Prims.op_AmpAmp",
        "primitive_Prims.op_GreaterThan",
        "primitive_Prims.op_LessThanOrEqual",
        "primitive_Prims.op_Subtraction",
        "proj_equation_FStar.UInt32.Mk_v",
        "projection_inverse_BoxBool_proj_0",
        "projection_inverse_BoxInt_proj_0",
        "projection_inverse_FStar.UInt32.Mk_v",
        "refinement_interpretation_Tm_refine_03d0bed5c0733099844f268aecd0836d",
        "refinement_interpretation_Tm_refine_ba523126f67e00e7cd55f0b92f16681d",
        "refinement_interpretation_Tm_refine_f048236b5f8051f83b495ea5eaa6127b",
        "typing_FStar.UInt32.v",
        "typing_Prims.pow2",
        "unit_typing"
      ],
      0
    ]
```
Changing `module MAC = Crypto.Symmetric.MAC` to `module GF = Crypto.Symmetric.GF128` results in a hint that replays:
```
[
      "M.f",
      1,
      0,
      0,
      [
        "@query",
        "b2t_def",
        "equation_FStar.HyperStack.is_stack_region",
        "equation_FStar.UInt.fits",
        "equation_FStar.UInt.max_int",
        "equation_FStar.UInt.min_int",
        "equation_FStar.UInt.size",
        "equation_FStar.UInt32.n",
        "equation_FStar.UInt64.uint_to_t",
        "equation_FStar.UInt64.v",
        "equation_FStar.UInt8.n",
        "equation_Prims.nat",
        "equation_Prims.pos",
        "fuel_correspondence_Prims.pow2.fuel_instrumented",
        "function_token_typing_FStar.UInt32.n",
        "function_token_typing_FStar.UInt8.n",
        "lemma_FStar.UInt.pow2_values",
        "primitive_Prims.op_AmpAmp",
        "primitive_Prims.op_GreaterThan",
        "primitive_Prims.op_LessThanOrEqual",
        "primitive_Prims.op_Subtraction",
        "proj_equation_FStar.UInt64.Mk_v",
        "projection_inverse_BoxBool_proj_0",
        "projection_inverse_BoxInt_proj_0",
        "projection_inverse_FStar.UInt64.Mk_v",
        "refinement_interpretation_Tm_refine_ba523126f67e00e7cd55f0b92f16681d",
        "refinement_interpretation_Tm_refine_f048236b5f8051f83b495ea5eaa6127b",
        "typing_Prims.pow2",
        "unit_typing"
      ],
      0
    ]
```
```
~/hacl-star/secure_api $ ~/fstar/bin/fstar.exe M.fst --include ../../FStar/ulib/hyperstack --include ../code/bignum --include ../code/experimental/aesgcm --include ../code/lib/kremlin --include ../code/poly1305 --include ../code/salsa-family --include ../secure_api/aead --include ../secure_api/prf --include ../secure_api/vale --include ../secure_api/uf1cma --include ../secure_api/utils --include ../specs --include ../../kremlin/kremlib --record_hints --hint_info
(./M.fst(12,0-14,4))
	Query (M.f, 1)	succeeded in 2945 milliseconds with fuel 0 and ifuel 0
Verified module: M (3236 milliseconds)
All verification conditions discharged successfully
```

```
~/hacl-star/secure_api (santiago_freshness) $ ~/fstar/bin/fstar.exe M.fst --include ../../FStar/ulib/hyperstack --include ../code/bignum --include ../code/experimental/aesgcm --include ../code/lib/kremlin --include ../code/poly1305 --include ../code/salsa-family --include ../secure_api/aead --include ../secure_api/prf --include ../secure_api/vale --include ../secure_api/uf1cma --include ../secure_api/utils --include ../specs --include ../../kremlin/kremlib --use_hints --hint_info
(/Users/anonymous/hacl-star/secure_api/M.fst) digest is valid; using hints db.
(./M.fst(12,0-14,4))
	Query (M.f, 1)	succeeded (with hint) in 118 milliseconds with fuel 0 and ifuel 0
Hint-info (./M.fst(12,0-14,4)): Replay succeeded in 118 milliseconds
Verified module: M (202 milliseconds)
All verification conditions discharged successfully
```

Adding `"lemma_FStar.UInt.pow2_values"` to the hint that fails makes it succeed. So there seems to be a bad interaction between the `16ul` passed to `Buffer.create` in `f` and the definition `Crypto.Symmetric.GF128.len = 16ul`.

I guess that applying `pow2_values` explicitly would solve the problem... 
Will try in the full file and report back.

**Comment by aseemr** [comment] 2017-04-10 09:02
Encoding verifies on the CI now, and the problem of hints not replaying is being tracked via #900 with a minimal repro. Closing this.

**Closed by aseemr** 2017-04-10 09:02 UTC
Labels: ci, Priority 1

**Comment by s-zanella** [comment] 2017-04-10 09:11
Just to add that this verifies in `hacl-star` CI. I don't think this verified as part of F*'s CI.

Most code in examples/low-level is now stale. We'll remove it in favour of hacl-star (see #928).
