### ISSUE TITLE
Unable to compile total implementation of foldl.

### ISSUE THREAD

**Issue by fmrl** [FStarLang/FStar#158] opened 2015-03-14 02:16 UTC
I'm attempting to write a total implementation of foldl. I based it on the definition of fold_left in lib/lists.fst. It does not compile and I am unsure of what is not correct:

```
module Module

   val tot_foldl: ('a -> 'b -> Tot 'a) -> 'a -> list 'b -> Tot 'a
   let rec tot_foldl f a l =
      match l with
        | [] -> a
        | hd::tl -> tot_foldl f (f a hd) tl

(*
issue-tot_foldl-1.fst(5,6-14,0): Patterns are incomplete
issue-tot_foldl-1.fst(7,41-7,43): Subtyping check failed; expected type _12742:(list 'b){(%[(f a hd); _12742] << %[a; l])}; got type (list 'b)
*)
```

**Comment by ad-l** [comment] 2015-03-14 02:27
Duplicate of #157

**Closed by ad-l** 2015-03-14 02:27 UTC
