### ISSUE TITLE
Order of universe abstraction is unpredictable

### ISSUE THREAD

**Issue by nikswamy** [FStarLang/FStar#883] opened 2017-03-03 21:54 UTC
Consider, in test.fst:

```
module Test
assume type dtuple3: a:Type 'ua -> b:(a -> Type 'ub) -> (x:a -> b x -> Type 'uc) -> Type0

module Test2
open Test
assume val __proj__Mkdtuple3__item___1 :
       #a:Type 'uu_319
     -> #b:(uu_:a -> Type 'uu_318)
     -> #c:(x:a -> uu_:(b x) -> Type 'uu_317)
     -> projectee:(dtuple3 u#'uu_319 u#'uu_318 u#'uu_317 a b c)
     -> a
````

```
$ fstar test.fst --dump_module Test2 --print_universes --print_implicits --explicit_deps

.\test.fst(4,7-4,12) (Warning): Support for more than one module in a file is deprecated
module Test2
assume val Test2.__proj__Mkdtuple3__item___1 <> : (#a:Type('uu_319) -> #b:(uu_:a@0 -> Tot Type('uu_318)) -> #c:(x:a@1 -> uu_:(b@1 x@0) -> Tot Type('uu_317)) -> projectee:(dtuple3<'uu_319, 'uu_318, 'uu_317> a@2 b@1 c@0) -> Tot a@3)
module Test2
assume val Test2.__proj__Mkdtuple3__item___1 <'uu___476, 'uu___477, 'uu___478> : (#a:Type('uu___478) -> #b:(uu_:a@0 -> Tot Type('uu___476)) -> #c:(x:a@1 -> uu_:(b@1 x@0) -> Tot Type('uu___477)) -> projectee:(dtuple3<'uu___478, 'uu___476, 'uu___477> a@2 b@1 c@0) -> Tot a@3)
All verification conditions discharged successfully
```

Notice, the order of abstracted variables is different than the syntactic order of their occurrence in the type.

**Comment by kyoDralliam** [comment] 2017-03-06 10:08
On which branch are you working ? I cannot reproduce it on current master... (commit=52145e369)

**Comment by aseemr** [comment] 2018-08-08 11:33
The order seems fine in the current master. Closing the issue.

**Closed by aseemr** 2018-08-08 11:33 UTC
