### ISSUE TITLE
F* chokes on inductive relation parameterized by another relation

### ISSUE THREAD

**Issue by catalin-hritcu** [FStarLang/FStar#575] opened 2016-07-12 19:53 UTC
Seems that F\* now has troubles defining simple inductive relations like reflexive transitive closure. Here's an even more simplified example that causes F\* to loop forever:

```
type relation = int -> Type

type multi (r:relation) : int -> Type =
| Multi_step : x:int -> r x -> multi r x
```

This seems like a regression, I'm quite sure this used to work well a while back.

[Update 2016-10-12] This no longer loops, but without Nik's `--__temp_no_proj Bug575` workaround the error message for this is now:

```
[hritcu@detained bug-reports]$ fstar.exe bug575.fst
Error: Unexpected error; please file a bug report, ideally with a minimized version of the source program that triggered the error.
Failure("k=(r:Bug575.relation -> uu___:Prims.int -> projectee:(Bug575.multi r@1 uu___@0) -> Tot (?39737 r@2 uu___@1 projectee@0))\nxs=r, uu___, projectee\nargs=r uu___ projectee x\nIll-formed substitutution")
```

**Comment by catalin-hritcu** [comment] 2016-07-12 20:11
This blocks me from porting stlc-norm to universes.
https://github.com/yforster/stlc-norm

**Comment by s-zanella** [comment] 2016-07-12 21:40
The definition of `multi` in the simplified example works when inlining `relation`:
```OCaml
type multi (r:int -> Type) : int -> Type =
| Multi_step : x:int -> r x -> multi r x
```
I don't know if you could work around the issue as easily in stlc-norm.

**Comment by nikswamy** [comment] 2016-07-13 04:40
Sigh. 

An ugly workaround: ` --__temp_no_proj ModuleA`. 

Investigating further

**Comment by catalin-hritcu** [comment] 2016-07-13 06:18
Thanks for the workarounds. It was indeed enough to just inline `relation` to keep going on stlc-norm.

**Comment by catalin-hritcu** [comment] 2016-08-09 15:55
This no longer loops, but now gives an unexpected error:
```
[hritcu@detained bug-reports]$ fstar.exe bug575.fst
Error: Unexpected error; please file a bug report, ideally with a minimized version of the source program that triggered the error.
Failure("k=(r:Bug575.relation -> uu___:Prims.int -> projectee:((Bug575.multi r@1) uu___@0) -> Tot (?32731 r@2 uu___@1 projectee@0))\nxs=r, uu___, projectee\nargs=r uu___ projectee x\nIll-formed substitutution")
./bug575.fst(3,28-7,42): Z3 provided a counterexample, but, unfortunately, F* could not translate it back to something meaningful
./bug575.fst(7,42-11,40): Z3 provided a counterexample, but, unfortunately, F* could not translate it back to something meaningful
Error: 2 errors were reported (see above)
```
Moreover, Santiago's workaround of inlining relation no longer works:
```
hritcu@detained bug-reports]$ fstar.exe bug575.fst
./bug575.fst(3,28-7,42): Z3 provided a counterexample, but, unfortunately, F* could not translate it back to something meaningful
Error: 1 errors were reported (see above)
```
Finally, Nik's workaround doesn't seem to fix this either:
```
[hritcu@detained bug-reports]$ fstar.exe bug575.fst --__temp_no_proj Bug575 
./bug575.fst(3,28-7,42): Z3 provided a counterexample, but, unfortunately, F* could not translate it back to something meaningful
./bug575.fst(7,42-11,40): Z3 provided a counterexample, but, unfortunately, F* could not translate it back to something meaningful
Error: 2 errors were reported (see above)
```

**Comment by nikswamy** [comment] 2016-08-09 16:08
1. You need my workaround `--__temp_no_proj Bug575`

2. Then, the failures you see are real failures that come from F* being unable to prove that these types have equality. The error message is terrible, but @aseemr is working on improving it. To indicate that you don't want equality for these types, tag them with the `noeq` qualifier. See the updated bug575.fst

**Comment by kyoDralliam** [comment] 2016-12-10 07:05
I have the impression that the origin of the problem is in the dependent pattern matching rather than the projectors themselves, i.e. even with `--__temp_no_proj` the following code fails 
```
let is_Multi_step r x (projectee : multi r x) =
  match projectee with
	  | Multi_step _ _  -> true
	  | _  -> false
```
with the usual 
`Failure("k=(r:relation -> x:((fun r -> (int $$ Tot Type(?104706))) r@0) -> projectee:(multi r@1 x@0) -> Tot (?104735 r@2 x@1 projectee@0))\nxs=r, x, projectee\nargs=r x projectee uu___\nIll-formed substitutution")`

**Comment by ad-l** [comment] 2017-03-29 13:21
@nikswamy any update on this bug? We would like to get rid of the "temporary" no-proj...

**Comment by nikswamy** [comment] 2017-04-09 15:38
worked a bit more on it 11 days ago, tightening the repro a bit, but no resolution yet

**Comment by kyoDralliam** [comment] 2017-04-12 13:43
Yet another (quite minimal) example : 
```
let rel (a:Type0) = a -> Type0

type free_reflexive (a:Type0) (r:rel a) : a -> Type0 =
  | FRReturn : x:a -> r x -> free_reflexive a r x
```

From some debugging with @shaolintl, it seems that the comment to the function `solve_both_pats` is slightly incorrect : 
```
              //(U1:k1) xs =?= (U2:k2) ys
              //    where k1 = bs -> k1' bs
              //          k2 = cs -> k2' cs
              //zs = xs intersect ys, (U:k_u) fresh
              //     where k_u = ds -> k_u' ds
              //U1 = \x1 x2. U zs
              //U2 = \y1 y2 y3. U zs
              //sub probs:
              //k1' xs =?= k2' ys
              //k_u zs =?= k1' xs   (an optimization drops this case when for k1'=Type _ \/ k2'=Type)
```

It may happen that k1 or k2 contains unification variable themselves and don't have "enough" binders wrt their respective arguments...

**Comment by kyoDralliam** [comment] 2017-04-13 09:03
...My previous comment seems slightly wrong, it may happen that `k` is of the valid arrow form only after substituting the first argument (consider the type `k = x:Type -> x` with arguments `(nat -> Type) 5`). Is there any way in the compiler to do this kind of flex-rigid problem interleaved with the subtitution of arguments ?

Also The problem disappear if you inline the definition of `rel` in the previous example so maybe I'm not debugging the right problem.

**Comment by mtzguido** [comment] 2018-09-18 15:06
Did a few tries and eveything seems to work now... will do some more intensive testing before closing.

**Closed** 2018-10-08 05:54 UTC
Labels: kind/bug
