### ISSUE TITLE
Unexpected output from Z3; Wrong number of arguments passed to function

### ISSUE THREAD

**Issue by catalin-hritcu** [FStarLang/FStar#1150] opened 2017-07-25 14:42 UTC
Didn't see this kind of SMT encoding problems in a long while, but they are back:
```
let positive' (s:int) : Type0 = s > 0
let positive : p:(int->Type0){p 42} = positive'

assume val witness : p:(int -> Type) -> Pure unit (requires (p 43)) (ensures (fun _ -> True))

val foo : unit -> Tot unit
let foo () = witness positive
```
Output:
```
[hritcu@resurrected pub]$ fstar.exe --log_queries examples/bug-reports/bug.fst                                         (git)-[master] 
./examples/bug-reports/bug.fst(0,0-0,0): (Warning) Bug: Unexpected output from Z3: (error "line 43734 column 26: Wrong number of arguments (1) passed to function (declare-fun Bug.positive () Term)")

./examples/bug-reports/bug.fst(0,0-0,0): (Warning) Bug: Unexpected output from Z3: (error "line 43770 column 26: Wrong number of arguments (1) passed to function (declare-fun Bug.positive () Term)")

./examples/bug-reports/bug.fst(0,0-0,0): (Warning) Bug: Unexpected output from Z3: (error "line 43806 column 26: Wrong number of arguments (1) passed to function (declare-fun Bug.positive () Term)")

./examples/bug-reports/bug.fst(0,0-0,0): (Warning) Bug: Unexpected output from Z3: (error "line 43842 column 26: Wrong number of arguments (1) passed to function (declare-fun Bug.positive () Term)")

./examples/bug-reports/bug.fst(0,0-0,0): (Warning) Bug: Unexpected output from Z3: (error "line 43878 column 26: Wrong number of arguments (1) passed to function (declare-fun Bug.positive () Term)")

./examples/bug-reports/bug.fst(9,0-9,29): (Error) Unknown assertion failed
Verified module: Bug (365 milliseconds)
1 error was reported (see above)
```

**Comment by markulf** [comment] 2017-09-18 12:36
The work around for this seems to be 

```
et positive' (s:int) : Type0 = s > 0
let positive () : p:(int->Type0){p 42} = positive'

assume val witness : p:(int -> Type) -> Pure unit (requires (p 43)) (ensures (fun _ -> True))

val foo : unit -> Tot unit
let foo () = witness ( positive () )

**Comment by markulf** [comment] 2017-09-18 12:37
@kyoDralliam and I ran into this issue when using monotonicity in MAC: https://github.com/FStarLang/FStar/blob/tuto_ex12b_RPC_no_axiom/doc/tutorial/code/solutions/Ex12.MAC.fst#L63

**Comment by nikswamy** [comment] 2017-10-13 20:23
Aseem, you've fixed many of these kinds of issues before. Care to take a look at this one?

**Comment by aseemr** [comment] 2017-10-23 09:40
The problem is that F* thinks the function `positive` is a zero-arity function, and then encodes it to Z3 as such. Later when it encodes `witness positive`, it has to prove the precondition `positive 42`, at which point Z3 complains about applying a zero-arity function.

The SMT encoding should descend under the return refinement type to see that `positive` has a function type, and then encode it as such.

**Comment by aseemr** [comment] 2017-10-23 10:26
Fixed in the commit https://github.com/FStarLang/FStar/commit/b439b3b6c77e956638edf80916231010267d3265.

**Closed by aseemr** 2017-10-23 10:26 UTC
Labels: component/smtencoding, kind/bug
