### ISSUE TITLE
Incompatible version for unification variable

### ISSUE THREAD

**Issue by jaybosamiya** [FStarLang/FStar#1319] opened 2017-10-23 21:31 UTC
Minimum example code:
```
module Temp

let foo x l =
  match l with
  | [] -> x                      // this should obviously be [x] instead for correct code
  | hd :: tl -> x :: l
```

On release version:
```
$ fstar --version # Release
F* 0.9.5.0
platform=Linux_x86_64
compiler=OCaml 4.05.0
date=2017-08-23T11:19:43-07:00
commit=fa9b1fd

$ fstar Temp.fst
Normalization failed with error Failure("Incompatible version for unification variable: current version is 477.1734; got version 477.1736")
Unexpected error; please file a bug report, ideally with a minimized version of the source program that triggered the error.
Failure("Incompatible version for unification variable: current version is 477.1734; got version 477.1736")
```

On latest docker image:
```
$ fstar --version # Latest docker image
F* 0.9.5.0
platform=Linux_x86_64
compiler=OCaml 4.04.2
date=2017-10-23T20:22:34+00:00
commit=512b435

$ fstar Temp.fst
Normalization failed with error Failure("Incompatible version for unification variable: current version is 518.1848; got version 518.1850")
Unexpected error; please file a bug report, ideally with a minimized version of the source program that triggered the error.
Failure("Incompatible version for unification variable: current version is 518.1848; got version 518.1850")
```

Expected error: Should give a type error since clearly `x` and `x :: l` are incompatible

**Comment by mtzguido** [comment] 2017-10-23 22:33
This might be related to generalization, as the following fails with the correct error:
```
module Temp

val foo : #a:Type -> a -> list a -> list a
let foo #a x l =
  match l with
  | [] -> x                      // this should obviously be [x] instead for correct code
  | hd :: tl -> x :: l
```
Probably the invariant-breaking uvars cause the mismatch, but just guessing.

**Comment by nikswamy** [comment] 2017-10-24 21:01
Here's another one I stumbled on today

```
module Bug1319
let map_rev (f : 'a -> 'b) (l : list 'a) : list 'b =
  let rec aux l acc = // (l:list 'a) (acc:list 'b) = //NS: weird, this needs an annotation to type-check in F*
   match l with 
   | [] -> acc 
   | x :: xs -> aux xs (f x :: acc)
   in  aux l []
```

```
Normalization failed with error Failure("Incompatible version for unification variable: current version is 832.332; got version 832.334")
Unexpected error; please file a bug report, ideally with a minimized version of the source program that triggered the error.
Normalization failed with error Failure("Incompatible version for unification variable: current version is 832.332; got version 832.334")
Unexpected error; please file a bug report, ideally with a minimized version of the source program that triggered the error.
```

**Comment by nikswamy** [comment] 2017-11-17 05:22
Several more reports of these recently ... I'm pushing it up my priority list and looking into it now

**Comment by nikswamy** [comment] 2017-11-17 05:33
minimizing further:

```
module Test
assume val f: #a:Type -> a -> a -> unit
let g x l = f x (Some x)
```

**Comment by nikswamy** [comment] 2017-11-17 16:46
The problem arises because F* tries to generate an error report about a failed unification after blowing away the union find graph used in that problem. The fix was a one liner to permute the generation of the error message and the graph destruction.

@mtzguido does this solve your problem?

Still, I see the fix as a bit of a band-aid. There still seem to be some code paths where backtracking points in the unification procedure are "lost". i.e., when marking a new transaction, I expect the continuation to always pass through either the rollback or the commit of the transaction, and this does not seem to be the case in this error path.

So, although the symptoms reported in this issue are no longer reproducible, I'm not yet closing the issue.

**Comment by nikswamy** [comment] 2017-11-17 16:46
Note, my Bug1319 example still fails to type-check without an annotation, but does not crash any more.

**Comment by mtzguido** [comment] 2017-11-18 21:07
I haven't seen it again, but maybe just coincidentally since I was in a weird local state when it happened. I'll report here if I run into it again!

**Comment by mtzguido** [comment] 2017-11-18 21:17
This also seems to have partially fixed #1256 part 2 (unification still fails, but not with this error)

**Comment by theolaurent** [comment] 2018-06-06 14:07
Hi, I got the same crash with a different program.
The minimized version is probably trying to do stupid stuff, but anyway.
```
type foo a =
  | Foo : (b:Type -> foo b) -> foo a

let rec f (t : option 'a) = match t with
  | Some b -> Foo (fun _ -> f b)
  | _ -> admit ()
```
It goes away with various modifications..

**Comment by nikswamy** [comment] 2018-06-14 03:54
Here's another example from @BarryBo (minimized)

```
module Test
assume val err (a:Type0) : Type0
assume val return (#a:Type) (x:a) : err a
assume val bind (#a:Type) (#b:Type) (f:err a) (g: a -> Tot (err b)) : Tot (err b)

assume val conv (x:int) : y:nat{y === x} //without the refinement on the result type here everything is fine

let test (x: err (int * unit)) : Tot (err (nat * unit))
= bind (x) (fun bu ->
  return (conv (fst bu), snd bu))
```

**Comment by lastland** [comment] 2018-06-15 22:18
Another example (might not be minimal):
```
module Examples

let n_reg_t : pos = 2

type reg_t = n:nat{n < n_reg_t}

let n_regtype (_: reg_t) : n:nat{0 < n} = 16

type regtyp (t:reg_t) = n:nat{n < n_regtype t}

let regval (_:reg_t) : Type0 = int

type regmap = t:reg_t -> regtyp t -> regval t

noeq type operand 'val 'op = {
  eval_operand   : 'op -> regmap -> 'val
}

let operandReg64 : operand int (regtyp 0) = {
  eval_operand  = (fun op regs -> regs op ) // types don't really match here
}
```
Error msg:
```
Unexpected error; please file a bug report, ideally with a minimized version of the source program that triggered the error.
Failure("Incompatible version for unification variable: current version is 619.13; got version 619.14")
```
It is worth noticing that this program is wrong, fixing it by replace the last part with
```
let operandReg64 : operand int (regtyp 0) = {
  eval_operand  = (fun op regs -> regs 0 op)
}
```
Then F* compiles it with no problem.

**Comment by lastland** [comment] 2018-06-15 22:19
And making the first parameter of `regmap` implicit would also solve the problem.

**Comment by mtzguido** [comment] 2018-06-16 01:15
Found another place where rolling back wasn't quite OK, and all of these now go through. Merging to master soon along with all the regression tests. I'm still not sure everything is peachy, so maybe we should leave it open?

**Comment by nikswamy** [comment] 2020-05-04 04:20
Looks like all of these go through properly now. Closing

**Closed by nikswamy** 2020-05-04 04:20 UTC
Labels: component/inference, component/typechecker, kind/bug, kind/crash, milestone/everest-v1
