### ISSUE TITLE
Type classes and higher kinded types

### ISSUE THREAD

**Issue by theolaurent** [FStarLang/FStar#1486] opened 2018-06-30 09:59 UTC
I might be mistaken, but I think [typeclasses](https://github.com/FStarLang/FStar/issues/852) don't resolve with higher kinded types, e.g. for functors:
```
noeq type functor f = {
  fmap  : (#a:Type) -> (#b:Type) -> (a -> b) -> f a -> f b ;
}

%splice[fmap] (mk_class (`%functor))

(* Two concrete instances *)
[@instance] let functor_list : functor list = { fmap = List.Tot.map }
[@instance] let functor_id : functor id = { fmap = fun #_ #_ f a -> f a }

let fmap' (#f:Type -> Type) [| functor f |] (#a:Type) (#b:Type) (g:a -> b) (x: f a) : f b = fmap g x
```
gives me `user tactic failed: Typeclass resolution failed`

**Comment by theolaurent** [comment] 2018-06-30 10:09
(a simpler, more concrete `fmap` application like `let _ = fmap (fun x -> x + 1) [1 ; 2 ; 3]` doesn't work either)

**Comment by mtzguido** [comment] 2018-07-01 07:14
Thanks Théo, this is indeed inconvenient. What happens (taking your last example) is that the unifier is resolving `f` to be `fun _ -> list int`, instead of just `list`. Which sort of works.. but it's very inconvenient in this case. I'll try to bang on it and make it unify to the simpler solution.

By the way, as you found, typeclasses are *very* green. I'm extremely happy to take reports but think twice before switching your development to use them :).

**Comment by theolaurent** [comment] 2018-07-01 07:41
Yes of course. No worries, I just like to try things out, and I am super enthusiast about typeclasses.
Thank you for working on those !

**Comment by mtzguido** [comment] 2018-07-01 20:06
Tried to solve this this morning without much luck, making a note to remember the details. The crux of the problem is the unifier getting a problem

```
?u int = list int
```

and, since the LHS is a quasi-pattern, it sets `?u` to `fun _ -> list int`. We thought of two heuristics to make it solve `?u := list`.
1) Try to structurally unify flex-rigid patterns first, and fallback to the current setup if not. This is not type-sound, as we might (and do) get things like `list ?u1 = ?u2 n`, but `?u2 : int -> Type` (not `Type -> Type`) and similar for `?u1` (`int` vs `Type`).
2) If we get `?u e1..en =? h d1..dn`, and setting `?u := d` makes the equality trivial, take that solution. That makes your `list int` example succeed but not the other higher-order one (since the problem is more like `f b ?= ?u1 ?u2`)

Some eta-reduction could also fix the `list int` one, but it might hinder expressiveness. Unsure if it's sound too for the reasons in 1).

**Comment by theolaurent** [comment] 2018-07-02 17:13
[Ziliani and Sozeau](https://www.irif.fr/~sozeau/research/publications/drafts/unification-jfp.pdf) use what they call _first order approximation_ to tackle problems of the form `?u1 ?u2 ~ t1 t2` (basically assigning `t1` to `?u1` and `t2` to `?u2`).
Don't know if it would fit well in F*'s unification algorithm though.

**Comment by theolaurent** [comment] 2018-07-02 17:46
For the sake of argument, [De Moura et al.](http://www.contrib.andrew.cmu.edu/~avigad/Papers/constr.pdf) don't use that approximation, and benefit from backtracking to try to assign `λ _ . t1 t2` to `u1` and then if fails, they try `t1 ~ u1` (so called _imitation step_).

**Comment by nikswamy** [comment] 2018-07-26 21:32
A potentially related problem when trying to typecheck the following code in the `nik_pat` branch.


```
module Pat
#set-options "--__temp_no_proj Pat"
noeq type t (f:bool -> Type0) :Type0 =
  | C1: x:f false -> t f

#set-options "--debug Pat --debug_level Rel --print_implicits --print_bound_var_types"
let foo (f:bool -> Type0) (x:t f) :unit =
  match x with
  | C1 y -> ()
```
We end up elaborating the pattern as

` (Pat.C1 #(fun uu___#299:Prims.bool -> (?14 $$ (residual) Prims.Tot Type)) uu___#286)`

 at type 

`(Pat.t (fun uu___#301:Prims.bool -> (?14 $$ (residual) Prims.Tot Type)))`

From which point it is hopeless to unify this type with the expected type `t f`

The problem comes from trying to solve

```
(f#259:(uu___#261:Prims.bool -> Tot Type), x#260:(Pat.t f#259) |- ?10 : Type)  
		<:
	(* pat_dot_term *)
(f#259:(uu___#261:Prims.bool -> Tot Type), x#260:(Pat.t f#259) |- ?9 : (uu___#294:Prims.bool -> Tot Type)) false
};
```

by introducing a new unification variable `?14:Type` and solving

```
Solving 13022: with TERM 10 ?14, TERM 9 (fun uu___#300:Prims.bool -> (?14 $$ (residual) Prims.Tot Type))
```

Some smarter first-order heuristic here would work better.

**Comment by mtzguido** [comment] 2018-07-30 18:11
I thin I just found a very interesting facet of this bug! Was filing separately, but pretty convinced it's the same unifier issue.

This fails, for no apparent reason:
```f#
let unthunk (#a:Type) (#wpa : pure_wp a) ($f : (unit -> PURE a wpa)) : PURE a wpa = f ()
```
```
Par.fst(3,84-3,88): (Error 19) assertion failed (see also /home/guido/r/fstar/ulib/prims.fst(206,97-206,103))
```

The VC is this:
```f#
(*could not prove post-condition*)
forall (p: Prims.pure_post a).
  wpa p ==>
  (forall (b: Prims.unit).
      wpa (fun bind_result_1 ->
            bind_result_1 == f () ==>
            (forall (return_val: a). return_val == bind_result_1 ==> p return_val)))
```
Which is equivalent to:
```f#
(*could not prove post-condition*)
forall (p: Prims.pure_post a).
  wpa p ==>
  (forall (b: Prims.unit).
      wpa (fun _ -> p (f ())))
```
So it seems like pretty much the same thing, the wp of the body was inferred to some overly-specialized thing instead of just `wpa`. Can't work around it, as far as I can tell.

**Comment by aseemr** [comment] 2018-07-31 04:51
Ugh, this last example is annoying. I wonder though if it is a unification issue, I don't see any unification variables, implicits etc. This could just be a typechecker issue, but not sure, will have to see more.

I also tried to encode monotonicity of wps to Z3, but even then this doesn't go through.

**Comment by aseemr** [comment] 2018-07-31 10:46
It is indeed monotonicity, this verifies:

```
assume Monotonicity: forall (a:Type) (wp:pure_wp a) (p1 p2:pure_post a). (forall (x:a). (p1 x ==> p2 x)) ==> (wp p1 ==> wp p2)

let unthunk (#a:Type) (#wpa : pure_wp a) ($f : (unit -> PURE a wpa)) : PURE a wpa = f ()
```

But it is unfortunate that this example requires an application of monotonicity. The thing is: we compute `PURE a wpa` as the type of the application but then insert a `bind` with `return_wp (f ())`, which changes the postcondition and then needs monotonicity.

**Comment by aseemr** [comment] 2018-07-31 10:56
For example, if it is a `STATE` function, we don't need monotonicity, since the type checker won't insert a `return`.

**Closed** 2022-04-25 19:59 UTC
Labels: kind/bug, component/tactics, component/unifier, milestone/everest-v1
