### ISSUE TITLE
Big differences in performance and (un)predictability on similar requests

### ISSUE THREAD

**Issue by SimonForest** [FStarLang/FStar#281] opened 2015-07-20 10:27 UTC
I was investigating the problems I encountered when doing some proofs about substitution in micro-fstar.fst. I found a strange behaviour with the following code in interactive mode :

```
(*--build-config
    options:--z3timeout 20 --max_fuel 8 --max_ifuel 6 --initial_fuel 4 --initial_ifuel 2;
    other-files:../../../lib/classical.fst ../../../lib/ext.fst ../../../lib/constr.fst
  --*)
module Test

(* Test of substitution on big terms *)

open Classical

type exp =
| EVar : nat -> exp
| EApp : exp -> exp -> exp 
| ELam : exp -> exp 

type sub = nat -> Tot (exp)

type renaming (s:sub) = (forall x. is_EVar (s x))

val is_renaming : s:sub -> Tot nat
let is_renaming s =
  if (excluded_middle (renaming s)) then
    0
  else 
    1

val is_evar : exp -> Tot nat
let is_evar e = if (is_EVar e) then 0 else 1

val sub_einc : nat -> Tot (exp)
let sub_einc x = EVar (x+1)

val esubst : s:sub -> e:exp -> Tot (r:exp{renaming s /\ is_EVar e ==> is_EVar r})
(decreases %[is_evar e; is_renaming s; 1;e])
val sub_elam : s:sub -> Tot (r:sub{renaming s ==> renaming r})
(decreases %[1;is_renaming s; 0; EVar 0])

let rec sub_elam s =
let res : sub = fun x ->
if x = 0 then EVar 0 else esubst (sub_einc) (s (x-1))
in res
and esubst s e = 
match e with
| EVar x -> s x
| EApp e1 e2 -> EApp (esubst s e1) (esubst s e2)
| ELam ebody -> ELam (esubst (sub_elam s) ebody)

let eesh = (esubst sub_einc)

let test f = EApp (EApp (EApp (eesh (eesh (eesh f))) (EVar 2)) (EVar 1)) (EVar 0)

val lemma : s:sub -> e:exp -> Lemma (esubst (sub_elam s) (eesh e) = eesh (esubst s e))
let lemma s e = admit()

(* Version without type : succeeds after a random time or fails *)
let plouf0 s f =lemma (sub_elam (sub_elam s)) (eesh (eesh f));
                lemma (sub_elam s) (eesh f);
                lemma (s) (f);
                assert(esubst (sub_elam (sub_elam (sub_elam s))) (test f) = test (esubst s f))

(* Version with type : succeeds after ~2-6sec *)
val plouf1 : s:sub -> f:exp -> Tot unit
let plouf1 s f =lemma (sub_elam (sub_elam s)) (eesh (eesh f));
                lemma (sub_elam s) (eesh f);
                lemma (s) (f);
                assert(esubst (sub_elam (sub_elam (sub_elam s))) (test f) = test (esubst s f))

(* Version with 'Lemma' instead of 'assert' : succeeds after a random time or fails, but mostly fails *)
val plouf2 : s:sub -> f :exp -> Lemma (esubst (sub_elam (sub_elam (sub_elam s))) (test f) = test (esubst s f))
let plouf2 s f =lemma (sub_elam (sub_elam s)) (eesh (eesh f));
                lemma (sub_elam s) (eesh f);
                lemma (s) (f)
```

I guess the behaviour of Fstar when checking plouf0, plouf1 and plouf2 should be the same. Especially between plouf1 and plouf2 : when something can be checked easily with an assert, it should be as easy to check it as part of a Lemma. The difference between plouf0 and plouf1 is also disturbing, since the type inference to do is really easy.

**Comment by catalin-hritcu** [comment] 2015-07-20 15:31
We just discovered that commenting out `plouf0` and `plouf1` makes `plouf2` work right away. Keeping any of them makes `plouf2` fail after ~60 seconds (most of the time at least).

This very strange behavior is consistent with what Simon was seeing when good proofs were breaking when adding unrelated things higher in the same file.

**Comment by jkzinzindohoue** [comment] 2015-07-20 15:52
Does it improve things if you put  "#reset-options" between the different
functions ? I think it cleans the SMT solver's environment.

2015-07-20 16:31 GMT+01:00 Catalin Hritcu <notifications@github.com>:

**Comment by catalin-hritcu** [comment] 2015-07-20 15:56
Thanks for the suggestion. "#reset-options" doesn't seem to have an effect here.

We also tried with z3 trunk and it didn't change anything (although it worked well otherwise).

**Comment by nikswamy** [comment] 2015-07-21 05:09
Is this only in interactive mode?

Adding more total functions to your context may cause Z3 to try to reduce them. I'm surprised that it would in this case, but it may be possible. 

Have you tried marking plouf0 and plouf1 as opaque?

Another thing you might try is to run Z3 with the smt.qi.profile option set. It will tell you which quantifiers are firing too much. But, understanding its output takes some practice.

**Comment by catalin-hritcu** [comment] 2015-07-21 06:47
The problem happens from the command line too, not just in the interactive.

Marking `plouf1` and `plouf2` opaque (and removing `plouf0` completely) doesn't change much. But you're right we should always try `opaque` before complaining about SMT behavior, sorry. Should do that quite extensively in micro-fstar.fst, as it might help and it will definitely not harm. I see that it's on Simon's todo list, should probably bump the priority on that a bit though :)

I'll try the `smt.qi.profile` option and report back. Thank you for the advice.

**Comment by catalin-hritcu** [comment] 2015-07-21 07:38
Bad news. I'm no longer able to reproduce the claim that "commenting out plouf0 and plouf1 makes plouf2 work right away". It was based on only a few experiments, and things seem completely random now. No causality, just randomness.

**Comment by catalin-hritcu** [comment] 2015-07-21 08:51
Started playing with `smt.qi.profile`. How does one interpret output like this though? What do the various columns mean?
```
[quantifier_instances]      k!396 :    320 :   3 : 4
[quantifier_instances]      k!386 :    320 :   3 : 4
[quantifier_instances]      k!297 :  46751 :  20 : 21
[quantifier_instances]      k!289 :  40490 :  20 : 21
[quantifier_instances]      k!273 :  16514 :  20 : 21
[quantifier_instances]      k!265 :  14935 :  20 : 21
[quantifier_instances]       k!53 :  77462 :  19 : 20
[quantifier_instances]       k!49 : 268096 :  20 : 21
[quantifier_instances]       k!45 : 171225 :  20 : 21
```

**Comment by catalin-hritcu** [comment] 2015-07-21 09:10
Created two gists with the files:
`plouf2-fail.smt2`: https://gist.github.com/catalin-hritcu/db064f001cd865548ef8
`plouf2-fail.profile`: https://gist.github.com/catalin-hritcu/0d15fcd8d412c558cdb3

I've obtained the `profile` file as follows:
```
time z3 -t:20000 plouf2-fail.smt2 &> plouf2-fail.profile
```
This works because `plouf2-fail.smt2` contains `(set-option :smt.qi.profile true)`.

Also found the z3 code that produces the `[quantifier_instances]` output:
https://github.com/Z3Prover/z3/blob/7f6ef0b6c0813f2e9e8f993d45722c0e5b99e152/src/smt/smt_quantifier.cpp#L73
and it's quite readable. It seems that the number after `k!` is the line of the quantifier pattern, while the column afterwards is the number of times this pattern was triggered. It seems that for the last query (the failing one) various quantifiers are triggered hundreds of thousands of times, but still need to figure out what that means.

**Comment by nikswamy** [comment] 2015-07-21 17:40
Here's a decent rule of thumb in reading this output. 

Ignore all the quantifiers that occur in encodings of the F\* libraries. E.g., k!49 is probably something from Prims---ignore the fact that it has 200K+ instantiations. 

Focus instead on quantifiers that appear in the encoding of your module ... the .smt2 file should have comments in it showing where your module is encoded. 

Another tool you might use is the Z3AxiomProfiler. You can get that by installing [https://vcc.codeplex.com/], and adding its binary directory to your path. Then, run z3 with TRACE=true, and feed the generated z3.log to Z3AxiomProfiler. This should then show you even more detail than the qi.profile. 

Figuring out how to make use of all of this is Z3 black art. I'm not necessarily suggesting that you dive into this. Just recording it here so that you know it exists.

**Comment by SimonForest** [comment] 2015-07-22 17:59
I did another try with plouf4, with raw encoding of the wp : 
```
val plouf4 : s:sub -> f:exp -> PURE unit (fun (p:PurePost unit) -> (esubst (sub_elam (sub_elam (sub_elam s))) (test f) = test (esubst s f)) ==> p ()) (fun (p:PurePost unit) -> (esubst (sub_elam (sub_elam (sub_elam s))) (test f) = test (esubst s f)) ==> p () )
let plouf4 s f =lemma (sub_elam (sub_elam s)) (eesh (eesh f));
                lemma (sub_elam s) (eesh f);
                lemma (s) (f)
```

and it worked quite fast. Faster than plouf1.

And the z3 queries sent by plouf4 are almost the same than the queries sent by plouf2, when the additional queries with different fuel (because of failure of the first query) are removed from plouf2.smt2.

I have found two relevant differences but only one seems critical regarding the success of the query :
 in plouf2, at some point, there is this code : 
```smt2
; <Start encoding Test.plouf2>
;;;;;;;;;;;;;;;;Uninterpreted function symbol for impure function
(declare-fun Test.plouf2 (Term Term) Term)
;;;;;;;;;;;;;;;;Uninterpreted name for impure function
(declare-fun Test.plouf2@tok () Term)

; </end encoding Test.plouf2>
```

whereas, in plouf4.smt2, there is this code : 
```smt2
; <Start encoding Test.plouf4>
(declare-fun Test.plouf4 (Term Term) Term)
(declare-fun Typ_refine_1448 (Term Term) Type)
(assert (forall ((@x0 Term) (@x1 Term))
 (! (HasKind (Typ_refine_1448 @x0
@x1)
Kind_type)
  
:pattern ((HasKind (Typ_refine_1448 @x0
@x1)
Kind_type)))))
;;;;;;;;;;;;;;;;_2_8189:unit{(~ (((esubst (sub_elam (sub_elam (sub_elam s))) (test f)) = (test (esubst s f))) ==> (~ (() = _2_8189))))}
(assert (forall ((@u0 Fuel) (@x1 Term) (@x2 Term) (@x3 Term))
 (! (iff (HasType @x1
(Typ_refine_1448 @x2
@x3))
(and (HasType @x1
Prims.unit)
(not (implies (Valid (Prims.b2t (Prims.op_Equality Test.exp
(Test.esubst (Test.sub_elam (Test.sub_elam (Test.sub_elam @x3)))
(Test.test @x2))
(Test.test (Test.esubst @x3
@x2)))))
(not (Valid (Prims.b2t (Prims.op_Equality Prims.unit
Term_unit
@x1))))))))
  
:pattern ((HasTypeFuel @u0
@x1
(Typ_refine_1448 @x2
@x3))))))
;;;;;;;;;;;;;;;;(s:sub -> f:exp -> PURE (unit))
(declare-fun Typ_fun_1450 () Type)
;;;;;;;;;;;;;;;;Typ_fun_1450 kinding
(assert (HasKind Typ_fun_1450
Kind_type))
;;;;;;;;;;;;;;;;pre-typing for functions
(assert (forall ((@u0 Fuel) (@x1 Term))
 (! (implies (HasType @x1
Typ_fun_1450)
(is-Typ_fun (PreType @x1)))
  
:pattern ((HasTypeFuel @u0
@x1
Typ_fun_1450)))))
;;;;;;;;;;;;;;;;Typ_fun_1450 interpretation
(assert (forall ((@u0 Fuel) (@x1 Term))
 (! (iff (HasType @x1
Typ_fun_1450)
(forall ((@x2 Term) (@x3 Term))
 (! (implies (and (HasType @x2
Test.sub@tok)
(HasType @x3
Test.exp))
(HasType (ApplyEE (ApplyEE @x1
@x2)
@x3)
(Typ_refine_1448 @x3
@x2)))
  
:pattern ((ApplyEE (ApplyEE @x1
@x2)
@x3)))))
  
:pattern ((HasTypeFuel @u0
@x1
Typ_fun_1450)))))
(declare-fun Test.plouf4@tok () Term)
;;;;;;;;;;;;;;;;fresh token
(assert (= 1453
(Term_constr_id Test.plouf4@tok)))
(assert (forall ((@x0 Term) (@x1 Term))
 (! (= (ApplyEE (ApplyEE Test.plouf4@tok
@x0)
@x1)
(Test.plouf4 @x0
@x1))
  
:pattern ((ApplyEE (ApplyEE Test.plouf4@tok
@x0)
@x1)))))
;;;;;;;;;;;;;;;;function token typing
(assert (HasType Test.plouf4@tok
Typ_fun_1450))
;;;;;;;;;;;;;;;;free var typing
(assert (forall ((@x0 Term) (@x1 Term))
 (! (implies (and (HasType @x0
Test.sub@tok)
(HasType @x1
Test.exp))
(HasType (Test.plouf4 @x0
@x1)
(Typ_refine_1448 @x1
@x0)))
  
:pattern ((Test.plouf4 @x0
@x1)))))

; </end encoding Test.plouf4>
```
if we remove this part from plouf4.smt2 to match the equivalent part of plouf2.smt2, the query fails as well. More precisely, removing the first assert makes the query fail : 
```smt2
(assert (forall ((@x0 Term) (@x1 Term))
 (! (HasKind (Typ_refine_1448 @x0
@x1)
Kind_type)
  
:pattern ((HasKind (Typ_refine_1448 @x0
@x1)
Kind_type)))))
```
So why is there a difference between the two functions here ? And why according to the comments plouf2 is considered as impure ?

There is another difference, that is not a big deal : 
in plouf2.smt2, at some point in the query of plouf2, there is this code : 
```smt2
(forall ((@x1 Term))
 (implies (and (HasType @x1
Prims.unit)
(Valid (Prims.b2t (Prims.op_Equality Test.exp
(Test.esubst (Test.sub_elam (Test.sub_elam (Test.sub_elam s___2_37)))
(Test.test f___2_38))
(Test.test (Test.esubst s___2_37
f___2_38))))))
(Valid (ApplyTE @a0
@x1))))
```
whereas in plouf4.smt2, there is this code : 
```smt2
(implies (Valid (Prims.b2t (Prims.op_Equality Test.exp
(Test.esubst (Test.sub_elam (Test.sub_elam (Test.sub_elam s___2_41)))
(Test.test f___2_42))
(Test.test (Test.esubst s___2_41
f___2_42)))))
(Valid (ApplyTE @a0
Term_unit)))
```

So a quantification over the expressions of type unit on one side, and a quantification just over () on the other side. I tried to change plouf2.smt2 to match the same style than plouf4.smt2 at this point but it still failed anyway.

And I have a question concerning one of the additional assert that plouf4 has : 
```smt2
(assert (forall ((@u0 Fuel) (@x1 Term) (@x2 Term) (@x3 Term))
 (! (iff (HasType @x1
(Typ_refine_1448 @x2
@x3))
(and (HasType @x1
Prims.unit)
(not (implies (Valid (Prims.b2t (Prims.op_Equality Test.exp
(Test.esubst (Test.sub_elam (Test.sub_elam (Test.sub_elam @x3)))
(Test.test @x2))
(Test.test (Test.esubst @x3
@x2)))))
(not (Valid (Prims.b2t (Prims.op_Equality Prims.unit
Term_unit
@x1))))))))
```

So if I understand correctly, it defines a type t1448 as : 
g |- x1 : (t1448 x2 x3) if and only if   not ( esubst (sub_elam (sub_elam (sub_elam x3))) (test x2) = test (esubst x3 x2) ==> (() <> x1))
which is logically equivalent to 
g |- x1 : (t1448 x2 x3) if and only if   (() = x ==> esubst (sub_elam (sub_elam (sub_elam x3))) (test x2) <> test (esubst x3 x2))

What is the use of this assert ? Why the final <> is not an = ? It makes no sense to me …

plouf4.smt2 : https://gist.github.com/SimonForest/71ae8aa01453281a6345
plouf2-reduced.smt2 : https://gist.github.com/SimonForest/7153371d32e05832d5c8

**Comment by nikswamy** [comment] 2015-07-23 03:56
To understand the encoding of `Typ_refine_1448`, I refer you to Section 9.3.2 of the tutorial [https://fstar-lang.org/tutorial/tutorial.html#sec-from-predicate-transformers-to-pre--and-post-conditions]

Roughly, what you have here is `~(P ==> Q)`. If you expand this out, you get `~(~P \/ Q)`, or `P /\ ~Q`. In this case,  `P=esubst (sub_elam (sub_elam (sub_elam x3))) (test x2) = test (esubst x3 x2)`
and `~Q= (x1=())`. Which is what you expect. 

The reason this kicks in is because we extract a post-condition from a WLP. See also `Prims.as_ensures`.

As for why `plouf2` is marked as impure---the comment is misleading. It's a lemma, so we never generate any equations for it. So, the handling is the same as what we do for impure functions. In this case, the generated comment would have been better if it said something like "no equations because it is a lemma which is always opaque".

**Comment by catalin-hritcu** [comment] 2015-07-23 07:26
Marking `plouf4` as opaque doesn't seem to break it. @SimonForest: can you see what changes in the SMT file when you do that?

**Comment by SimonForest** [comment] 2015-07-23 11:50
Oups my logical equivalence was false. It seems that I forgot the 'not'. Sorry.

And marking plouf4 as opaque does not seem to change **anything** in the queries. There is just two comments that get changed : 
without opaque : 
```
; Starting query at test.fst(53,23-85,0)
```
with opaque : 
```
; Starting query at test.fst(85,0-85,0)
```
Where (53,23-85,0) is the range of some comments between 'lemma' and 'plouf4'. So it does not seem relevant.

So the same equations are generated even with opaque in front of plouf4. Is this a bug ?

Anyway it is also weird that the head queries generated for the non-opaque version seems to help proving the lemma. More specifically, I saw that in these head queries, there are : 
```smt2
(assert (forall ((@u0 Fuel) (@x1 Term) (@x2 Term) (@x3 Term))
 (! (iff (HasType @x1
(Typ_refine_1448 @x2
@x3))
(and (HasType @x1
Prims.unit)
(not (implies (Valid (Prims.b2t (Prims.op_Equality Test.exp
(Test.esubst (Test.sub_elam (Test.sub_elam (Test.sub_elam @x3)))
(Test.test @x2))
(Test.test (Test.esubst @x3
@x2)))))
(not (Valid (Prims.b2t (Prims.op_Equality Prims.unit
Term_unit
@x1))))))))
  
:pattern ((HasTypeFuel @u0
@x1
(Typ_refine_1448 @x2
@x3))))))
```
so the same than we discussed before, which defines t1448, and this one :
```smt2
(assert (forall ((@x0 Term) (@x1 Term))
 (! (implies (and (HasType @x0
Test.sub@tok)
(HasType @x1
Test.exp))
(HasType (Test.plouf4 @x0
@x1)
(Typ_refine_1448 @x1
@x0)))
```
which tells us that applying an x0 of type sub and an x1 of type exp to plouf4 gives us a term 'plouf4 x0 x1' of type t1448, which gives us, by the definition of t1448 above the fact that ' plouf4 x0 x1 = () ==> the conclusion of plouf4, which is still not proved at this point ! '. So is it not possible for z3, when it tries to prove plouf4, to instantiate those two patterns and get directly the conclusion, shortcutting the proof ? It seems that plouf4 is not applied during the proof though. But z3 could get it applied by using patterns right ? So is it not dangerous ?

**Comment by SimonForest** [comment] 2015-07-23 12:16
But removing an element from the proof makes plouf4 fail. So it does not seem that there is shortcutting …

**Comment by vkanne-msft** [comment] 2016-07-05 23:04
@catalin-hritcu can you test this one as well ?

**Comment by catalin-hritcu** [comment] 2016-07-12 18:58
The 4 versions consistently finish in ~12-13s on my machine. This seems fixed, closing.
```
[hritcu@detained bug-reports]$ time fstar.exe bug281.fst
Verifying module: Bug281
All verification conditions discharged successfully
fstar.exe bug281.fst  12.29s user 0.06s system 99% cpu 12.357 total
[hritcu@detained bug-reports]$ 
[hritcu@detained bug-reports]$ time fstar.exe bug281.fst
Verifying module: Bug281
All verification conditions discharged successfully
fstar.exe bug281.fst  13.02s user 0.07s system 100% cpu 13.074 total
[hritcu@detained bug-reports]$ time fstar.exe bug281.fst
Verifying module: Bug281
All verification conditions discharged successfully
fstar.exe bug281.fst  12.61s user 0.09s system 99% cpu 12.707 total
```

**Closed by catalin-hritcu** 2016-07-12 18:58 UTC
Labels: bug, needs confirmation with --universes, proof-assistant
