### ISSUE TITLE
Encountered "Expected expression of type "Type0"; got expression ..." when checking simple modules

### ISSUE THREAD

**Issue by Axure** [FStarLang/FStar#1321] opened 2017-10-26 12:11 UTC
```
% fstar.exe --fstar_home ~/deps/fstar ~/Test.fst 
/home/zhenghu/deps/fstar/ulib/FStar.Pervasives.fst(219,3-219,21): (Warning) SMTPatT is deprecated; please just use SMTPat
/home/zhenghu/deps/fstar/ulib/FStar.Pervasives.fst(218,11-218,52): (Error) Expected expression of type "Type0"; got expression "fun uu___121794 ->
  forall (x:FStar.Pervasives.Native.option a). Prims.b2t (None? x) \/ Prims.b2t (Some? x)" of type "uu___121793:(*?u3*) _ a -> Prims.Tot Type0"
1 error was reported (see above)
```

What's in Test.fst is
```
module Test
```

If I comment out the problematic section, which is

```
//allowing inverting option without having to globally increase the fuel just for this
val invertOption : a:Type -> Lemma
  (requires True)
  (ensures (forall (x:option a). None? x \/ Some? x))
  [SMTPatT (option a)]
let invertOption a = allow_inversion (option a)
```

then the empty module seems to check.

I'm using the latest release (0.9.5) for Linux downloaded from this repo.

**Comment by mtzguido** [comment] 2017-10-26 12:14
Hi, I think this is caused by the fix to #57, but you shouldn't experience this if your compiler is consistent with prims.fst. Seems weird that the release doesn't work, let me try to reproduce.

**Comment by mtzguido** [comment] 2017-10-26 12:18
Couldn't repro... I think you're using a different F* binary, which has to be a newer one since this fix I mention was not in place for the v0.9.5.0 release. How are you running F*, and is it returning this version info?
```
$ ./bin/fstar.exe --version 
F* 0.9.5.0
platform=Linux_x86_64
compiler=OCaml 4.05.0
date=2017-08-23T11:19:43-07:00
commit=fa9b1fd
```

**Comment by mtzguido** [comment] 2017-10-26 12:29
(Also that warning about `SMTPatT` is just a week old)

**Comment by Axure** [comment] 2017-10-26 16:38
I found out that I have to specify the full path, e.g. '/home/zhenghu/deps/fstar/bin/fstar.exe', to call `fstar.exe`. In that way I also need not provide the `fstar_home`. I'm not sure about the reason.

I believe the distro containing the fstar.exe called with this command, and the distro containing the fstar_home in the command are the same. I tried both 0.9.5 and 0.9.4 (both downloaded here), though, with no success in both cases.

**Comment by mtzguido** [comment] 2017-10-26 16:55
I'm not sure I understand, but I think you're not running the appropriate executable. Can you show me the output of `which fstar.exe`?

**Comment by Axure** [comment] 2017-10-26 20:32
You are right. The output is: `/home/zhenghu/.opam/system/bin/fstar.exe`.

So I was actually running an (unsuccessful) installation by opam. It actually failed to install fstar, saying it was unable to find `fstarlib.cma`.

**Comment by mtzguido** [comment] 2017-10-26 22:03
I see! I think there were some problems with the opam package that should now be resolved, so you could try to reinstall it from there. Otherwise, be sure to provide absolute paths or using `./bin/fstar.exe` on your unpacked directory.

Closing since this seems resolved.

**Closed by mtzguido** 2017-10-26 22:03 UTC
