### ISSUE TITLE
Delta normalization in a tactic does not work inside effectful functions

### ISSUE THREAD

**Issue by tchajed** [FStarLang/FStar#1190] opened 2017-08-10 14:54 UTC
In the following example, `add_1` can be inlined into `add_2` but the same approach doesn't work for inlining inside a stateful function `create_add_1`. Furthermore, I actually want to inline a stateful function into another stateful function, as demonstrated in `create_and_set'`.

```fstar
module Inlining

open FStar.Tactics

open FStar.HyperStack
open FStar.HyperStack.ST
module U32 = FStar.UInt32

open FStar.Buffer

let add_1 (x:int) : int = x+1

// we want to inline add_1 into this function
let add_2 (x:int) : int = add_1 (add_1 x)

// we want to inline add_1 in this function
let create_add_1 (u:unit) : St unit =
  push_frame();
  let x = create 0ul (U32.uint_to_t (add_1 1)) in
  pop_frame();
  ()

let normalize (#t:Type) (x:t) : tactic unit =
  dup;;
  exact (quote x);;
  norm [Delta];;
  trefl

// add_2' is like add_2 but has add_1 inlined (printing verifies this)
let add_2' : int -> int = synth_by_tactic (normalize ((fun (x:int) -> add_1 (add_1 x))))

// normalizing has no effect
let create_add_1' : unit -> St unit = synth_by_tactic (normalize ((fun (u:unit) ->
             push_frame();
             let x = create 0ul (U32.uint_to_t (add_1 1)) in
             pop_frame();
             ()) <: unit -> St unit))

let set_to_1 (x: buffer U32.t{length x == 1}) =
  x.(0ul) <- 1ul

// we want to inline set_to_1 in this function
let create_and_set (u:unit) : St unit =
  push_frame();
  let x = create 0ul 1ul in
  set_to_1 x;
  pop_frame();
  ()

// normalizing has no effect
let create_and_set' : unit -> St unit =
  synth_by_tactic (normalize ((fun (u:unit) ->
    push_frame();
    let x = create 0ul 1ul in
    set_to_1 x;
    pop_frame();
    ()) <: unit -> St unit))
```

**Comment by mtzguido** [comment] 2017-08-10 17:07
Sigh, this smells of the normalizer switching its set of flags while running, which usually results in this kind of unexpected behaviours. In the last example, defining `let set_to_1 x : Tot unit = ()` also does not unfold, but some other examples such as:
```
let f x : St int = x + 42
let create_and_set' : unit -> St int =
  synth_by_tactic (normalize ((fun (u:unit) -> f 2) <: unit -> St int))
```
do unfold. I'll investigate, but is this blocking you? I could add a workaround if so. (A new `norm` flag, I suppose)

**Comment by tchajed** [comment] 2017-08-11 07:43
Yeah, what I wanted to experiment with using tactics was specifically inlining small, higher-order stateful functions.

**Comment by mtzguido** [comment] 2017-08-12 23:44
I think this is now fixed in my branch, it seems to be indeed that during normalization of effectful computations, `Delta` steps were explicitly removed. I do not know why, but all F* tests succeed without it. 

@kyod has run into this piece of code before, and I think @msprotz too: any clue why this steps change is here? Should we revise it?

Not closing the issue for now..

**Comment by mtzguido** [comment] 2018-05-07 19:43
AFAIK this is fixed.

**Closed by mtzguido** 2018-05-07 19:43 UTC
Labels: kind/discussion
