### ISSUE TITLE
Extraction crashes on Ghost values

### ISSUE THREAD

**Issue by jkzinzindohoue** [FStarLang/FStar#655] opened 2016-08-29 16:57 UTC
```F#
module Bug

open FStar.Heap

let ghost_one () : GTot int = 1

assume val g: (u:unit) -> St unit

let test (u:unit) : St unit
  = ghost_one ();
    g(); // Crashes extraction
    ()
```
It crashes F* with `Failure("Impossible: Inconsistent effects Impure and Ghost")` at extraction while typechecking goes through.

**Comment by s-zanella** [comment] 2016-09-05 10:55
I'm also hitting this error while extracting `Crypto.Symmetric.Poly1305.MAC`. I could not find any workaround short of not using `Ghost`.

**Comment by nikswamy** [comment] 2016-09-22 14:34
This looks like a duplicate of #517, a particularly nasty variant.

FWIW, this variant with a `val` declaration correctly fails type-checking. 

```
module Bug655

open FStar.Heap

val ghost_one : unit -> GTot int 
let ghost_one () : GTot int = 1

assume val g: (u:unit) -> St unit

let test (u:unit) : St unit
  = ghost_one ();
    g(); // Crashes extraction
    ()
```

**Closed** 2016-09-22 17:59 UTC
Labels: bug, extraction
