### ISSUE TITLE
lax-mode + decreases clauses result in uninstantiated universes, leading to `deep_compress`-related error

### ISSUE THREAD

**Issue by W95Psp** [FStarLang/FStar#2193] opened 2020-12-07 11:25 UTC
Hi,

For a while, I've been running into the error `Internal error: unexpected unresolved (universe) uvar in deep_compress` when opening a module that uses `lex_t`
It seems that top-level definitions with such decreases clauses leave some universe variables uninstantiated.

The following module `A` imports module `B`. The first module declaration for `B` yields no error, while the three later yield the error about `deep_compress`.

```fstar
module A
open B
```

```fstar
module B

let rec j (n: nat): Tot unit (decreases (LexCons u#0 u#0 n LexTop))
  = if n=0 then () else j (n-1)

let rec f (n: nat): Tot unit (decreases (LexCons n (LexTop <: lex_t u#0)))
  = if n=0 then () else f (n-1)
    
let rec g (n: nat): Tot unit (decreases (%[n] <: lex_t u#0))
  = if n=0 then () else g (n-1)

let rec h (n: nat): Tot unit (decreases n)
  = if n=0 then () else h (n-1)

noeq type fake_lex_t =
  | FakeLexTop : fake_lex_t
  | FakeLexCons : #a: Type u#n -> a -> fake_lex_t -> fake_lex_t

let rec i (n: nat): Tot unit (decreases (FakeLexCons n FakeLexTop))
  = admit () 
```

```fstar
module B

let rec f (n: nat): Tot unit (decreases %[n]) // or (decreases (LexCons n LexTop))
  = if n=0 then () else f (n-1)
```

```fstar
module B

let foo (t:Type u#n): Type0 = True
let rec f (n: nat): Tot unit (decreases foo)
  = if n=0 then () else ()
```

```fstar
module B

type foo: Type u#m = | FOO

let rec i (n: nat): Tot unit (decreases FOO)
  = admit () 
```

Since the error was introduced (on commit 97c7acadf70ca49f1285743870eb1d17f3bbd7b4), this issue reproduces on my side.

The issue was appearing only indirectly when I open a module; I think I remember modules are loaded in a sort of lax mode. Thus, I tried my faulty `decreases` clauses in lax mode, and the error appears directly, i.e., the following fails:
```fstar
module Foo
#set-options "--lax"
type foo: Type u#m = | FOO
let i (n: nat): Tot unit (decreases FOO)
  = admit () 
```

So maybe it's type checking in lax-mode that somehow calls `deep_compress` without instantiating correctly some `uvar`s on decreases clauses, what do you think?

**Comment by mtzguido** [comment] 2020-12-11 21:33
Thanks for the report! I had observed this while bootstrapping F* with some local changes I have but couldn't find a small repro. This is probably the cause so it's great that you posted it. I think this is caused since the decreases clause is ignored in the computation of free variables in `FStar.Syntax.Free`, which can be fixed like this:
```diff
diff --git a/src/syntax/FStar.Syntax.Free.fs b/src/syntax/FStar.Syntax.Free.fs
index 1fa3c09d3f..77853c5f9b 100644
--- a/src/syntax/FStar.Syntax.Free.fs
+++ b/src/syntax/FStar.Syntax.Free.fs
@@ -198,8 +198,18 @@ and free_names_and_uvars_comp c use_cache =
               union (free_univs u) (free_names_and_uvars t use_cache)
 
             | Comp ct ->
-              let us = free_names_and_uvars_args ct.effect_args (free_names_and_uvars ct.result_typ use_cache) use_cache in
-              List.fold_left (fun us u -> union us (free_univs u)) us ct.comp_univs in
+              let decreases_vars =
+                match List.tryFind (function DECREASES _ -> true | _ -> false) ct.flags with
+                | None -> no_free_vars
+                | Some (DECREASES d) ->
+                  free_names_and_uvars d use_cache
+                | Some _ ->
+                  failwith "impossible"
+              in
+              let us = union (free_names_and_uvars ct.result_typ use_cache) decreases_vars in
+              let us = free_names_and_uvars_args ct.effect_args us use_cache in
+              List.fold_left (fun us u -> union us (free_univs u)) us ct.comp_univs
+         in
          c.vars := Some (fst n);
          n
```
But, this causes some crashes in regressions tests, for some reasons. I'll look more into it and report back.

Again thanks for the report!

**Comment by nuaaysh** [comment] 2021-01-01 11:38
Hello, @mtzguido  I find the `deep_compress` bug still exists when using the mutually inductive type! 

For instance,

- test.fst

```fshar
type tlists = list tlist
val size_tlist_ok: tl:tlist -> Tot nat (decreases %[tl])
let rec size_tlist_ok tl =
  match tl with
  | Base _ -> 1
  | Llist l -> size_tlists l
and size_tlists (l:tlists) : Tot nat (decreases %[l]) =
  match l with
  | [] -> 0
  | hd :: tl -> let tn = size_tlist_ok hd in
    tn + size_tlists tl

```
- valid.fst

```fsharp
module Valid

open Test
```

```
... fstar.exe valid.fst
(Error 339) Internal error: unexpected unresolved (universe) uvar in deep_compress
```


Now I find I even can not use the mutually inductive type 
 I get the issue if running the test.fst:

```
(Error 200) Unexpected number of universe instantiations for "size_tlists" (1 vs 0)
```
If I use the previous version, no this bug.

**Comment by aseemr** [comment] 2021-01-06 11:41
Hi @nuaaysh , as Guido mentioned in the PR that fixes this issue, this code overlaps with some other work in progress that impacts the decreases clauses more broadly (see #1916). We would first push those changes, hopefully soon, and then I will pick Guido's commits to merge them into master.

As I understand from the discussion here and on Zulip, it seems like you are not blocked on it. Please let us know if you are and we can try to find a workaround or rejig the plan. Thanks for your patience as we sort it out!

**Comment by nuaaysh** [comment] 2021-01-06 15:59
Hello, @aseemr currently my question is solved, thanks a lot!

**Comment by W95Psp** [comment] 2021-01-07 10:09
Thanks for the fix and the explanation @mtzguido, your PR is indeed solving the issue on my side!

**Comment by aseemr** [comment] 2021-02-09 09:21
I merged Guido's fix to master, closing this issue. Sorry for the delay.

**Closed by aseemr** 2021-02-09 09:21 UTC
