### ISSUE TITLE
Unexpected error when implementing mergesort

### ISSUE THREAD

**Issue by yforster** [FStarLang/FStar#166] opened 2015-03-19 15:39 UTC
I tried proving the correctness of mergesort and got "Unexpected error Failure("Bound term variable not found: sl1")"

I stripped down the code to this piece here:

```
module MergeSort
open List

assume val split : list int ->  (list int * list int)

assume val merge: l1:list int -> l2:list int ->
           Tot (l:list int { (forall x. (mem x l1 \/ mem x l2 <==> mem x l)) })

val mergesort: l:list int -> (list int)
let rec mergesort l = match l with
  | [] -> []
  | [x] -> [x]
  | _ ->
    let (l1, l2) = split l in
    let sl1 = mergesort l1 in
    let sl2 = mergesort l2 in
    merge sl1 sl2
```

I first thought that fstar fails while proving termination, but making split and mergesort total or not seems not to make a difference.

**Comment by catalin-hritcu** [comment] 2015-03-21 19:30
Hi Yannick, Seems you weren't the only one who had this problem, Enrico had it too. Hope you managed to somehow work around it for the homework.

Marking this as a duplicate of #170, because that has an even smaller file (saw this too late, sorry).

**Closed by catalin-hritcu** 2015-03-21 19:30 UTC
Labels: duplicate
