### ISSUE TITLE
Problems with dockerfiles

### ISSUE THREAD

**Issue by carsten-j** [FStarLang/FStar#526] opened 2016-05-10 20:40 UTC
In order to build an image with the dockerfile from the Ubuntu Wliy I ran into a couple of issues.
1. ocamlfind seems to need gmp library so I had to add libgmp3-dev to the list of packages installed by apt-get. `(FIXED)`
2. make targets listed requires zarith package for ocaml so I had to add it to opam install `(FIXED)`
3. The last command in the dockerfile "RUN opam config exec -- make -C src regressions OTHERFLAGS=--lax" assumes that ../bin/tests.exe exists but that is not build by any of the previous targets.

I am running Docker version
⇒  docker version
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:44:17 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Wed Apr 27 00:34:20 2016
 OS/Arch:      linux/amd64

All on OSX version 10.11.4

**Comment by sishtiaq** [comment] 2016-05-11 09:37
Hi @carsten-j, Do you want to make these changes to https://github.com/FStarLang/FStar/blob/master/.docker/ubuntu_wily/Dockerfile and send in a PR?

**Comment by carsten-j** [comment] 2016-05-11 11:50
Hi @sishtiaq,

I would like to send a PR but I cannot figure out what make target that creates ../bin/tests.exe 

So right now I just commented out the last line in the dockerfile
`# RUN opam config exec -- make -C src regressions OTHERFLAGS=--lax`
and I do not believe this is the right solution to submit in a PR. 

If someone can point toward the make target then I will be happy to test and submit a PR.

**Comment by sishtiaq** [comment] 2016-05-11 12:58
I think src/Makefile's $(BIN)/tests.exe does it.

**Comment by carsten-j** [comment] 2016-05-11 15:42
That make target requires the F# compiler so it will not be straightforward to call since the dockerfile do not install the F# compiler. So to fix this the dockerfile will need to install the F# compiler.

**Comment by protz** [comment] 2016-05-16 15:19
I think we'd be pretty willing to take a patch to the Makefile that moves `bin/tests.exe` outside of `make regressions`, so that the docker test file can just skip `tests.exe`.

I had it written locally but didn't commit it because there was no strong use-case for it. Let me know if you feel like fixing the Makefile.

**Comment by protz** [comment] 2016-05-16 15:19
But #527 seems to take of adding F# into the docker file so perhaps this is not needed.

**Comment by msprotz** [comment] 2016-06-16 20:20
@beurdouche 

I recently cleaned up the Makefile targets so that you can easily choose to only run the OCaml specific regressions. Can you confirm that the docker file has been updated to take advantage of the new target and now only runs "make -C ocaml-output && make regressions"?

**Comment by beurdouche** [comment] 2016-06-16 21:10
Dockerfiles currently runs the following:

```# F* Build
RUN opam config exec -- make -C src/ocaml-output

# F* Testing
RUN opam config exec -- make -C examples/unit-tests
RUN opam config exec -- make -C src regressions OTHERFLAGS=--lax```

I guess I should be able to remove unit-tests (probably included in regressions right ?) and the lax flag ?

**Comment by msprotz** [comment] 2016-06-16 21:22
yes

**Comment by beurdouche** [comment] 2016-06-16 21:25
Ok, I'll do this tomorrow morning ;)

**Comment by beurdouche** [comment] 2016-07-18 08:02
Forgot that, I will do this changes at the same time I'll handle #584

**Comment by nikswamy** [comment] 2020-03-23 19:40
Lots of work in #584. @protz @beurdouche  can this one be closed?

**Comment by msprotz** [comment] 2020-03-23 19:40
👍 for closing

**Closed** 2020-03-23 19:42 UTC
Labels: kind/enhancement
