### ISSUE TITLE
Not a protected embedded term

### ISSUE THREAD

**Issue by cpitclaudel** [FStarLang/FStar#1171] opened 2017-08-02 15:31 UTC
The line below crashes F* with `Failure("Not a protected embedded term: fun uu___735464 ->\n  FStar.Tactics.Builtins.__embed (fun a b -> a + b) <: Prims.PURE FStar.Reflection.Types.term")`:

```
let x: nat = synth_by_tactic (print (term_to_string (quote (fun a b -> a + b))))
```

**Comment by mtzguido** [comment] 2017-08-02 19:07
Duplicate of #1172.

**Closed by mtzguido** 2017-08-02 19:07 UTC
Labels: bug, duplicate, tactics
