### ISSUE TITLE
ulib doesn't compile with --cache_checked_modules

### ISSUE THREAD

**Issue by cpitclaudel** [FStarLang/FStar#1213] opened 2017-08-23 13:04 UTC
I'm not sure how to use the new `--cache_checked_modules` option:

```
$ cd ulib
$ make OTHERFLAGS=--cache_checked_modules -j8 -k
…
Failure("Corrupt file: ./FStar.Classical.fst.checked.lax")
…
Failure("Impossible: locally nameless")
…
Failure("file_of_file_idx: invalid argument: n = 13\n")
…
./FStar.Tactics.Derived.fst(44,60-44,67): (Error) Identifier not found: [FStar.Tactics.Effect.__proj__TAC__item__reflect]
Module FStar.Tactics.Effect resolved into FStar.Tactics.Effect, definition __proj__TAC__item__reflect not found
1 error was reported (see above)
…
Failure("file_of_file_idx: invalid argument: n = 9\n")
…
```

@nikswamy @aseemr Am I misusing this option?

**Comment by tahina-pro** [comment] 2017-08-24 04:41
This might have something to do with parallelism: .checked.lax files seem to be written for each dependency, thus such files may be written several times at the same time. I also experienced this kind of error on my branch (`taramana_pointers_with_codes_modifies`) but when running once more I finally got no errors.

**Comment by nikswamy** [comment] 2017-08-24 04:43
This is not meant to work with parallelism. That's why I said that we should produce .checked files in dependency order.

**Comment by kyoDralliam** [comment] 2017-08-24 12:06
Is doing `OTHERFLAGS=--cache_checked_module make` is expected to fail in `ulib` (without parallelism) ? I always get 
```
Unexpected error; please file a bug report, ideally with a minimized version of the source program that triggered the error.
Failure("Impossible: locally nameless")
```
on the second file I check (either FStar.HyperStack.ST or FStar.Seq.fst)...

**Comment by nikswamy** [comment] 2017-08-24 16:15
It worked fine for me on Windows with OCaml 4.02.3.

I was able to cache and then restore pretty much the entire stack of modules in HACL*, which of course includes the ST modules in ulib etc.

Curious where this locally nameless error comes from. Backtrace?

Nik





Get Outlook for Android<https://aka.ms/ghei36>

**Comment by kyoDralliam** [comment] 2017-08-25 12:06
Hm, I cannot reproduce the same gerror after cleaning up the `*-ver` files.
Instead I have this error, which seems to complain about some not loaded file when printing a range. (Btw, are ranges recorded as-is in the checked file ? Don't they depend on the (non-necessarily reproducible) internal state of the compiler for the mapping between the `file_idx` bits and the filename ?)

```
Unexpected error
Failure("file_of_file_idx: invalid argument: n = 7\n")
Raised at file "pervasives.ml", line 30, characters 22-33
Called from file "src/basic/ml/FStar_Range.ml", line 118, characters 56-132
Called from file "src/basic/ml/FStar_Range.ml", line 208, characters 57-74
Called from file "src/basic/ml/FStar_Range.ml", line 210, characters 30-51
Called from file "src/batList.mlv", line 169, characters 28-33
Called from file "src/batList.mlv", line 172, characters 4-12
Called from file "src/ocaml-output/FStar_SMTEncoding_Term.ml", line 1480, characters 31-66
Called from file "src/ocaml-output/FStar_SMTEncoding_Term.ml", line 1551, characters 16-39
Called from file "src/batList.mlv", line 171, characters 23-28
Called from file "src/ocaml-output/FStar_SMTEncoding_Term.ml", line 1480, characters 31-66
Called from file "src/ocaml-output/FStar_SMTEncoding_Term.ml", line 1551, characters 16-39
Called from file "src/batList.mlv", line 169, characters 28-33
Called from file "src/batList.mlv", line 172, characters 4-12
Called from file "src/ocaml-output/FStar_SMTEncoding_Term.ml", line 1480, characters 31-66
Called from file "src/ocaml-output/FStar_SMTEncoding_Term.ml", line 1551, characters 16-39
Called from file "src/ocaml-output/FStar_SMTEncoding_Term.ml", line 1551, characters 16-39
Called from file "src/batList.mlv", line 169, characters 28-33
Called from file "src/batList.mlv", line 172, characters 4-12
Called from file "src/ocaml-output/FStar_SMTEncoding_Term.ml", line 1480, characters 31-66
Called from file "src/ocaml-output/FStar_SMTEncoding_Term.ml", line 1551, characters 16-39
Called from file "src/ocaml-output/FStar_SMTEncoding_Term.ml", line 1551, characters 16-39
Called from file "src/batList.mlv", line 169, characters 28-33
Called from file "src/batList.mlv", line 172, characters 4-12
Called from file "src/ocaml-output/FStar_SMTEncoding_Term.ml", line 1480, characters 31-66
Called from file "src/ocaml-output/FStar_SMTEncoding_Term.ml", line 1551, characters 16-39
Called from file "src/batList.mlv", line 169, characters 28-33
Called from file "src/batList.mlv", line 172, characters 4-12
Called from file "src/ocaml-output/FStar_SMTEncoding_Term.ml", line 1480, characters 31-66
Called from file "src/ocaml-output/FStar_SMTEncoding_Term.ml", line 1551, characters 16-39
Called from file "src/ocaml-output/FStar_SMTEncoding_Term.ml", line 1551, characters 16-39
Called from file "src/batList.mlv", line 169, characters 28-33
Called from file "src/batList.mlv", line 172, characters 4-12
Called from file "src/ocaml-output/FStar_SMTEncoding_Term.ml", line 1480, characters 31-66
Called from file "src/ocaml-output/FStar_SMTEncoding_Term.ml", line 1551, characters 16-39
Called from file "src/ocaml-output/FStar_SMTEncoding_Term.ml", line 1551, characters 16-39
Called from file "src/batList.mlv", line 171, characters 23-28
Called from file "src/ocaml-output/FStar_SMTEncoding_Term.ml", line 1480, characters 31-66
Called from file "src/ocaml-output/FStar_SMTEncoding_Term.ml", line 1551, characters 16-39
Called from file "src/ocaml-output/FStar_SMTEncoding_Term.ml", line 1632, characters 27-57
Called from file "src/batList.mlv", line 169, characters 28-33
Called from file "src/batList.mlv", line 172, characters 4-12
Called from file "src/ocaml-output/FStar_SMTEncoding_Z3.ml", line 920, characters 8-90
Called from file "src/ocaml-output/FStar_SMTEncoding_Z3.ml", line 949, characters 26-42
Called from file "src/ocaml-output/FStar_SMTEncoding_Solver.ml", line 1148, characters 19-73
Called from file "src/ocaml-output/FStar_TypeChecker_Rel.ml", line 8188, characters 45-184
Called from file "list.ml", line 73, characters 12-15
Called from file "ulib/ml/FStar_All.ml", line 3, characters 21-24
Called from file "src/ocaml-output/FStar_TypeChecker_Rel.ml", line 8216, characters 8-64
Called from file "src/ocaml-output/FStar_TypeChecker_TcTerm.ml", line 3322, characters 35-128
Called from file "src/ocaml-output/FStar_TypeChecker_TcTerm.ml", line 5896, characters 21-1023
Called from file "src/ocaml-output/FStar_TypeChecker_TcTerm.ml", line 4967, characters 28-60
Called from file "src/ocaml-output/FStar_TypeChecker_Tc.ml", line 4048, characters 20-1023
Called from file "src/ocaml-output/FStar_TypeChecker_Tc.ml", line 4993, characters 31-46
Called from file "src/basic/ml/FStar_Util.ml", line 46, characters 14-18
Called from file "src/ocaml-output/FStar_TypeChecker_Tc.ml", line 5093, characters 14-97
Called from file "src/basic/ml/FStar_Util.ml", line 613, characters 30-37
Called from file "src/ocaml-output/FStar_TypeChecker_Tc.ml", line 5110, characters 8-76
Called from file "src/ocaml-output/FStar_TypeChecker_Tc.ml", line 5208, characters 25-77
Called from file "src/ocaml-output/FStar_TypeChecker_Tc.ml", line 5512, characters 23-49
Called from file "src/basic/ml/FStar_Util.ml", line 46, characters 14-18
Called from file "src/ocaml-output/FStar_Universal.ml", line 431, characters 20-152
Called from file "src/ocaml-output/FStar_SMTEncoding_Solver.ml", line 97, characters 20-24
Called from file "src/ocaml-output/FStar_Universal.ml", line 446, characters 20-100
Called from file "src/ocaml-output/FStar_Universal.ml", line 555, characters 18-101
Called from file "src/ocaml-output/FStar_Universal.ml", line 580, characters 32-73
Called from file "src/ocaml-output/FStar_Universal.ml", line 597, characters 25-72
Called from file "src/ocaml-output/FStar_Universal.ml", line 638, characters 27-69
Called from file "src/ocaml-output/FStar_Main.ml", line 217, characters 30-70
Called from file "src/ocaml-output/FStar_Main.ml", line 241, characters 8-13
```

**Comment by cpitclaudel** [comment] 2017-10-09 16:50
Could we make checked-file creation atomic?

**Comment by wintersteiger** [comment] 2017-10-16 14:04
I get the same error with today's F* master: 

```
...
[F* info] Lax-checking implementation of FStar.ST
[F* error] Unexpected error
[F* error] Failure("Impossible: locally nameless")
[F* error] Raised at file "pervasives.ml", line 30, characters 22-33
[F* error] Called from file "src/ocaml-output/FStar_TypeChecker_TcTerm.ml", line 2503, characters 19-37
[F* error] Called from file "src/ocaml-output/FStar_TypeChecker_TcTerm.ml", line 6356, characters 24-52
[F* error] Called from file "src/ocaml-output/FStar_TypeChecker_TcTerm.ml", line 6263, characters 19-99
[F* error] Called from file "src/ocaml-output/FStar_TypeChecker_TcTerm.ml", line 6302, characters 30-46
...
```

I get that with `--cache_checked_modules` (and  `--use_hints --use_hint_hashes --record_hints --z3refresh`) while lax-checking `mitls-fstar/src/tls/*` (with modifications). It throws a different error without `--cache_checked_modules`, but I think that's not related to this problem at all.

**Comment by aseemr** [comment] 2018-08-08 06:37
@cpitclaudel, @kyoDralliam, closing this issue since `ulib/` now works fine with `cache_checked_modules` and makefile parallelism. Please reopen if you still see the issue.

**Closed by aseemr** 2018-08-08 06:37 UTC
Labels: component/build, kind/bug
