### ISSUE TITLE
Unexpected error while compiling mitls

### ISSUE THREAD

**Issue by andreas23** [FStarLang/FStar#1143] opened 2017-07-20 12:04 UTC
When compiling mitls (version 18d0fb493503176dd193a3285f22dd220368221c) using FStar (version d97ceb4a997c1936a3ec600d526d2fb6d19d299b), I'm getting this error multiple times:

```
Unexpected error; please file a bug report, ideally with a minimized version of the source program that triggered the error.
Failure("for expression (let es = Handshake.logT (C?.hs c) h in Prims._assume (Prims.b2t (j_ < FStar.Seq.Base.length es)))\n<:\nPrims.PURE Prims.unit, Expected effect Pure; got effect Ghost")
```

**Comment by andreas23** [comment] 2017-07-20 13:36
The bug does not appear when using FStar version f0067ceb48e5d95f263d6f33ade1bfbf58385214, so the regression was introduced since then.

**Comment by mtzguido** [comment] 2017-07-20 13:43
This is very likely caused by the merge of the tactics branch, which introduced the removal of `lcomp`s (I bisected it to 4a690df0f47d783f5bf3c2f1e29acbf2fd5b51e6, I believe) and there seems to be a case that was wrongly handled. We also noticed this in FStar.Seq.Sorted, where I worked around it, but then forgot to fix the compiler... so thanks for opening the issue!

I'll get on it..

**Comment by mtzguido** [comment] 2017-07-30 22:28
Terribly sorry for the delay. This is now fixed in master. It wasn't the same thing I saw with `FStar.Seq.Sorted` (which was the one related to lcomp's, also fixed now) but a bug introduced by me in extraction recently.

**Closed by mtzguido** 2017-07-30 22:28 UTC
