### ISSUE TITLE
tactics: exact is too strict

### ISSUE THREAD

**Issue by cpitclaudel** [FStarLang/FStar#1252] opened 2017-09-19 13:42 UTC
For example, this currently fails:

```
module SynthByTacticVC

open FStar.Tactics

assume val p: int -> prop

type intp = x:int{p x}

let id_intp (x: intp) : intp = x

let f : intp =
  synth_by_tactic (exact (q_id <-- quote id_intp;
                          q_one <-- quote 1;
                          return (pack (Tv_App q_id (q_one, Q_Explicit)))))
```

Is there (should there be?) a way to make `exact` create a new goal `p 1`?

**Comment by mtzguido** [comment] 2017-10-12 00:37
Sorry, I never replied to this. This is not related to synth, and `exact` will indeed spin off *guards* in separate queries.

The problem is that when we apply `exact (quote 1)`, we infer the type of `1`, get `int`, and try to unify that with `intp`, which of course fails.
Note this example fails too:
```
let f : nat = synth_by_tactic (exact (quote 1))
```
saying "expected `nat`, got `int`".

A fix for this is setting the environment's expected type to `nat` before typechecking, but I remember that introduced some annoying regression, so I didn't merge it.

I'll check again, and hopefully find a good solution.

**Comment by mtzguido** [comment] 2017-10-30 01:53
This now works, given that we use `exact_guard`. I added a regression test for it.

**Closed by mtzguido** 2017-10-30 01:53 UTC
Labels: component/tactics, kind/discussion
