### ISSUE TITLE
Assertion failure when defining malformed sum type

### ISSUE THREAD

**Issue by TWal** [FStarLang/FStar#2570] opened 2022-05-02 10:01 UTC
See the following example:

```fstar
type test (t:Type0) =
  | Test: unit
```

It gives the following error:
```
(Error 18) ASSERTION FAILURE: firstN
F* may be in an inconsistent state.
Please file a bug report, ideally with a minimized version of the program that triggered the error.
```

**Comment by aseemr** [comment] 2022-05-11 11:10
The root cause is same as #2522. I have a fix in `aseem_misc2`, will push.

**Comment by aseemr** [comment] 2022-05-11 16:16
Fixed in master, thanks for the report!

**Closed as completed by aseemr** 2022-05-11 16:16 UTC
