### ISSUE TITLE
Equality on Type breaks the backend

### ISSUE THREAD

**Issue by jkzinzindohoue** [FStarLang/FStar#540] opened 2016-06-03 12:46 UTC
The following code 
```F#
module Test

let test (a:Type) (b:Type) : Lemma (True) = 
  let _ =  a <> b in ()
```
throws the following error when extracting to ocaml
```
Error: Unexpected error; please file a bug report, ideally with a minimized version of the source program that triggered the error.
Failure("Impossible: ill-typed application:\n\thead=Prims.op_Equality, arg=a, tag=Tm_name: a\n\texpected type unit, got Obj.t")
```

**Comment by nikswamy** [comment] 2016-06-03 16:35
@aseemr 

This will be fixed by Aseem's branch that restricts equality appropriately. No fix to the backend.

**Comment by nikswamy** [comment] 2016-06-03 16:36
Duplicate of #510

**Closed by nikswamy** 2016-06-03 16:36 UTC
Labels: bug, extraction

**Comment by jkzinzindohoue** [comment] 2016-06-03 19:29
But does it not remain an extraction issue ?
The "problematic" code should be erased as it is the body of a lemma, so why should it impact the extraction mechanism ?
