### ISSUE TITLE
Issue with split file interfaces

### ISSUE THREAD

**Issue by VincentCheval** [FStarLang/FStar#2137] opened 2020-09-09 06:52 UTC
Hello,

I may have encountered a bug when splitting my .fst into .fsti and .fst following the indications in [F★ interfaces (split file, more complicated version)](https://github.com/FStarLang/FStar/wiki/F★-interfaces-%28split-file%2C-more-complicated-version%29).

If I write a very basic module TestA as follows, it works by running `fstar testA.fsti testA.fst`
testA.fsti
```
module TestA
val i : nat
val f: nat -> nat
val proof : i:nat -> Lemma (ensures (f i > 2))
```
testA.fst
```
module TestA
let i = 0
let f i = i+3
let proof (i:nat) = ()
```

If I remove any of the `val` declaration in the file testA.fsti it also works. However, it does not seem to be the case when I add the function `prove_impl` to testA.fst as follows and without changing the testA.fsti
```
module TestA
let i = 0
let f i = i+3
let proof (i:nat) = ()
let prove_impl #hyp #goal proof =
  let q () = goal in
  FStar.Classical.impl_intro_gen #hyp #q proof
```
I get the error 
```
testA.fst(2,4-2,5): (Error 47) Duplicate top-level names [TestA.i]; previously declared at testA.fsti(2,4-2,5)
```
I have the impression that something in the function `prove_impl` suddenly make FStar consider both .fsti and .fst as two distinct .fst.

I also tried to adding the `val` declaration associated to `prove_impl` either in testA.fst or testA.fsti but I get the same error message:
testA.fsti
```
module TestA
val i : nat
val f: nat -> nat
val proof: nat -> Lemma (ensures (f i > 2))
val prove_impl:
  #hyp: Type ->
  #goal: Type ->
  (_: (_:unit{ hyp } -> Lemma (ensures (goal)))) ->
  Lemma (ensures (hyp ==> goal))
```

Reading [Some issues and workarounds when writing interfaces](https://github.com/FStarLang/FStar/wiki/Some-issues-and-workarounds-when-writing-interfaces), I imagine that the problem comes from the types declaration. I tried however to replace the `Type` by `Type0` but it did not work.

Thanks !

Best,
Vincent

**Comment by aseemr** [comment] 2020-09-09 07:26
@VincentCheval , it works for me:

```
aseemr@ASEEMR-Z840 ~/evmd/FStar
$ cat TestA.fsti
module TestA

val i : nat
val f: nat -> nat
val proof : i:nat -> Lemma (ensures (f i > 2))
val prove_impl:
  #hyp: Type ->
  #goal: Type ->
  (_: (_:unit{ hyp } -> Lemma (ensures (goal)))) ->
  Lemma (ensures (hyp ==> goal))

aseemr@ASEEMR-Z840 ~/evmd/FStar
$ cat TestA.fst
module TestA
let i = 0
let f i = i+3
let proof (i:nat) = ()
let prove_impl #hyp #goal proof =
  let q () = goal in
  FStar.Classical.impl_intro_gen #hyp #q proof

aseemr@ASEEMR-Z840 ~/evmd/FStar
$ fstar.exe TestA.fst
Verified module: TestA
All verification conditions discharged successfully
```

I have also checked in the emacs mode. Am I trying to reproduce it wrong?

**Comment by VincentCheval** [comment] 2020-09-09 09:53
The problem arises when you run `fstar.exe testA.fsti testA.fst` as suggested in [F★ interfaces (split file, more complicated version)](https://github.com/FStarLang/FStar/wiki/F★-interfaces-%28split-file%2C-more-complicated-version%29)

**Comment by aseemr** [comment] 2023-03-28 11:52
Yeah this mode of invoking F* on multiple command line files is not supported anymore. We have resources like `ulib/gmake/Makefile.tmpl` or https://fstarlang.github.io/lowstar/html/ (the Low* tutorial) that detail how projects should be set up. I will add a deprecation note to the outdated wiki pages. Thanks!

**Closed by aseemr** 2023-03-28 11:52 UTC
