### ISSUE TITLE
Unexpected Error: "Impossible: this instance has already been assigned a solution"

### ISSUE THREAD

**Issue by ngrimm** [FStarLang/FStar#398] opened 2015-09-28 12:52 UTC
produced by the following minimized example:

```
val foo : unit -> St (unit)
let foo _ = ()
 
val bar : unit -> option (u:unit & (unit -> St (unit)))
let bar _ = Some (| (), (fun () -> foo ()) |)
```

**Comment by catalin-hritcu** [comment] 2015-12-04 14:34
This fails for me with a syntax error:
```
fstar.exe bug398.fst 
/home/hritcu/Projects/fstar/pub/examples/bug-reports/bug398.fst(6,56-6,56): Syntax error
```

**Comment by catalin-hritcu** [comment] 2015-12-04 14:41
Maybe this is getting masked by #404?

**Comment by s-zanella** [comment] 2015-12-04 14:49
It's related to #404 in that it fails with `Syntax error` when using the F# build. 
When using the OCaml build, it fails with `Unexpected error`.

**Comment by auduchinok** [comment] 2016-05-30 13:19
I got the same error with a code from the tutorial.
```fsharp
let newCounter init =
  let c = ref init in
  fun () -> c := !c + 1; !c
```

**Comment by catalin-hritcu** [comment] 2016-05-30 16:00
@auduchinok I can indeed reproduce this on the `master` branch without `--universes`. Please note though that the usage of F\* without `--universes` is currently discouraged, and this will not be fixed there. You should instead use `--universes`, which will soon become the default mode.

With `--universes` I get a normal typing error:
```
(5,12-5,13) : Error
Expected expression of type "(FStar.ST.ref (?15616 init c uu___))";
got expression "c" of type "Type"
```
which I can fix by changing `ref` to `ST.alloc`. I've done this in more places in the tutorial, since it seems we have a lot of stale code that's not part of the build there. So thanks for reporting.

@ngrimm Could you please check whether your problem still occurs with `--universes` and close the issue if it doesn't?

**Comment by beurdouche** [comment] 2016-05-30 16:02
@catalin-hritcu @nikswamy : should we move the online tutorial to the `--universes` option at some point ?

**Comment by catalin-hritcu** [comment] 2016-05-30 16:13
@beurdouche  That would indeed be great. All code that doesn't currently `--universes` needs to be ported, so feel free start a new meta issue about that and lend a hand.

**Comment by sishtiaq** [comment] 2016-05-31 17:00
I can help with this: assign stuff to me.

**Comment by vkanne-msft** [comment] 2016-06-16 20:08
We only fix bugs in universes now. This wont be fixed. 
Porting tutorial is a separate issue.

**Closed by vkanne-msft** 2016-06-16 20:08 UTC
Labels: bug
