### ISSUE TITLE
Incorrect type annotation on inner let binding succeeds.

### ISSUE THREAD

**Issue by aseemr** [FStarLang/FStar#253] opened 2015-06-04 17:45 UTC
Say f is a total order, then the function
```
fun p1 p2 -> f (fst p1) (fst p2)
```
is not antisymmetric, `p1 = (a, b1)` and `p2 = (a, b2)`, where `b1 != b2`.

However, following code successfully type checks (the annotation on inner let binding).
```
type cmp (a:Type) = f:(a -> a -> Tot bool){forall a1 a2. (f a1 a2 /\ f a2 a1)  ==> a1 = a2}

val p_cmp: #k:Type -> #v:Type -> cmp k -> Tot unit
let p_cmp 'k 'v f =
  let g:(cmp ('k * 'v)) = fun p1 p2 -> f (fst p1) (fst p2) in
  ()
```

**Comment by aseemr** [comment] 2015-06-04 17:50
If I change the return type of p_cmp unit to cmp (k * v), and return g, then I do get a subtyping failed error.

**Comment by catalin-hritcu** [comment] 2015-06-05 05:59
Same as #183?

**Comment by catalin-hritcu** [comment] 2015-06-11 14:32
Probably not really a duplicate of #183. There annotations on matches are completely ignored all the time, while here for real lets one needs a bit of work to make this fail.

**Comment by vkanne-msft** [comment] 2016-06-17 18:41
Fails now as expected with the --universes flag. @catalin-hritcu can you kindly verify as well?

**Closed by vkanne-msft** 2016-06-17 18:41 UTC
Labels: bug, needs confirmation with --universes

**Comment by catalin-hritcu** [comment] 2016-06-18 11:57
Seems that this indeed no longer happens (with or without universes).
