### ISSUE TITLE
by_induction_on fails for lemmas with two arguments

### ISSUE THREAD

**Issue by ckeller** [FStarLang/FStar#100] opened 2014-12-16 17:44 UTC
F* cannot prove this lemma using automatic induction:
```
val append_length :
  l1:list 'a -> l2:list 'a ->
  Lemma
    (requires True)
    (ensures (length (append l1 l2) = length l1 + length l2))
let rec append_length l1 l2 = by_induction_on l1 append_length
```

**Comment by catalin-hritcu** [comment] 2015-02-17 13:21
I think the right way to solve this is to drop using_induction_hyp altogether and implement #51 instead.

**Comment by catalin-hritcu** [comment] 2015-07-13 10:03
Syntax got changed to `by_induction_on l1 append_length`, but the problem is still here.

**Comment by catalin-hritcu** [comment] 2016-07-12 20:39
`by_induction_on` is gone for good. It never really worked very well, and Nik would prefer to figure out something properly via a tactic language. Closing as wontfix.

**Closed by catalin-hritcu** 2016-07-12 20:39 UTC
Labels: enhancement, wontfix
