### ISSUE TITLE
Why can't I access record parameters in a dependent type? 

### ISSUE THREAD

**Issue by A-Manning** [FStarLang/FStar#663] opened 2016-09-01 14:30 UTC
I apologise for the barrage of syntax questions, but there's nowhere else to ask...
Consider the code here, outlining the basics of a red-black tree: 

```
module RedBLackTree

// A node is either Red or Black
type colour = 
  | R // Red
  | B // Black

// A node is either a Tree or Empty
type node =
  | Node of tree
  | E
// A tree has a key, colour, a left child and a right child
and tree = {key:int; col:colour;
      left: node; right: node;}

let myRoot:node = Node ({key=4;col=R;left=E;right=E;}<:tree)
// Expected expression of type "tree"
let foo = myRoot.key

```

why can't I use `myRoot.key`?

**Comment by s-zanella** [comment] 2016-09-01 14:33
Because `myRoot` has type `node`, not `tree`.
You can get the underlying record of type `tree` by projecting using `Node._0 myRoot`. If you had given a name to the argument of `Node`, e.g. `Node: t:tree -> node` then you would be have been able to use `Node.t myRoot`.

**Comment by A-Manning** [comment] 2016-09-01 15:08
I changed the definition of `Node` to give the argument a name, as you suggested - but when I try to use `Node.t n` for some `node` n, I get the error `Expected type "node";`

```
module RedBLackTree

// A node is either Red or Black
type colour = 
  | R // Red
  | B // Black

// A node is either a Tree or Empty
type node =
  | Node: t:tree -> node
  | E
// A tree has a key, colour, a left child and a right child
and tree = {key:int; col:colour;
	  left: node; right: node;}
// We will assume the properties that a leaf is black

 

let myRoot:node = Node ({key=4;col=R;left=E;right=E;}<:tree)

val getKey: n:node -> Tot int
let getKey n:node = (Node.t n).key
```
Source code is above

**Comment by msprotz** [comment] 2016-09-01 15:15
Right, but what happens when `n` is `E`, not `Node`? Your code only works if you know first that `n` is in the `Node` case of your `node` inductive type.

**Comment by A-Manning** [comment] 2016-09-01 15:18
Can I type n to ensure that it's Node? like ` n:node{n=Node}`?

**Comment by msprotz** [comment] 2016-09-01 15:19
Yes. `let getKey (n:node{is_Node n}) = n.t.key` (maybe)...

**Comment by A-Manning** [comment] 2016-09-01 15:21
I assume you've used is_Node n as a separate function- how would it be implemented? 

Like this?
```
let is_Node n:node = function 
  | Node -> True
  | E -> False
```

**Comment by s-zanella** [comment] 2016-09-01 15:22
Such discriminator functions are generated for every constructor (as projectors, e.g. `Node.t`)

**Comment by A-Manning** [comment] 2016-09-01 15:24
That's pretty cool, thanks

**Comment by markulf** [comment] 2016-09-01 23:31
Should we turn this issue into a better description of these features in the wiki? Tempted to reopen.

**Comment by s-zanella** [comment] 2016-09-01 23:38
The tutorial explains projectors and discriminators in section 4.4. I don't think it's wise to duplicate that explanation in the wiki. Perhaps the tutorial should describe the naming scheme for projectors of anonymous arguments, but I don't see much more we could distill from this issue.

**Comment by msprotz** [comment] 2016-09-01 23:45
I think the issue highlights the lack of a reference manual; the tutorial is nice but it's hard to jump to a specific section.

**Comment by markulf** [comment] 2016-09-01 23:49
Should we point to tutorial sections from the wiki, or to reference manual material from the tutorial This might be a first step.

If the tutorial were the answer, I would have expected to see a link to the relevant tutorial subsection in this issue.

**Comment by msprotz** [comment] 2016-09-02 02:11
A syntactic reference (e.g. records are not dependent; one-branch inductives are; names are optional for inductives; `e.Some.v` syntax, etc.) would be helpful, and it would contain a pointer to the tutorial, I guess...?

**Comment by cpitclaudel** [comment] 2017-10-04 14:44
We now have a separate issue tracking the syntax reference; filing this as duplicate of https://github.com/FStarLang/FStar/issues/680

**Closed by cpitclaudel** 2017-10-04 14:44 UTC
Labels: documentation
