### ISSUE TITLE
Type-checking Pervasives slow because of definition of tuples

### ISSUE THREAD

**Issue by cpitclaudel** [FStarLang/FStar#1079] opened 2017-06-13 18:27 UTC
```
$ echo "module Empty" > Empty.fst


$ time bin/fstar.exe Empty.fst
Verified module: Empty (2 milliseconds)
All verification conditions discharged successfully

real	0m3.000s
user	0m2.948s
sys	0m0.032s


$ time bin/fstar.exe --explicit_deps Empty.fst
All verification conditions discharged successfully

real	0m0.069s
user	0m0.052s
sys	0m0.008s
```

**Comment by catalin-hritcu** [comment] 2017-06-13 18:55
The difference doesn't seem as huge on my machine
(on Arch Linux with the OCaml version of F\* master)
```
[hritcu@resurrected pub]$ time -p bin/fstar.exe Empty.fst
Verified module: Empty (6 milliseconds)
All verification conditions discharged successfully
real 0.86
user 0.84
sys 0.03

[hritcu@resurrected pub]$ time -p bin/fstar.exe --explicit_deps Empty.fst
All verification conditions discharged successfully
real 0.10
user 0.09
sys 0.01
```

**Comment by mtzguido** [comment] 2017-06-13 19:04
Apparently this is caused by `FStar.Pervasives` not being included with explicit deps.

```
$ time bin/fstar.exe Empty.fst --debug y
Checking module: Prims
Lax-checking implementation of Prims
Auto-deps kicked in; here's some info.
Here's the list of filenames we will process: /home/guido/fstar/ulib/FStar.Pervasives.fst Empty.fst
Here's the list of modules we will verify: empty
Checking module: Pervasives
Lax-checking implementation of FStar.Pervasives
Checking module: Empty
Verifying implementation of Empty
Verified module: Empty (7 milliseconds)
All verification conditions discharged successfully

real	0m1.016s
user	0m0.948s
sys	0m0.048s

$ time bin/fstar.exe --explicit_deps Empty.fst --debug y
Checking module: Prims
Lax-checking implementation of Prims
Checking module: Empty
Lax-checking implementation of Empty
All verification conditions discharged successfully

real	0m0.117s
user	0m0.088s
sys	0m0.016s

$ time bin/fstar.exe --explicit_deps ulib/FStar.Pervasives.fst Empty.fst --debug y
Checking module: Prims
Lax-checking implementation of Prims
Checking module: Pervasives
Lax-checking implementation of FStar.Pervasives
Checking module: Empty
Lax-checking implementation of Empty
All verification conditions discharged successfully

real	0m1.021s
user	0m0.964s
sys	0m0.040s
```

Also, beware that with explicit deps, the module is not verified (only lax-checked) unless `--verify_module` is added. So, this happens
```
$ cat Empty.fst 
module Empty
let x : squash False = ()

$ ./bin/fstar.exe --explicit_deps Empty.fst 
All verification conditions discharged successfully

$ ./bin/fstar.exe Empty.fst 
./Empty.fst(3,23-3,25): (Error) Subtyping check failed; expected type Prims.squash Prims.l_False; got type Prims.unit (see also ./Empty.fst(3,15-3,20))
Verified module: Empty (259 milliseconds)
```

**Comment by cpitclaudel** [comment] 2017-06-13 19:39
Thanks.  I wonder why it's so slow to typecheck Pervasives.fst.  It would be nice to have a way to cache the results of the typechecking, too, since it's costing 1-3 seconds on every run.

**Comment by mtzguido** [comment] 2017-06-13 19:57
Did some tests and seems definitions of tuples account for about 3/4 of the total, a significant part. We noticed this was the case for big *dependent* tuples with @nikswamy not long ago, and removed a big chunk of them (f46212aaebe).

For quick tests, one can just empty out pervasives

**Comment by mtzguido** [comment] 2017-06-13 19:58
(pressed the wrong button)

Did some tests and seems definitions of tuples account for about 3/4 of the total, a significant part. We noticed this was the case for big _dependent_ tuples with @nikswamy not long ago, and removed a big chunk of them (f46212aaebe).

For quick tests, one can just empty out pervasives, but not sure about a good general solution.

**Comment by cpitclaudel** [comment] 2017-06-25 20:08
@mtzguido Could you give a quick summary of how you profiled the code and measured that? I'm rusty at OCaml profiling :) Thanks!

**Comment by mtzguido** [comment] 2017-06-25 21:25
I didn't run a profiler, I just did a quick-and-dirty run of F* over different versions of Pervasives and measured the module checking time.

For a slightly less quick-and-dirty solution, I just added an option to print the time taken for each top-level declaration in commit e67db42e7. Here's the relevant output for `tuple8`

```
$ ./bin/fstar.exe ulib/FStar.Pervasives.Native.fst --debug FStar.Pervasives.Native --debug_level TCDeclTime
[...]
Checked FStar.Pervasives.Native.tuple8, FStar.Pervasives.Native.Mktuple8 in 45 milliseconds
Checked FStar.Pervasives.Native.uu___is_Mktuple8 in 0 milliseconds
Checked let uu___is_Mktuple8 : _ in 0 milliseconds
Checked FStar.Pervasives.Native.__proj__Mktuple8__item___1 in 1 milliseconds
Checked let __proj__Mktuple8__item___1 : _ in 33 milliseconds
Checked FStar.Pervasives.Native.__proj__Mktuple8__item___2 in 1 milliseconds
Checked let __proj__Mktuple8__item___2 : _ in 29 milliseconds
Checked FStar.Pervasives.Native.__proj__Mktuple8__item___3 in 0 milliseconds
Checked let __proj__Mktuple8__item___3 : _ in 31 milliseconds
Checked FStar.Pervasives.Native.__proj__Mktuple8__item___4 in 0 milliseconds
Checked let __proj__Mktuple8__item___4 : _ in 29 milliseconds
Checked FStar.Pervasives.Native.__proj__Mktuple8__item___5 in 0 milliseconds
Checked let __proj__Mktuple8__item___5 : _ in 29 milliseconds
Checked FStar.Pervasives.Native.__proj__Mktuple8__item___6 in 0 milliseconds
Checked let __proj__Mktuple8__item___6 : _ in 30 milliseconds
Checked FStar.Pervasives.Native.__proj__Mktuple8__item___7 in 0 milliseconds
Checked let __proj__Mktuple8__item___7 : _ in 31 milliseconds
Checked FStar.Pervasives.Native.__proj__Mktuple8__item___8 in 0 milliseconds
Checked let __proj__Mktuple8__item___8 : _ in 31 milliseconds
Checked FStar.Pervasives.Native.__proj__Mktuple8__item___1 in 0 milliseconds
Checked let __proj__Mktuple8__item___1 : _ in 0 milliseconds
Checked FStar.Pervasives.Native.__proj__Mktuple8__item___2 in 0 milliseconds
Checked let __proj__Mktuple8__item___2 : _ in 0 milliseconds
Checked FStar.Pervasives.Native.__proj__Mktuple8__item___3 in 0 milliseconds
Checked let __proj__Mktuple8__item___3 : _ in 0 milliseconds
Checked FStar.Pervasives.Native.__proj__Mktuple8__item___4 in 0 milliseconds
Checked let __proj__Mktuple8__item___4 : _ in 0 milliseconds
Checked FStar.Pervasives.Native.__proj__Mktuple8__item___5 in 0 milliseconds
Checked let __proj__Mktuple8__item___5 : _ in 0 milliseconds
Checked FStar.Pervasives.Native.__proj__Mktuple8__item___6 in 0 milliseconds
Checked let __proj__Mktuple8__item___6 : _ in 0 milliseconds
Checked FStar.Pervasives.Native.__proj__Mktuple8__item___7 in 0 milliseconds
Checked let __proj__Mktuple8__item___7 : _ in 0 milliseconds
Checked FStar.Pervasives.Native.__proj__Mktuple8__item___8 in 0 milliseconds
Checked let __proj__Mktuple8__item___8 : _ in 0 milliseconds
Verified module: FStar.Pervasives.Native (1144 milliseconds)
All verification conditions discharged successfully
```

It prints the time for source top-level and for each "derived" top-level generated internally by the compiler separated. It might be confusing as a programmer, but here we can see that it's the checking of each projector what contributes the most to the time, ~30ms times 8 = ~240ms. (Each appears twice because their declarations and definitions are separate as well.

**Comment by cpitclaudel** [comment] 2017-06-25 21:28
Wonderful, thanks! :)

**Comment by nikswamy** [comment] 2017-10-16 00:09
Closing this. Especially since we now have `--cache_checked_modules`

**Closed by nikswamy** 2017-10-16 00:09 UTC
Labels: area/usability, kind/enhancement
