### ISSUE TITLE
Default effects for top-level values

### ISSUE THREAD

**Issue by ngrimm** [FStarLang/FStar#289] opened 2015-07-29 14:49 UTC
In the following code, `assert(False)` succeeds.
```
module Fail

val foo : unit -> ST unit 
                     (requires (fun _ -> True))
                     (ensures  (fun _ r _  -> True)) 
let foo  () = ()

val test : unit -> unit
let test () = ()

(* val bar : unit -> unit *)
let bar () = let u = foo () in assert(False) //; test ()
```
There is also some additional strange behaviour:
* Any reasonble explicit type I tried to give to `bar` caused the assertion to fail. 
(except for something like `val bar : u:unit{False} -> unit`. However, if I use the option `--log_types` it prints the type 
`let bar : (_1_10:unit -> STATE (unit))`)

* If i add a function call to any other function (e.g., `test`), the assertion fails

* `assert(False)` does not succeed in the body of `foo`, but without the call to `foo`  `assert(False)` does not succed in `bar`

* This seems to be specific to `ST` (and also `ST2`). If i give the same type to `foo` in `Pure` or `Div` the assertion fails.

**Comment by catalin-hritcu** [comment] 2015-07-30 03:52
Discovered that `log_types` ignores effect arguments, but you can print them with `print_effect_args`:
```
../../bin/fstar.exe bug289.fst --log_types --print_effect_args
val Bug289.foo : (unit -> St (unit) )
let foo : (unit -> St (unit) )
let bar : (_1_2:unit -> STATE (unit) (fun post h0 -> ((forall (a). (forall (h). (if True then (forall (a). (forall (h1). ((True /\ True) ==> (forall (x). ((False /\ True) ==> ((x == (_assert False ())) ==> ((~ (a == x)) \/ (~ (h == h1))))))))) else True \/ (post a h)))) /\ if True then (True /\ (forall (a). (forall (h1). ((True /\ True) ==> (False /\ (forall (x). (True ==> ((x == (_assert False ())) ==> True)))))))) else False)), (fun post h0 -> (forall (a). (forall (h). (if True then (forall (a). (forall (h1). ((True /\ True) ==> (forall (x). ((False /\ True) ==> ((x == (_assert False ())) ==> ((~ (a == x)) \/ (~ (h == h1))))))))) else True \/ (post a h))))))
```
This shows the wp F* is inferring for this ... hope it helps diagnose this better.

**Comment by aseemr** [comment] 2015-07-30 03:58
Discussed this with Nik today. This is expected behavior, perhaps not intuitive.

For all effects *except ST*, if the programmer does not write a val declaration, F* checks the inferred wp w.r.t. a default wp (see default effects in prims). This end up verifying the internal assertions of the function.

For ST, this is not the case, there is no default wp: the assertions are just added to the inferred wp and not verified (until the function is called), which is what's happening here.

1. If a val decl. is added for bar, F* tries to verify the internal assertion, and hence fails as expected.

2. 'test' is in ALL effect. Calling test in bar makes the inferred type of bar to be in ALL, which means F* uses default ALL wp, and hence assertion fails.

3. foo has a val decl., hence assert(False) fails in foo. If call to foo is removed from bar, then bar is just in PURE, which means F* uses PURE default wp, and hence assertion fails.

**Comment by catalin-hritcu** [comment] 2015-07-30 04:41
This seems wrong. What's the reason for not providing a default for St as well?

**Comment by catalin-hritcu** [comment] 2015-07-30 04:47
Otherwise I would propose to reject all computations in St without an explicit annotation. Allowing them is simply unsound.

**Comment by catalin-hritcu** [comment] 2015-07-30 05:18
Here is an annotation one can give to `bar` without triggering the assertion failure:
```
val bar : unit -> STATE unit (fun (post:unit->heap->Type) _ -> False)
                             (fun (post:unit->heap->Type) _ -> False)
let bar () = let u = foo () in assert(False)
```
I find this disturbing.

(It's also strange that if I write `_` instead of `(post:...)` this fails with `Kinds "(_1_2:U6448 -> _1_4:(U6451 _1_2) -> Type)" and "((unit -> heap -> Type) -> heap -> Type)" are incompatible`)

**Comment by catalin-hritcu** [comment] 2015-07-30 05:24
OK, nevermind my last comment. The type I wrote is equivalent to this:
```
val bar : unit -> ST unit (requires (fun _ -> False))
                          (ensures (fun _ _ _ -> False))
```
which is also accepted, but this is reasonable. The problem is when `False` is not an explicit precondition.

**Comment by aseemr** [comment] 2015-07-30 05:24
Why is the last example you gave strange, if you have False in context, anything goes. It has nothing to do with ST.

val foo: unit -> PURE unit (fun 'p -> False) (fun 'p -> False)
let foo _ = assert (False)

val bar: unit -> Lemma (requires False) (ensures True)
let bar _ = assert (False)

**Comment by catalin-hritcu** [comment] 2015-07-30 06:32
Tried adding a default for `STATE` just to see what would happen:
```
default effect XXX (a:Type) =
         STATE a (st_null_wp heap a) (st_null_wp heap a)
```
and it breaks 3 of our tests
* `examples/algorithms/counters.fst` fails:
```
../../bin/fstar.exe  --admit_fsi Set ../../lib/set.fsi ../../lib/heap.fst ../../lib/list.fst ../../lib/string.fst ../../lib/st.fst counters.fst intsort.fst insertionsort.fst mergesort.fst
counters.fst(58,79-58,84): Subtyping check failed; expected type (unit -> InvST (int)); got type (_6_32:unit -> XXX (int))
counters.fst(73,41-73,46): Subtyping check failed; expected type (unit -> InvST (int)); got type (_6_50:unit -> XXX (int))
Error: 2 errors were reported (see above)
```
* `examples/security/acls2.fst` fails:
```
../../bin/fstar.exe  --admit_fsi Set ../../lib/set.fsi ../../lib/heap.fst ../../lib/list.fst ../../lib/string.fst ../../lib/st.fst acls.fst acls2.fst
acls2.fst(93,10-93,16): pre-condition at acls2.fst(74,48-74,60)
```
* `examples/unit-tests/unit1.fst` fails:
```
../../bin/fstar.exe  --admit_fsi Set ../../lib/set.fsi ../../lib/heap.fst ../../lib/list.fst ../../lib/string.fst ../../lib/st.fst ../../lib/int32.fst unit1.fst unit2.fst testset.fst short-circuit.fst
unit1.fst(382,8-382,19): Subtyping check failed; expected type (x:(ref int) -> ST (int)); got type (y:(ref int) -> ST (int))
```
* as well as `st2.fst`, which fails all over even if adding a similar default to `STATE2`:
```
type st2_null_wp (heap:Type) (a:Type)
                 (p:STPost_h heap2 a) (h:heap2) =
     (forall (x:a) (h:heap2). p x h)
default effect XXX2 (a:Type) =
         STATE2 a (st2_null_wp heap a) (st2_null_wp heap a)
```
Both with or without `XXX2` the errors are these:
```
../bin/fstar.exe st2.fst 
st2.fst(53,0-53,33): post-condition at st2.fst(52,41-52,75)
st2.fst(62,0-62,43): post-condition at st2.fst(61,41-61,74)
st2.fst(72,0-72,35): post-condition at st2.fst(71,41-71,74)
st2.fst(82,0-82,35): post-condition at st2.fst(81,41-81,74)
st2.fst(92,0-92,35): post-condition at st2.fst(91,41-91,74)
st2.fst(102,0-102,35): post-condition at st2.fst(101,41-101,74)
st2.fst(112,0-112,35): post-condition at st2.fst(111,41-111,79)
st2.fst(122,0-122,35): post-condition at st2.fst(121,41-121,102)
st2.fst(135,0-135,67): post-condition at st2.fst(134,62-134,94)
st2.fst(206,0-206,66): post-condition at st2.fst(205,54-205,108)
st2.fst(304,0-307,37): post-condition at st2.fst(303,42-303,73)
```

**Comment by nikswamy** [comment] 2015-07-30 13:54
I think the current choices of defaults are (mostly) justifiable. 

First, recall that if a default effect is applied, the precise WP inferred for the program is lost. With that in mind, one should think to apply defaults as seldom as possible.

In the case of the PURE monad, the current default is Tot. The reasoning here is that if the Tot default succeeds, then there really is no loss in precision---the rest of the program can still reason about the Tot function via its definition. 

The same reasoning applies for GHOST and GTot. 

For the ALL effect, the default is ML. The reasoning here is that for compatibility with ML programs, if you're writing an ALL-effects function and you didn't annotate anything, then you probably want just the plain old ML type.

There is currently a default for EXN which is Ex, and DIV which is Dv. These are unjustified, IMO. I'd like to remove them.

There is no default for STATE.

Of course, if you want a default, you can always add your own default effect in your file, so long as a default is not already configured in Prims.

**Comment by nikswamy** [comment] 2015-08-04 16:27
Closing this issue, since all the issues raised are explained. We could revisit the default definitions, at some point, if it becomes necessary.

**Closed by nikswamy** 2015-08-04 16:27 UTC
